import type { DrugInfo } from '../medicalTypes';

export const DRUGS_PART1: Record<string, DrugInfo> = {
  Acetaminophen: {
    name: 'Acetaminophen (Paracetamol)',
    drugClass: 'Analgesic / Antipyretic',
    indications: ['Mild to moderate pain', 'Fever reduction', 'Headache', 'Musculoskeletal pain', 'Osteoarthritis'],
    sideEffects: ['Hepatotoxicity (overdose)', 'Skin rash (rare)', 'Nausea'],
    contraindications: ['Severe hepatic impairment', 'Known hypersensitivity', 'Acute liver failure'],
  },
  Aspirin: {
    name: 'Aspirin',
    drugClass: 'NSAID / Antiplatelet',
    indications: ['Pain relief', 'Fever reduction', 'Anti-inflammatory', 'Cardiovascular prevention', 'Post-MI prevention'],
    sideEffects: ['GI bleeding', 'Stomach ulcers', 'Tinnitus', 'Increased bruising', 'Reye syndrome in children'],
    contraindications: ['Active peptic ulcer', 'Bleeding disorders', 'Children with viral illness (Reye syndrome)', 'Severe hepatic impairment', 'Third trimester pregnancy'],
  },
  Ibuprofen: {
    name: 'Ibuprofen',
    drugClass: 'NSAID',
    indications: ['Pain relief', 'Fever reduction', 'Anti-inflammatory', 'Arthritis', 'Menstrual cramps'],
    sideEffects: ['GI upset', 'GI bleeding', 'Renal impairment', 'Cardiovascular risk', 'Hypertension'],
    contraindications: ['Active GI bleeding', 'Severe renal impairment', 'NSAID hypersensitivity', 'Third trimester pregnancy', 'Post-CABG surgery'],
  },
  Naproxen: {
    name: 'Naproxen',
    drugClass: 'NSAID',
    indications: ['Arthritis', 'Pain relief', 'Dysmenorrhea', 'Bursitis', 'Tendonitis', 'Gout'],
    sideEffects: ['GI upset', 'GI bleeding', 'Renal impairment', 'Edema', 'Hypertension'],
    contraindications: ['Active GI bleeding', 'Severe renal impairment', 'Aspirin/NSAID hypersensitivity', 'Third trimester pregnancy', 'Post-CABG'],
  },
  Ketorolac: {
    name: 'Ketorolac',
    drugClass: 'NSAID',
    indications: ['Short-term moderate to severe pain', 'Post-operative pain'],
    sideEffects: ['GI bleeding', 'Renal impairment', 'Bleeding risk', 'Nausea', 'Headache'],
    contraindications: ['Active bleeding', 'Peptic ulcer disease', 'Renal impairment', 'Concurrent aspirin/NSAIDs', 'Obstetric labor'],
  },
  Diclofenac: {
    name: 'Diclofenac',
    drugClass: 'NSAID',
    indications: ['Arthritis', 'Pain relief', 'Inflammatory conditions', 'Dysmenorrhea'],
    sideEffects: ['GI upset', 'GI bleeding', 'Hepatotoxicity', 'Renal impairment', 'Cardiovascular risk'],
    contraindications: ['Active GI bleeding', 'Hepatic impairment', 'Severe renal impairment', 'NSAID hypersensitivity', 'Post-CABG'],
  },
  Celecoxib: {
    name: 'Celecoxib',
    drugClass: 'COX-2 Selective NSAID',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Acute pain', 'Dysmenorrhea', 'Ankylosing spondylitis'],
    sideEffects: ['Cardiovascular risk', 'GI upset (less than nonselective NSAIDs)', 'Edema', 'Sulfonamide cross-reaction'],
    contraindications: ['Sulfonamide allergy', 'Post-CABG surgery', 'Active GI bleeding', 'Severe renal/hepatic impairment'],
  },
  Indomethacin: {
    name: 'Indomethacin',
    drugClass: 'NSAID',
    indications: ['Acute gout', 'Ankylosing spondylitis', 'Rheumatoid arthritis', 'Patent ductus arteriosus closure (neonate)'],
    sideEffects: ['GI ulceration', 'Headache', 'Renal impairment', 'Dizziness', 'Bone marrow suppression (rare)'],
    contraindications: ['Active GI bleeding', 'Aspirin sensitivity', 'Severe renal impairment', 'Post-CABG'],
  },
  Meloxicam: {
    name: 'Meloxicam',
    drugClass: 'NSAID',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis'],
    sideEffects: ['GI upset', 'GI bleeding', 'Renal impairment', 'Edema', 'Dizziness'],
    contraindications: ['Active GI bleeding', 'Severe renal impairment', 'Aspirin/NSAID sensitivity', 'Post-CABG'],
  },
  Piroxicam: {
    name: 'Piroxicam',
    drugClass: 'NSAID',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Acute gout'],
    sideEffects: ['GI ulceration', 'GI bleeding', 'Renal impairment', 'Photosensitivity'],
    contraindications: ['Active GI bleeding', 'Aspirin sensitivity', 'Severe renal impairment', 'Third trimester pregnancy'],
  },
  Sulindac: {
    name: 'Sulindac',
    drugClass: 'NSAID',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Ankylosing spondylitis', 'Acute gout'],
    sideEffects: ['GI upset', 'GI bleeding', 'Hepatotoxicity', 'Renal impairment'],
    contraindications: ['Active GI bleeding', 'Aspirin sensitivity', 'Severe renal impairment'],
  },
  Etodolac: {
    name: 'Etodolac',
    drugClass: 'NSAID',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Pain relief'],
    sideEffects: ['GI upset', 'GI bleeding', 'Renal impairment', 'Edema', 'Dizziness'],
    contraindications: ['Active GI bleeding', 'Aspirin sensitivity', 'Severe renal impairment', 'Post-CABG'],
  },
  Nabumetone: {
    name: 'Nabumetone',
    drugClass: 'NSAID',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis'],
    sideEffects: ['GI upset', 'Diarrhea', 'Rash', 'Hepatotoxicity', 'Renal impairment'],
    contraindications: ['Active GI bleeding', 'Aspirin sensitivity', 'Severe renal impairment'],
  },
  Morphine: {
    name: 'Morphine',
    drugClass: 'Opioid Analgesic',
    indications: ['Severe pain', 'Post-surgical pain', 'Cancer pain', 'Acute MI', 'Palliative care'],
    sideEffects: ['Respiratory depression', 'Constipation', 'Nausea/vomiting', 'Sedation', 'Pruritus', 'Urinary retention', 'Tolerance/dependence'],
    contraindications: ['Respiratory depression', 'Paralytic ileus', 'Severe asthma', 'Head injury (raised ICP)', 'Concurrent MAOIs'],
  },
  Codeine: {
    name: 'Codeine',
    drugClass: 'Opioid Analgesic',
    indications: ['Mild to moderate pain', 'Cough suppression (antitussive)'],
    sideEffects: ['Constipation', 'Nausea', 'Sedation', 'Dizziness', 'Respiratory depression (high doses)', 'Dependence'],
    contraindications: ['Severe respiratory depression', 'GI obstruction', 'Concurrent MAOIs', 'Children under 12', 'Breastfeeding (ultrarapid metabolizers)'],
  },
  Oxycodone: {
    name: 'Oxycodone',
    drugClass: 'Opioid Analgesic',
    indications: ['Moderate to severe pain'],
    sideEffects: ['Respiratory depression', 'Constipation', 'Nausea/vomiting', 'Sedation', 'Dizziness', 'Pruritus', 'Dependence'],
    contraindications: ['Severe respiratory depression', 'Paralytic ileus', 'Concurrent MAOIs', 'Acute asthma'],
  },
  Hydrocodone: {
    name: 'Hydrocodone',
    drugClass: 'Opioid Analgesic',
    indications: ['Moderate to severe pain', 'Cough suppression (combination)'],
    sideEffects: ['Respiratory depression', 'Constipation', 'Nausea', 'Sedation', 'Dizziness', 'Dependence'],
    contraindications: ['Severe respiratory depression', 'Paralytic ileus', 'Concurrent MAOIs'],
  },
  Hydromorphone: {
    name: 'Hydromorphone',
    drugClass: 'Opioid Analgesic',
    indications: ['Moderate to severe pain'],
    sideEffects: ['Respiratory depression', 'Constipation', 'Nausea/vomiting', 'Sedation', 'Dizziness', 'Dependence'],
    contraindications: ['Severe respiratory depression', 'Paralytic ileus', 'Concurrent MAOIs'],
  },
  Fentanyl: {
    name: 'Fentanyl',
    drugClass: 'Opioid Analgesic (synthetic)',
    indications: ['Severe acute pain', 'Anesthesia adjunct', 'Breakthrough cancer pain', 'Preoperative sedation'],
    sideEffects: ['Severe respiratory depression', 'Chest wall rigidity (rapid IV)', 'Constipation', 'Sedation', 'Dependence'],
    contraindications: ['Respiratory depression', 'MAOI use', 'Paralytic ileus'],
  },
  Methadone: {
    name: 'Methadone',
    drugClass: 'Opioid Analgesic',
    indications: ['Opioid use disorder (maintenance)', 'Severe chronic pain', 'Opioid detoxification'],
    sideEffects: ['QT prolongation', 'Respiratory depression', 'Sedation', 'Constipation', 'Long half-life accumulation'],
    contraindications: ['Severe respiratory depression', 'Prolonged QT', 'Concurrent MAOIs', 'Paralytic ileus'],
  },
  Tramadol: {
    name: 'Tramadol',
    drugClass: 'Opioid Analgesic (weak)',
    indications: ['Moderate to moderately severe pain'],
    sideEffects: ['Nausea/vomiting', 'Dizziness', 'Constipation', 'Seizure risk', 'Serotonin syndrome', 'Sedation'],
    contraindications: ['Concurrent MAOIs', 'SSRIs/SNRIs (serotonin syndrome)', 'Seizure disorder', 'Children', 'Breastfeeding'],
  },
  Buprenorphine: {
    name: 'Buprenorphine',
    drugClass: 'Partial Opioid Agonist',
    indications: ['Opioid use disorder', 'Chronic pain', 'Opioid dependence treatment'],
    sideEffects: ['Headache', 'Constipation', 'Nausea', 'Sedation', 'Limited respiratory depression ceiling'],
    contraindications: ['Severe respiratory depression', 'Severe hepatic impairment', 'Acute alcohol/opioid intoxication'],
  },
  Baclofen: {
    name: 'Baclofen',
    drugClass: 'Muscle Relaxant / GABA-B agonist',
    indications: ['Spasticity (MS, spinal cord injury)', 'Hiccup relief', 'Alcohol use disorder (off-label)'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Weakness', 'Nausea', 'Withdrawal seizures (abrupt stop)'],
    contraindications: ['Baclofen hypersensitivity', 'Abrupt discontinuation in spasticity', 'Severe renal impairment'],
  },
  Naloxone: {
    name: 'Naloxone',
    drugClass: 'Opioid Antagonist (Antidote)',
    indications: ['Opioid overdose reversal', 'Reversal of opioid sedation', 'Resuscitation adjunct'],
    sideEffects: ['Opioid withdrawal symptoms', 'Vomiting', 'Tachycardia', 'Hypertension', 'Agitation'],
    contraindications: ['Known hypersensitivity', 'Patients who need ongoing opioid analgesia'],
  },
  Naltrexone: {
    name: 'Naltrexone',
    drugClass: 'Opioid Antagonist',
    indications: ['Alcohol use disorder', 'Opioid use disorder (maintenance)', 'Reduction of opioid craving'],
    sideEffects: ['Nausea', 'Headache', 'Hepatotoxicity (high doses)', 'Insomnia', 'Anxiety'],
    contraindications: ['Acute opioid use or withdrawal', 'Acute hepatitis or liver failure', 'Ongoing opioid analgesia'],
  },
  Flumazenil: {
    name: 'Flumazenil',
    drugClass: 'Benzodiazepine Antagonist (Antidote)',
    indications: ['Benzodiazepine overdose reversal', 'Reversal of benzodiazepine sedation', 'Diagnosis of coma'],
    sideEffects: ['Seizures (withdrawal)', 'Agitation', 'Anxiety', 'Dizziness', 'Arrhythmias'],
    contraindications: ['Known benzodiazepine dependence (seizure risk)', 'Cyclic antidepressant overdose', 'History of seizures'],
  },
  Acetylcysteine: {
    name: 'N-Acetylcysteine',
    drugClass: 'Antidote / Mucolytic',
    indications: ['Acetaminophen overdose', 'Mucus hypersecretion (mucolytic)', 'Contrast nephropathy (controversial)'],
    sideEffects: ['Nausea/vomiting', 'Anaphylactoid reactions', 'Bronchospasm', 'Flushing', 'Pruritus'],
    contraindications: ['Known hypersensitivity', 'Severe asthma with bronchospasm history'],
  },
};
