import type { DrugInfo } from '../medicalTypes';

export const DRUGS_PART9: Record<string, DrugInfo> = {
  Isotretinoin: {
    name: 'Isotretinoin',
    drugClass: 'Retinoid (Dermatologic)',
    indications: ['Severe nodular acne', 'Refractory acne', 'Keratosis disorders'],
    sideEffects: ['Teratogenicity (iPLEDGE program)', 'Dry skin/mucosa (cheilitis)', 'Hypertriglyceridemia', 'Hepatotoxicity', 'Mood changes/suicidal ideation', 'Photosensitivity', 'Pseudotumor cerebri'],
    contraindications: ['Isotretinoin hypersensitivity', 'Pregnancy', 'Breastfeeding', 'Hepatic disease', 'Hyperlipidemia (uncontrolled)', 'Concurrent tetracyclines'],
  },
  Tretinoin: {
    name: 'Tretinoin',
    drugClass: 'Retinoid (topical)',
    indications: ['Acne vulgaris', 'Photodamaged skin', 'Fine wrinkles'],
    sideEffects: ['Skin irritation (erythema, peeling)', 'Photosensitivity', 'Retinoid dermatitis', 'Hyperpigmentation (paradoxical)'],
    contraindications: ['Tretinoin hypersensitivity', 'Concurrent photosensitizing', 'Pregnancy (topical caution)'],
  },
  Adapalene: {
    name: 'Adapalene',
    drugClass: 'Retinoid (topical, third-gen)',
    indications: ['Acne vulgaris (comedonal)'],
    sideEffects: ['Skin irritation', 'Dryness', 'Peeling', 'Photosensitivity'],
    contraindications: ['Adapalene hypersensitivity', 'Pregnancy (caution)'],
  },
  BenzoylPeroxide: {
    name: 'Benzoyl Peroxide',
    drugClass: 'Topical Acne Agent',
    indications: ['Acne vulgaris', 'Rosacea (adjunct)'],
    sideEffects: ['Skin irritation', 'Dryness', 'Bleaching of hair/clothing', 'Contact dermatitis'],
    contraindications: ['Benzoyl peroxide hypersensitivity'],
  },
  SilverSulfadiazine: {
    name: 'Silver Sulfadiazine',
    drugClass: 'Topical Antibiotic (burn)',
    indications: ['Burn wound infections', 'Burns prevention'],
    sideEffects: ['Burning/stinging', 'Rash', 'Leukopenia (rare)', 'Sulfonamide cross-reaction'],
    contraindications: ['Silver sulfadiazine hypersensitivity', 'Sulfonamide allergy', 'Pregnancy (near term)', 'Neonates (<2 months)', 'G6PD deficiency'],
  },
  Mupirocin: {
    name: 'Mupirocin',
    drugClass: 'Topical Antibiotic',
    indications: ['Impetigo', 'Skin MRSA colonization', 'Infected eczema'],
    sideEffects: ['Local irritation', 'Burning', 'Rash', 'Pruritus'],
    contraindications: ['Mupirocin hypersensitivity', 'Extensive burns', 'Renal impairment (PEG base)'],
  },
  Calcipotriene: {
    name: 'Calcipotriene',
    drugClass: 'Vitamin D Analog (topical)',
    indications: ['Plaque psoriasis'],
    sideEffects: ['Local irritation', 'Hypercalcemia (excessive use)', 'Photosensitivity', 'Rash'],
    contraindications: ['Calcipotriene hypersensitivity', 'Hypercalcemia', 'Severe renal impairment'],
  },
  Pimecrolimus: {
    name: 'Pimecrolimus',
    drugClass: 'Topical Calcineurin Inhibitor',
    indications: ['Mild-moderate atopic dermatitis'],
    sideEffects: ['Burning/stinging', 'Application site reactions', 'Herpes infection risk', 'Flushing with alcohol'],
    contraindications: ['Pimecrolimus hypersensitivity', 'Immunocompromised skin (avoid)', 'Active skin infection'],
  },
  Imiquimod: {
    name: 'Imiquimod',
    drugClass: 'Topical Immune Response Modifier',
    indications: ['Actinic keratosis', 'Basal cell carcinoma (superficial)', 'Genital warts'],
    sideEffects: ['Local erythema', 'Burning', 'Erosion/ulceration', 'Flulike symptoms', 'Hyper/hypopigmentation'],
    contraindications: ['Imiquimod hypersensitivity', 'Open wounds (avoid)', 'Autoimmune disease (caution)'],
  },
  FluorouracilTopical: {
    name: 'Fluorouracil (Topical)',
    drugClass: 'Antimetabolite (topical)',
    indications: ['Actinic keratosis', 'Superficial basal cell carcinoma'],
    sideEffects: ['Local inflammation', 'Burning', 'Erosion', 'Photosensitivity', 'Hyperpigmentation'],
    contraindications: ['Fluorouracil hypersensitivity', 'Dihydropyrimidine dehydrogenase (DPD) deficiency'],
  },
  Tamsulosin: {
    name: 'Tamsulosin',
    drugClass: 'Alpha-1 Blocker (uroselective)',
    indications: ['Benign prostatic hyperplasia', 'Ureteral stones (expulsion)'],
    sideEffects: ['Dizziness', 'Orthostatic hypotension', 'Retrograde ejaculation (prominent)', 'Floppy iris syndrome (surgery)', 'Nasal congestion'],
    contraindications: ['Tamsulosin hypersensitivity', 'Severe orthostatic hypotension', 'Intercurrent cataract surgery (floppy iris)'],
  },
  Alfuzosin: {
    name: 'Alfuzosin',
    drugClass: 'Alpha-1 Blocker (uroselective)',
    indications: ['Benign prostatic hyperplasia'],
    sideEffects: ['Dizziness', 'Headache', 'Orthostatic hypotension (less)', 'Fatigue', 'Upper respiratory infection'],
    contraindications: ['Alfuzosin hypersensitivity', 'Severe hepatic impairment', 'Concurrent strong CYP3A4 inhibitors', 'Severe orthostatic hypotension'],
  },
  Silodosin: {
    name: 'Silodosin',
    drugClass: 'Alpha-1 Blocker (uroselective)',
    indications: ['Benign prostatic hyperplasia'],
    sideEffects: ['Retrograde ejaculation (prominent)', 'Dizziness', 'Orthostatic hypotension', 'Nasal congestion'],
    contraindications: ['Silodosin hypersensitivity', 'Severe renal/hepatic impairment', 'Concurrent strong CYP3A4 inhibitors'],
  },
  Finasteride: {
    name: 'Finasteride',
    drugClass: '5-Alpha Reductase Inhibitor',
    indications: ['Benign prostatic hyperplasia', 'Male pattern hair loss'],
    sideEffects: ['Decreased libido', 'Erectile dysfunction', 'Decreased ejaculate', 'Gynecomastia', 'PSA reduction (half)'],
    contraindications: ['Finasteride hypersensitivity', 'Pregnancy/handling by pregnant women', 'Urethral stricture (caution)'],
  },
  Dutasteride: {
    name: 'Dutasteride',
    drugClass: '5-Alpha Reductase Inhibitor',
    indications: ['Benign prostatic hyperplasia'],
    sideEffects: ['Decreased libido', 'Erectile dysfunction', 'Gynecomastia', 'Ejaculatory dysfunction', 'PSA reduction'],
    contraindications: ['Dutasteride hypersensitivity', 'Pregnancy (handling)', 'Severe hepatic impairment', 'Urethral stricture (caution)'],
  },
  Oxybutynin: {
    name: 'Oxybutynin',
    drugClass: 'Antimuscarinic (overactive bladder)',
    indications: ['Overactive bladder', 'Detrusor overactivity', 'Neurogenic bladder'],
    sideEffects: ['Dry mouth', 'Constipation', 'Blurred vision', 'Urinary retention', 'Confusion (elderly)', 'Heat intolerance'],
    contraindications: ['Oxybutynin hypersensitivity', 'Urinary/gastric retention', 'Narrow-angle glaucoma', 'Myasthenia gravis', 'Severe ulcerative colitis'],
  },
  Tolterodine: {
    name: 'Tolterodine',
    drugClass: 'Antimuscarinic (overactive bladder)',
    indications: ['Overactive bladder'],
    sideEffects: ['Dry mouth', 'Constipation', 'Blurred vision', 'Headache', 'Urinary retention'],
    contraindications: ['Tolterodine hypersensitivity', 'Urinary/gastric retention', 'Narrow-angle glaucoma', 'Myasthenia gravis', 'Severe hepatic impairment'],
  },
  Solifenacin: {
    name: 'Solifenacin',
    drugClass: 'Antimuscarinic (overactive bladder)',
    indications: ['Overactive bladder'],
    sideEffects: ['Constipation (prominent)', 'Dry mouth', 'Blurred vision', 'QT prolongation', 'Urinary retention'],
    contraindications: ['Solifenacin hypersensitivity', 'Urinary/gastric retention', 'Narrow-angle glaucoma', 'Severe hepatic impairment', 'Prolonged QT'],
  },
  Mirabegron: {
    name: 'Mirabegron',
    drugClass: 'Beta-3 Adrenergic Agonist (overactive bladder)',
    indications: ['Overactive bladder'],
    sideEffects: ['Hypertension', 'Tachycardia', 'Urinary tract infection', 'Headache', 'Constipation'],
    contraindications: ['Mirabegron hypersensitivity', 'Uncontrolled hypertension', 'Severe renal/hepatic impairment'],
  },
  Bethanechol: {
    name: 'Bethanechol',
    drugClass: 'Muscarinic Agonist (cholinergic)',
    indications: ['Urinary retention (non-obstructive)', 'GI hypomotility (off-label)'],
    sideEffects: ['Bradycardia', 'Hypotension', 'Bronchospasm', 'Excessive salivation', 'Abdominal cramps'],
    contraindications: ['Bethanechol hypersensitivity', 'Asthma', 'Peptic ulcer', 'Coronary artery disease', 'Hyperthyroidism', 'Bladder outlet obstruction', 'Epilepsy'],
  },
  Phenazopyridine: {
    name: 'Phenazopyridine',
    drugClass: 'Urinary Analgesic',
    indications: ['Urinary tract pain/discomfort', 'Post-UTI symptom relief'],
    sideEffects: ['Orange-red urine', 'GI upset', 'Headache', 'Methemoglobinemia (G6PD)', 'Renal toxicity (high doses)'],
    contraindications: ['Phenazopyridine hypersensitivity', 'Severe renal impairment', 'G6PD deficiency', 'Pregnancy'],
  },
  Sildenafil: {
    name: 'Sildenafil',
    drugClass: 'PDE5 Inhibitor',
    indications: ['Erectile dysfunction', 'Pulmonary arterial hypertension', 'Raynaud phenomenon (off-label)'],
    sideEffects: ['Headache', 'Flushing', 'Dyspepsia', 'Nasal congestion', 'Priapism (rare)', 'Sudden vision/hearing loss (rare)', 'Blue vision'],
    contraindications: ['Sildenafil hypersensitivity', 'Concurrent nitrates', 'Severe cardiovascular disease', 'Severe hypotension', 'Recent MI/stroke'],
  },
  Tadalafil: {
    name: 'Tadalafil',
    drugClass: 'PDE5 Inhibitor',
    indications: ['Erectile dysfunction', 'Benign prostatic hyperplasia', 'Pulmonary arterial hypertension'],
    sideEffects: ['Headache', 'Myalgia (unique)', 'Flushing', 'Dyspepsia', 'Nasal congestion', 'Priapism (rare)'],
    contraindications: ['Tadalafil hypersensitivity', 'Concurrent nitrates', 'Severe cardiovascular disease', 'Severe renal/hepatic impairment'],
  },
  Vardenafil: {
    name: 'Vardenafil',
    drugClass: 'PDE5 Inhibitor',
    indications: ['Erectile dysfunction'],
    sideEffects: ['Headache', 'Flushing', 'Dyspepsia', 'QT prolongation', 'Nasal congestion'],
    contraindications: ['Vardenafil hypersensitivity', 'Concurrent nitrates', 'Prolonged QT', 'Severe hepatic impairment'],
  },
  Alprostadil: {
    name: 'Alprostadil',
    drugClass: 'Prostaglandin E1',
    indications: ['Erectile dysfunction (injectable)', 'Maintain patent ductus arteriosus (neonates)'],
    sideEffects: ['Penile pain', 'Priapism (prolonged)', 'Local hematoma', 'Fibrosis (chronic)', 'Systemic hypotension (neonate)'],
    contraindications: ['Alprostadil hypersensitivity', 'Penile implant', 'Sickle cell disease', 'Predisposition to priapism', 'Abnormal penile anatomy'],
  },
  Estradiol: {
    name: 'Estradiol',
    drugClass: 'Estrogen (hormone therapy)',
    indications: ['Menopause symptoms', 'Hormone replacement therapy', 'Hypogonadism', 'Contraception (combination)'],
    sideEffects: ['Thromboembolism', 'Nausea', 'Breast tenderness', 'Vaginal bleeding', 'Cholelithiasis', 'Endometrial cancer (unopposed)'],
    contraindications: ['Estradiol hypersensitivity', 'Pregnancy', 'Breast cancer', 'Thromboembolic disease', 'Liver disease', 'Undiagnosed vaginal bleeding'],
  },
  Medroxyprogesterone: {
    name: 'Medroxyprogesterone',
    drugClass: 'Progestin (contraceptive/endocrine)',
    indications: ['Contraception (depot)', 'Endometriosis', 'Amenorrhea', 'Endometrial hyperplasia protection'],
    sideEffects: ['Menstrual irregularities', 'Weight gain', 'Bone density loss (long-term)', 'Mood changes', 'Breast tenderness'],
    contraindications: ['Medroxyprogesterone hypersensitivity', 'Pregnancy', 'Breast cancer', 'Thromboembolic disease', 'Liver disease', 'Undiagnosed vaginal bleeding'],
  },
  Levonorgestrel: {
    name: 'Levonorgestrel',
    drugClass: 'Progestin (emergency contraception/IUD)',
    indications: ['Emergency contraception', 'Intrauterine contraception (IUD)', 'Menorrhagia (IUD)'],
    sideEffects: ['Nausea', 'Menstrual changes', 'Headache', 'Breast tenderness', 'Dizziness'],
    contraindications: ['Levonorgestrel hypersensitivity', 'Pregnancy', 'Active liver disease', 'Breast cancer'],
  },
  Clomiphene: {
    name: 'Clomiphene',
    drugClass: 'SERM (ovulation induction)',
    indications: ['Ovulation induction (PCOS)', 'Female infertility (anovulatory)'],
    sideEffects: ['Hot flashes', 'Ovarian hyperstimulation', 'Multiple pregnancy', 'Visual disturbances (rare)', 'Ovarian cysts'],
    contraindications: ['Clomiphene hypersensitivity', 'Pregnancy', 'Liver disease', 'Ovarian cyst', 'Abnormal uterine bleeding', 'Undiagnosed bleeding'],
  },
  Letrozole: {
    name: 'Letrozole',
    drugClass: 'Aromatase Inhibitor',
    indications: ['Breast cancer (hormone receptor-positive)', 'Ovulation induction (off-label)'],
    sideEffects: ['Hot flashes', 'Arthralgia/myalgia', 'Fatigue', 'Osteoporosis', 'Cholesterol elevation'],
    contraindications: ['Letrozole hypersensitivity', 'Pregnancy', 'Premenopausal (without therapy)', 'Severe hepatic impairment'],
  },
  Anastrozole: {
    name: 'Anastrozole',
    drugClass: 'Aromatase Inhibitor',
    indications: ['Breast cancer (postmenopausal, hormone receptor-positive)'],
    sideEffects: ['Hot flashes', 'Arthralgia', 'Osteoporosis/fractures', 'Fatigue', 'Nausea'],
    contraindications: ['Anastrozole hypersensitivity', 'Pregnancy', 'Premenopausal women'],
  },
  Tamoxifen: {
    name: 'Tamoxifen',
    drugClass: 'SERM (selective estrogen receptor modulator)',
    indications: ['Breast cancer (adjuvant/metastatic)', 'Breast cancer prevention (high-risk)', 'Ductal carcinoma in situ'],
    sideEffects: ['Hot flashes', 'VTE (thromboembolism)', 'Endometrial cancer risk', 'Cataracts', 'Menstrual irregularities', 'Nausea'],
    contraindications: ['Tamoxifen hypersensitivity', 'Pregnancy', 'History of VTE', 'Concurrent warfarin (caution)'],
  },
  Raloxifene: {
    name: 'Raloxifene',
    drugClass: 'SERM (bone-selective)',
    indications: ['Postmenopausal osteoporosis', 'Breast cancer risk reduction'],
    sideEffects: ['Hot flashes', 'VTE (thromboembolism)', 'Leg cramps', 'Flu-like symptoms', 'Peripheral edema'],
    contraindications: ['Raloxifene hypersensitivity', 'Pregnancy', 'History of VTE', 'Severe hepatic impairment'],
  },
  Leuprolide: {
    name: 'Leuprolide',
    drugClass: 'GnRH Agonist',
    indications: ['Prostate cancer', 'Precocious puberty', 'Endometriosis', 'Uterine fibroids', 'Transgender hormone therapy (adjunct)'],
    sideEffects: ['Tumor flare (initial)', 'Hot flashes', 'Gynecomastia (men)', 'Bone density loss', 'Mood changes', 'Injection site reactions'],
    contraindications: ['Leuprolide hypersensitivity', 'Pregnancy', 'Undiagnosed vaginal bleeding'],
  },
  Goserelin: {
    name: 'Goserelin',
    drugClass: 'GnRH Agonist (implant)',
    indications: ['Prostate cancer', 'Endometriosis', 'Uterine fibroids', 'Breast cancer (premenopausal)'],
    sideEffects: ['Hot flashes', 'Tumor flare', 'Bone loss', 'Injection site reactions', 'Mood changes'],
    contraindications: ['Goserelin hypersensitivity', 'Pregnancy'],
  },
  Oxytocin: {
    name: 'Oxytocin',
    drugClass: 'Uterotonic / Oxytocic',
    indications: ['Labor induction/augmentation', 'Postpartum hemorrhage', 'Abortion (adjunct)'],
    sideEffects: ['Uterine hyperstimulation', 'Fetal distress', 'Hyponatremia (water intoxication, prolonged)', 'Hypotension (bolus)', 'Nausea'],
    contraindications: ['Oxytocin hypersensitivity', 'Placenta previa', 'Uterine rupture risk', 'Fetal malpresentation', 'Severe fetal distress', 'Hypertonic uterus'],
  },
  Methylergonovine: {
    name: 'Methylergonovine',
    drugClass: 'Ergot Alkaloid (uterotonic)',
    indications: ['Postpartum hemorrhage', 'Uterine atony'],
    sideEffects: ['Hypertension', 'Nausea/vomiting', 'Headache', 'Coronary vasospasm', 'Cramping'],
    contraindications: ['Methylergonovine hypersensitivity', 'Pregnancy (pre-delivery)', 'Hypertension', 'Preeclampsia/eclampsia', 'Coronary artery disease'],
  },
  Carboprost: {
    name: 'Carboprost Tromethamine',
    drugClass: 'Prostaglandin F2-alpha (uterotonic)',
    indications: ['Postpartum hemorrhage (refractory)', 'Uterine atony'],
    sideEffects: ['Fever', 'Diarrhea', 'Vomiting', 'Bronchospasm', 'Hypertension', 'Flushing'],
    contraindications: ['Carboprost hypersensitivity', 'Severe asthma', 'Pelvic inflammatory disease', 'Active cardiac/pulmonary disease'],
  },
  Mifepristone: {
    name: 'Mifepristone',
    drugClass: 'Antiprogestin',
    indications: ['Medical abortion (with misoprostol)', 'Cushing syndrome (selected)'],
    sideEffects: ['Abdominal cramping', 'Bleeding', 'Nausea', 'Vomiting', 'Infections (rare)'],
    contraindications: ['Mifepristone hypersensitivity', 'Ectopic pregnancy', 'IUD in place', 'Adrenal insufficiency', 'Coagulopathy', 'Chronic corticosteroid use'],
  },
  Desmopressin: {
    name: 'Desmopressin',
    drugClass: 'ADH Analog (vasopressin receptor agonist)',
    indications: ['Central diabetes insipidus', 'Nocturnal enuresis', 'Hemophilia A (mild, adjunct)', 'von Willebrand disease'],
    sideEffects: ['Hyponatremia (water retention)', 'Headache', 'Flushing', 'Nausea', 'Seizures (severe hyponatremia)'],
    contraindications: ['Desmopressin hypersensitivity', 'Hyponatremia', 'Moderate-severe renal impairment', 'Heart failure (caution)'],
  },
  Tolvaptan: {
    name: 'Tolvaptan',
    drugClass: 'Vasopressin V2 Antagonist (vaptan)',
    indications: ['SIADH (euvolemic/hypervolemic hyponatremia)', 'Autosomal dominant polycystic kidney disease'],
    sideEffects: ['Thirst', 'Dry mouth', 'Overly rapid sodium correction', 'Hepatotoxicity (ADPKD dosing)', 'Polyuria'],
    contraindications: ['Tolvaptan hypersensitivity', 'Hypovolemic hyponatremia', 'Inability to sense thirst', 'Severe hepatic impairment', 'Anuria'],
  },
  Calcitonin: {
    name: 'Calcitonin',
    drugClass: 'Antiresorptive (calcium regulator)',
    indications: ['Postmenopausal osteoporosis', 'Hypercalcemia (adjunct)', 'Paget disease (adjunct)'],
    sideEffects: ['Nausea', 'Flushing', 'Injection site reactions', 'Rhinitis/ulceration (nasal)', 'Hypocalcemia'],
    contraindications: ['Calcitonin hypersensitivity', 'Severe hypocalcemia'],
  },
  Alendronate: {
    name: 'Alendronate',
    drugClass: 'Bisphosphonate',
    indications: ['Osteoporosis', 'Paget disease', 'Osteopenia (selected)'],
    sideEffects: ['Esophagitis/esophageal ulcer', 'GI upset', 'Osteonecrosis of jaw (rare)', 'Atypical femur fracture (long-term)', 'Hypocalcemia'],
    contraindications: ['Alendronate hypersensitivity', 'Esophageal abnormalities', 'Inability to sit upright', 'Hypocalcemia', 'Severe renal impairment'],
  },
  Risedronate: {
    name: 'Risedronate',
    drugClass: 'Bisphosphonate',
    indications: ['Osteoporosis', 'Paget disease', 'Glucocorticoid-induced osteoporosis'],
    sideEffects: ['Esophagitis', 'GI upset', 'Osteonecrosis of jaw (rare)', 'Atypical femur fractures (long-term)'],
    contraindications: ['Risedronate hypersensitivity', 'Esophageal abnormalities', 'Hypocalcemia', 'Severe renal impairment', 'Pregnancy'],
  },
  ZoledronicAcid: {
    name: 'Zoledronic Acid',
    drugClass: 'Bisphosphonate (IV)',
    indications: ['Osteoporosis', 'Hypercalcemia of malignancy', 'Multiple myeloma (bone lesions)', 'Paget disease'],
    sideEffects: ['Acute phase reaction (fever, myalgia)', 'Nephrotoxicity', 'Hypocalcemia', 'Osteonecrosis of jaw', 'Atypical fractures'],
    contraindications: ['Zoledronic acid hypersensitivity', 'Severe renal impairment', 'Hypocalcemia', 'Pregnancy'],
  },
  Teriparatide: {
    name: 'Teriparatide',
    drugClass: 'Parathyroid Hormone Analog (anabolic)',
    indications: ['Osteoporosis (high fracture risk)', 'Glucocorticoid-induced osteoporosis'],
    sideEffects: ['Hypercalcemia', 'Leg cramps', 'Dizziness', 'Injection site reactions', 'Osteosarcoma (animal, boxed warning)'],
    contraindications: ['Teriparatide hypersensitivity', 'Hypercalcemia', 'Paget disease', 'Bone metastases', 'Prior radiation to bone', 'Children (open epiphyses)'],
  },
  Denosumab: {
    name: 'Denosumab',
    drugClass: 'RANKL Inhibitor (monoclonal antibody)',
    indications: ['Osteoporosis', 'Bone metastases (solid tumors)', 'Giant cell tumor of bone', 'Glucocorticoid-induced osteoporosis'],
    sideEffects: ['Hypocalcemia', 'Osteonecrosis of jaw', 'Infections (cellulitis)', 'Atypical fractures (rebound on stop)', 'Back pain'],
    contraindications: ['Denosumab hypersensitivity', 'Hypocalcemia', 'Pregnancy'],
  },
  Cinacalcet: {
    name: 'Cinacalcet',
    drugClass: 'Calcimimetic',
    indications: ['Secondary hyperparathyroidism (CKD)', 'Parathyroid carcinoma hypercalcemia', 'Primary hyperparathyroidism (selected)'],
    sideEffects: ['Nausea', 'Hypocalcemia', 'GI upset', 'QT prolongation', 'Hypotension'],
    contraindications: ['Cinacalcet hypersensitivity', 'Hypocalcemia'],
  },
  Epinephrine: {
    name: 'Epinephrine (Adrenaline)',
    drugClass: 'Catecholamine / Sympathomimetic',
    indications: ['Anaphylaxis', 'Cardiac arrest', 'Severe asthma (refractory)', 'Local hemostasis', 'Symptomatic bradycardia'],
    sideEffects: ['Tachycardia', 'Hypertension', 'Arrhythmias', 'Tremor', 'Anxiety', 'Myocardial ischemia'],
    contraindications: ['Narrow-angle glaucoma', 'Use during second stage of labor', 'Concurrent halogenated anesthetics (arrhythmia risk)'],
  },
  Isoproterenol: {
    name: 'Isoproterenol',
    drugClass: 'Beta Agonist (synthetic catecholamine)',
    indications: ['Bradycardia (temporary pacing adjunct)', 'Torsades de pointes (adjunct, historically)', 'Status asthmaticus (historical)'],
    sideEffects: ['Tachycardia', 'Arrhythmias', 'Hypertension/hypotension', 'Headache', 'Tremor', 'Myocardial ischemia'],
    contraindications: ['Isoproterenol hypersensitivity', 'Tachyarrhythmias', 'Angina', 'Coronary insufficiency', 'Hypersensitivity to sympathomimetics'],
  },
  Phenylephrine: {
    name: 'Phenylephrine',
    drugClass: 'Pure Alpha-1 Agonist',
    indications: ['Hypotension', 'Shock (vasopressor)', 'Nasal congestion (topical)', 'Ophthalmic mydriasis'],
    sideEffects: ['Hypertension', 'Reflex bradycardia', 'Headache', 'Rebound congestion (topical)', 'Skin necrosis (extravasation)'],
    contraindications: ['Phenylephrine hypersensitivity', 'Severe hypertension', 'Concurrent MAOIs', 'Narrow-angle glaucoma (ophthalmic)'],
  },
  Atropine: {
    name: 'Atropine',
    drugClass: 'Antimuscarinic (anticholinergic)',
    indications: ['Bradycardia', 'Organophosphate poisoning (antidote)', 'Preanesthesia (reduce secretions)', 'Ophthalmic (cycloplegia)'],
    sideEffects: ['Dry mouth', 'Blurred vision', 'Tachycardia', 'Urinary retention', 'Hyperthermia', 'Delirium (elderly)'],
    contraindications: ['Atropine hypersensitivity', 'Narrow-angle glaucoma', 'Obstructive uropathy', 'Tachyarrhythmias', 'Myasthenia gravis', 'Severe ulcerative colitis'],
  },
  Pralidoxime: {
    name: 'Pralidoxime',
    drugClass: 'Acetylcholinesterase Reactivator (antidote)',
    indications: ['Organophosphate poisoning', 'Nerve agent poisoning'],
    sideEffects: ['Dizziness', 'Blurred vision', 'Muscle weakness', 'Hypertension', 'Laryngospasm (rapid IV)'],
    contraindications: ['Pralidoxime hypersensitivity', 'Concurrent physostigmine'],
  },
  Protamine: {
    name: 'Protamine Sulfate',
    drugClass: 'Heparin Antagonist (antidote)',
    indications: ['Heparin overdose/bleeding', 'Reversal after cardiac surgery'],
    sideEffects: ['Hypotension', 'Bradycardia', 'Anaphylactoid reactions (fish allergy)', 'Pulmonary hypertension', 'Rebound anticoagulation'],
    contraindications: ['Protamine hypersensitivity (fish allergy)'],
  },
  Phytonadione: {
    name: 'Phytonadione (Vitamin K1)',
    drugClass: 'Vitamin / Anticoagulant Reversal',
    indications: ['Warfarin reversal', 'Vitamin K deficiency', 'Hemorrhagic disease of newborn'],
    sideEffects: ['Anaphylactoid reactions (IV)', 'Flushing', 'Injection site reactions', 'Hemolysis (G6PD, high dose)'],
    contraindications: ['Phytonadione hypersensitivity', 'Severe hepatic disease (ineffective)'],
  },
  Fomepizole: {
    name: 'Fomepizole',
    drugClass: 'Alcohol Dehydrogenase Inhibitor (antidote)',
    indications: ['Methanol poisoning', 'Ethylene glycol poisoning'],
    sideEffects: ['Headache', 'Nausea', 'Dizziness', 'Bradycardia', 'Metallic taste'],
    contraindications: ['Fomepizole hypersensitivity'],
  },
  Deferoxamine: {
    name: 'Deferoxamine',
    drugClass: 'Iron Chelator (antidote)',
    indications: ['Acute iron toxicity', 'Chronic iron overload (transfusion)'],
    sideEffects: ['Hypotension', 'Flushing', 'Pain at infusion site', 'Yersinia infection risk', 'Ocular/ototoxicity (chronic)'],
    contraindications: ['Deferoxamine hypersensitivity', 'Severe renal disease', 'Anuria'],
  },
  Defersirox: {
    name: 'Deferasirox',
    drugClass: 'Oral Iron Chelator',
    indications: ['Chronic iron overload (thalassemia, transfusions)'],
    sideEffects: ['Renal impairment', 'Hepatotoxicity', 'GI upset', 'Rash', 'Cytopenias'],
    contraindications: ['Deferasirox hypersensitivity', 'Severe renal impairment', 'Severe hepatic impairment', 'High-risk myelodysplastic syndrome'],
  },
  Dimercaprol: {
    name: 'Dimercaprol (BAL)',
    drugClass: 'Heavy Metal Chelator (antidote)',
    indications: ['Arsenic poisoning', 'Mercury poisoning', 'Lead poisoning (with EDTA)', 'Gold toxicity'],
    sideEffects: ['Hypertension', 'Tachycardia', 'Nausea/vomiting', 'Pain at injection site', 'Metallic taste', 'G6PD hemolysis'],
    contraindications: ['Dimercaprol hypersensitivity', 'Iron poisoning (dimercaprol-iron complex toxic)', 'Severe hepatic disease', 'G6PD deficiency'],
  },
  EDTA: {
    name: 'Calcium Disodium EDTA',
    drugClass: 'Heavy Metal Chelator (antidote)',
    indications: ['Lead poisoning', 'Manganese poisoning (off-label)'],
    sideEffects: ['Nephrotoxicity', 'Hypocalcemia (tetany)', 'GI upset', 'Injection site reactions', 'Renal tubular damage'],
    contraindications: ['EDTA hypersensitivity', 'Anuria', 'Severe renal disease', 'Severe hypocalcemia'],
  },
  MethyleneBlue: {
    name: 'Methylene Blue',
    drugClass: 'Antidote (reducing agent)',
    indications: ['Methemoglobinemia', 'Ifosfamide encephalopathy (adjunct)'],
    sideEffects: ['Blue-green urine/stool', 'Serotonin syndrome (with SSRIs)', 'Hypertension', 'Nausea', 'Skin staining'],
    contraindications: ['Methylene blue hypersensitivity', 'G6PD deficiency (hemolysis)', 'Serotonin syndrome risk (MAOI combination)'],
  },
  Hydroxocobalamin: {
    name: 'Hydroxocobalamin',
    drugClass: 'Cyanide Antidote',
    indications: ['Cyanide poisoning', 'Smoke inhalation (cyanide)'],
    sideEffects: ['Red discoloration of skin/urine', 'Hypertension', 'Injection site reactions', 'Interference with lab tests', 'Allergic reactions (rare)'],
    contraindications: ['Hydroxocobalamin hypersensitivity'],
  },
  Dantrolene: {
    name: 'Dantrolene',
    drugClass: 'Muscle Relaxant (ryanodine receptor antagonist)',
    indications: ['Malignant hyperthermia', 'Neuroleptic malignant syndrome (adjunct)', 'Spasticity'],
    sideEffects: ['Hepatotoxicity', 'Muscle weakness', 'Drowsiness', 'Nausea/diarrhea', 'Pleuritis/pericarditis'],
    contraindications: ['Dantrolene hypersensitivity', 'Active liver disease', 'Skeletal muscle weakness states'],
  },
  CalciumGluconate: {
    name: 'Calcium Gluconate',
    drugClass: 'Mineral Replacement / Antidote',
    indications: ['Hypocalcemia', 'Hyperkalemia (cardiac protection)', 'Hyperphosphatemia (adjunct)', 'Calcium channel blocker overdose', 'Magnesium toxicity'],
    sideEffects: ['Hypercalcemia', 'Bradycardia (rapid IV)', 'Tissue necrosis (extravasation)', 'GI upset (oral)'],
    contraindications: ['Calcium gluconate hypersensitivity', 'Hypercalcemia', 'Ventricular fibrillation', 'Digitalis toxicity (IV)'],
  },
  SodiumBicarbonate: {
    name: 'Sodium Bicarbonate',
    drugClass: 'Alkalinizing Agent / Antidote',
    indications: ['Metabolic acidosis (severe)', 'Tricyclic antidepressant overdose', 'Salicylate poisoning (adjunct)', 'Sodium bicarbonate urine alkalinization', 'Hyperkalemia (adjunct)'],
    sideEffects: ['Metabolic alkalosis', 'Hypernatremia', 'Fluid overload', 'Hypokalemia', 'Tissue necrosis (extravasation)'],
    contraindications: ['Sodium bicarbonate hypersensitivity', 'Metabolic alkalosis', 'Hypocalcemia', 'Hypokalemia', 'Hypernatremia'],
  },
  ActivatedCharcoal: {
    name: 'Activated Charcoal',
    drugClass: 'GI Decontaminant (antidote)',
    indications: ['Toxic ingestions', 'Drug overdose decontamination'],
    sideEffects: ['Vomiting', 'Constipation', 'Black stools', 'Aspiration (caution)', 'GI obstruction (rare)'],
    contraindications: ['Activated charcoal hypersensitivity', 'Bowel obstruction', 'Perforation', 'GI bleeding', 'Ingestion of corrosive/iron/lithium/alcohol', 'Aspiration risk'],
  },
  FerrousSulfate: {
    name: 'Ferrous Sulfate',
    drugClass: 'Iron Supplement',
    indications: ['Iron deficiency anemia', 'Iron deficiency prophylaxis'],
    sideEffects: ['Constipation', 'Nausea', 'Dark stools', 'GI upset', 'Abdominal pain'],
    contraindications: ['Iron hypersensitivity', 'Iron overload (hemochromatosis)', 'Hemolytic anemia (unless deficiency)', 'Pernicious anemia (ineffective)'],
  },
  FolicAcid: {
    name: 'Folic Acid',
    drugClass: 'Vitamin (B9) Supplement',
    indications: ['Megaloblastic anemia (folate deficiency)', 'Pregnancy (neural tube defect prevention)', 'Methotrexate adjunct'],
    sideEffects: ['Bitter taste', 'Nausea', 'Masking of B12 deficiency', 'Insomnia (rare)'],
    contraindications: ['Folic acid hypersensitivity'],
  },
  Cyanocobalamin: {
    name: 'Cyanocobalamin (Vitamin B12)',
    drugClass: 'Vitamin B12 Supplement',
    indications: ['Vitamin B12 deficiency', 'Pernicious anemia', 'Megaloblastic anemia'],
    sideEffects: ['Injection site pain', 'Hypokalemia (initial treatment)', 'Acne', 'Allergic reactions (rare)'],
    contraindications: ['Cyanocobalamin hypersensitivity', 'Cobalt allergy', 'Leber optic atrophy'],
  },
  Thiamine: {
    name: 'Thiamine (Vitamin B1)',
    drugClass: 'Vitamin Supplement',
    indications: ['Beriberi', 'Wernicke encephalopathy', 'Thiamine deficiency (alcoholism)', 'Heart failure (adjunct, deficiency)'],
    sideEffects: ['Injection site reactions', 'Anaphylaxis (rare, IV)', 'Nausea'],
    contraindications: ['Thiamine hypersensitivity'],
  },
  Pyridoxine: {
    name: 'Pyridoxine (Vitamin B6)',
    drugClass: 'Vitamin Supplement',
    indications: ['Isoniazid-induced neuropathy', 'Pyridoxine deficiency', 'Nausea in pregnancy (mild)', 'Sideroblastic anemia (adjunct)'],
    sideEffects: ['Peripheral neuropathy (high dose)', 'Nausea', 'Lactic acidosis (overdose)'],
    contraindications: ['Pyridoxine hypersensitivity'],
  },
  NiacinVit: {
    name: 'Niacin (Vitamin B3)',
    drugClass: 'Vitamin Supplement',
    indications: ['Pellagra (niacin deficiency)', 'Dyslipidemia'],
    sideEffects: ['Flushing', 'Pruritus', 'Hepatotoxicity (high dose)', 'Hyperglycemia', 'Hyperuricemia'],
    contraindications: ['Niacin hypersensitivity', 'Active liver disease', 'GI bleeding (caution)'],
  },
  Cholecalciferol: {
    name: 'Cholecalciferol (Vitamin D3)',
    drugClass: 'Vitamin D Supplement',
    indications: ['Vitamin D deficiency', 'Osteoporosis (adjunct)', 'Rickets', 'Hypocalcemia (adjunct)'],
    sideEffects: ['Hypercalcemia (high doses)', 'Hypercalciuria', 'Nephrolithiasis (excess)', 'Nausea', 'Constipation'],
    contraindications: ['Cholecalciferol hypersensitivity', 'Hypercalcemia', 'Hypercalciuria', 'Vitamin D toxicity', 'Malabsorption syndromes (oral)'],
  },
  Calcitriol: {
    name: 'Calcitriol (Active Vitamin D)',
    drugClass: 'Vitamin D Analog (calcium regulator)',
    indications: ['Hypocalcemia in CKD', 'Secondary hyperparathyroidism', 'Hypoparathyroidism', 'Vitamin D-resistant rickets'],
    sideEffects: ['Hypercalcemia', 'Hypercalciuria', 'Nephrolithiasis', 'Soft tissue calcification', 'Nausea'],
    contraindications: ['Calcitriol hypersensitivity', 'Hypercalcemia', 'Hypercalciuria', 'Vitamin D toxicity'],
  },
  MagnesiumSulfate: {
    name: 'Magnesium Sulfate',
    drugClass: 'Electrolyte / Anticonvulsant / Tocolytic',
    indications: ['Preeclampsia/eclampsia (seizure prophylaxis)', 'Hypomagnesemia', 'Torsades de pointes', 'Severe asthma (adjunct)', 'Preterm labor (tocolytic)'],
    sideEffects: ['Hypotension', 'Flushing', 'Hyporeflexia', 'Respiratory depression (high levels)', 'Hypocalcemia', 'Muscle weakness'],
    contraindications: ['Magnesium sulfate hypersensitivity', 'Heart block', 'Myocardial damage', 'Hypermagnesemia', 'Renal failure (dose adjust)'],
  },
  PotassiumChloride: {
    name: 'Potassium Chloride',
    drugClass: 'Electrolyte Supplement',
    indications: ['Hypokalemia', 'Potassium depletion (diuretics)', 'Metabolic alkalosis (with K loss)'],
    sideEffects: ['Hyperkalemia', 'GI irritation (oral)', 'Cardiac arrhythmias (rapid IV)', 'Tissue necrosis (extravasation)'],
    contraindications: ['Potassium chloride hypersensitivity', 'Hyperkalemia', 'Severe renal impairment (with oliguria)', 'Concurrent potassium-sparing diuretics'],
  },
  SodiumChloride: {
    name: 'Sodium Chloride',
    drugClass: 'Electrolyte Supplement / Fluid',
    indications: ['Hyponatremia', 'Volume depletion', 'Intravenous fluid maintenance', 'Cerebral edema (hypertonic)'],
    sideEffects: ['Hypernatremia', 'Fluid overload', 'Pulmonary edema', 'Metabolic acidosis (excess chloride)'],
    contraindications: ['Sodium chloride hypersensitivity', 'Hypernatremia', 'Fluid overload', 'Severe renal impairment with edema (caution)'],
  },
};