import type { DrugInfo } from '../medicalTypes';

export const DRUGS_PART4: Record<string, DrugInfo> = {
  Efavirenz: {
    name: 'Efavirenz',
    drugClass: 'Non-Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART)'],
    sideEffects: ['CNS effects (vivid dreams, dizziness)', 'Rash', 'Hepatotoxicity', 'Teratogenicity', 'Lipodystrophy'],
    contraindications: ['Efavirenz hypersensitivity', 'Pregnancy'],
  },
  Nevirapine: {
    name: 'Nevirapine',
    drugClass: 'Non-Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART)', 'Prevention of maternal-fetal transmission'],
    sideEffects: ['Severe rash (Stevens-Johnson)', 'Hepatotoxicity', 'Fever', 'Nausea', 'Elevated transaminases'],
    contraindications: ['Nevirapine hypersensitivity', 'Severe hepatic impairment'],
  },
  Rilpivirine: {
    name: 'Rilpivirine',
    drugClass: 'Non-Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART, viral load <100k)'],
    sideEffects: ['Depression', 'Insomnia', 'Headache', 'Rash', 'QT prolongation (high doses)'],
    contraindications: ['Rilpivirine hypersensitivity', 'Concurrent strong CYP3A4 inducers', 'Requires acid (PPI contraindication)'],
  },
  Atazanavir: {
    name: 'Atazanavir',
    drugClass: 'Protease Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART)'],
    sideEffects: ['Indirect hyperbilirubinemia (jaundice)', 'Nephrolithiasis', 'GI upset', 'Prolonged PR interval', 'Lipodystrophy'],
    contraindications: ['Atazanavir hypersensitivity', 'Concurrent CPP3A4 substrates with risk (midazolam, ergot)', 'Severe hepatic impairment'],
  },
  Darunavir: {
    name: 'Darunavir',
    drugClass: 'Protease Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART)'],
    sideEffects: ['GI upset', 'Hepatotoxicity', 'Rash', 'Elevated lipids', 'Insulin resistance', 'Sulfonamide cross-reaction'],
    contraindications: ['Darunavir hypersensitivity', 'Severe hepatic impairment', 'Concurrent CYP3A4-metabolized drugs (careful)'],
  },
  LopinavirRitonavir: {
    name: 'Lopinavir-Ritonavir',
    drugClass: 'Protease Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART)'],
    sideEffects: ['GI intolerance (diarrhea, nausea)', 'Hyperlipidemia', 'Insulin resistance', 'QT/PR prolongation', 'Hepatotoxicity'],
    contraindications: ['Lopinavir hypersensitivity', 'Severe hepatic impairment', 'Concurrent QT-prolonging drugs'],
  },
  Tenofovir: {
    name: 'Tenofovir Disoproxil Fumarate',
    drugClass: 'Nucleotide Reverse Transcriptase Inhibitor (HIV/HBV)',
    indications: ['HIV-1 infection', 'Chronic hepatitis B', 'HIV/HBV coinfection'],
    sideEffects: ['Nephrotoxicity (Fanconi syndrome)', 'Osteopenia/osteoporosis', 'Lactic acidosis', 'Renal impairment'],
    contraindications: ['Tenofovir hypersensitivity', 'Severe renal impairment', 'Concurrent nephrotoxic drugs'],
  },
  TenofovirAF: {
    name: 'Tenofovir Alafenamide',
    drugClass: 'Nucleotide Reverse Transcriptase Inhibitor (HIV/HBV)',
    indications: ['HIV-1 infection', 'Chronic hepatitis B'],
    sideEffects: ['Nausea', 'Headache', 'Weight gain', 'Less renal/bone toxicity than TDF'],
    contraindications: ['Tenofovir hypersensitivity', 'Concurrent strong P-glycoprotein inducers'],
  },
  Emtricitabine: {
    name: 'Emtricitabine',
    drugClass: 'Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection', 'HIV pre-exposure prophylaxis (PrEP)'],
    sideEffects: ['Headache', 'Nausea', 'Skin discoloration (hyperpigmentation)', 'Hepatotoxicity'],
    contraindications: ['Emtricitabine hypersensitivity'],
  },
  Lamivudine: {
    name: 'Lamivudine',
    drugClass: 'Nucleoside Reverse Transcriptase Inhibitor (HIV/HBV)',
    indications: ['HIV-1 infection', 'Chronic hepatitis B'],
    sideEffects: ['Headache', 'Nausea', 'Pancreatitis (children)', 'Lactic acidosis', 'Hepatic steatosis'],
    contraindications: ['Lamivudine hypersensitivity'],
  },
  Abacavir: {
    name: 'Abacavir',
    drugClass: 'Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection (combination ART)'],
    sideEffects: ['Hypersensitivity reaction (HLA-B*5701)', 'Fever', 'Rash', 'GI upset', 'MI risk (caution)'],
    contraindications: ['Abacavir hypersensitivity', 'HLA-B*5701 positive', 'Severe hepatic impairment'],
  },
  Zidovudine: {
    name: 'Zidovudine (AZT)',
    drugClass: 'Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection', 'Prevention of maternal-fetal transmission'],
    sideEffects: ['Anemia', 'Neutropenia', 'Myopathy', 'Lactic acidosis', 'GI upset', 'Headache'],
    contraindications: ['Zidovudine hypersensitivity', 'Severe anemia/neutropenia'],
  },
  Stavudine: {
    name: 'Stavudine',
    drugClass: 'Nucleoside Reverse Transcriptase Inhibitor (HIV)',
    indications: ['HIV-1 infection (historically)'],
    sideEffects: ['Peripheral neuropathy', 'Pancreatitis', 'Lipoatrophy', 'Lactic acidosis', 'Hepatic steatosis'],
    contraindications: ['Stavudine hypersensitivity', 'Pregnancy', 'Peripheral neuropathy'],
  },
  Entecavir: {
    name: 'Entecavir',
    drugClass: 'Antiviral (HBV nucleoside analog)',
    indications: ['Chronic hepatitis B'],
    sideEffects: ['Headache', 'Fatigue', 'Dizziness', 'Lactic acidosis', 'Hepatitis flare on discontinuation'],
    contraindications: ['Entecavir hypersensitivity'],
  },
  Adefovir: {
    name: 'Adefovir Dipivoxil',
    drugClass: 'Antiviral (HBV nucleotide analog)',
    indications: ['Chronic hepatitis B'],
    sideEffects: ['Nephrotoxicity', 'Osteomalacia', 'Lactic acidosis', 'Hepatitis flare'],
    contraindications: ['Adefovir hypersensitivity', 'Severe renal impairment'],
  },
  Chloroquine: {
    name: 'Chloroquine',
    drugClass: 'Antimalarial (4-aminoquinoline)',
    indications: ['Malaria (sensitive strains, treatment/prophylaxis)', 'Amebiasis', 'Rheumatoid arthritis (historically)'],
    sideEffects: ['Retinopathy (chronic)', 'GI upset', 'Pruritus', 'Headache', 'QT prolongation', 'Hemolysis (G6PD)'],
    contraindications: ['Chloroquine hypersensitivity', 'Retinal disease', 'G6PD deficiency', 'Porphyria'],
  },
  Hydroxychloroquine: {
    name: 'Hydroxychloroquine',
    drugClass: 'Antimalarial / DMARD',
    indications: ['Malaria prophylaxis', 'SLE', 'Rheumatoid arthritis', 'Lupus nephritis (adjunct)'],
    sideEffects: ['Retinal toxicity (chronic use)', 'GI upset', 'Headache', 'QT prolongation', 'Skin hyperpigmentation'],
    contraindications: ['Hydroxychloroquine hypersensitivity', 'Pre-existing retinopathy', 'G6PD deficiency'],
  },
  Quinine: {
    name: 'Quinine',
    drugClass: 'Antimalarial',
    indications: ['Severe/complicated malaria (IV, with adjuvant)', 'Babesiosis', 'Leg cramps (withdrawn)'],
    sideEffects: ['Cinchonism (tinnitus, headache)', 'QT prolongation', 'Hypoglycemia', 'Hemolysis (G6PD)', 'Thrombocytopenia'],
    contraindications: ['Quinine hypersensitivity', 'G6PD deficiency', 'Prolonged QT', 'Concurrent QT-prolonging drugs'],
  },
  ArtemetherLumefantrine: {
    name: 'Artemether-Lumefantrine',
    drugClass: 'Artemisinin Combination Therapy (ACT)',
    indications: ['Uncomplicated falciparum malaria'],
    sideEffects: ['Headache', 'Nausea', 'QT prolongation (lumefantrine)', 'Dizziness', 'Vomiting'],
    contraindications: ['Artemether hypersensitivity', 'Concurrent strong CYP3A4 inducers'],
  },
  Artesunate: {
    name: 'Artesunate',
    drugClass: 'Artemisinin Antimalarial',
    indications: ['Severe malaria (IV)', 'Uncomplicated malaria (combination)'],
    sideEffects: ['Hemolysis (post-treatment)', 'Delayed anemia', 'Nausea', 'QT prolongation (rare)'],
    contraindications: ['Artesunate hypersensitivity', 'First trimester pregnancy (relative)'],
  },
  Mefloquine: {
    name: 'Mefloquine',
    drugClass: 'Antimalarial (quinoline-methanol)',
    indications: ['Malaria prophylaxis', 'Malaria treatment (selected)'],
    sideEffects: ['Neuropsychiatric effects (anxiety, insomnia, psychosis)', 'Dizziness', 'GI upset', 'QT prolongation'],
    contraindications: ['Mefloquine hypersensitivity', 'History of seizures/psychiatric disease', 'Prolonged QT', 'Cardiac conduction abnormalities'],
  },
  Primaquine: {
    name: 'Primaquine',
    drugClass: 'Antimalarial (8-aminoquinoline)',
    indications: ['Malaria (relapse prevention - hypnozoites)', 'P. vivax/P. ovale radical cure'],
    sideEffects: ['Hemolysis (G6PD)', 'Methemoglobinemia', 'GI upset', 'Granulocytopenia'],
    contraindications: ['G6PD deficiency', 'Pregnancy', 'Concurrent quinacrine'],
  },
  Tafenoquine: {
    name: 'Tafenoquine',
    drugClass: 'Antimalarial (8-aminoquinoline)',
    indications: ['Malaria prophylaxis', 'P. vivax radical cure'],
    sideEffects: ['Hemolysis (G6PD)', 'Methemoglobinemia', 'Dizziness', 'GI upset'],
    contraindications: ['G6PD deficiency', 'Pregnancy', 'Breastfeeding'],
  },
  AtovaquoneProguanil: {
    name: 'Atovaquone-Proguanil',
    drugClass: 'Antimalarial combination',
    indications: ['Malaria prophylaxis', 'Uncomplicated malaria treatment', 'PCP treatment (atovaquone)'],
    sideEffects: ['GI upset', 'Headache', 'Rash', 'Vomiting', 'Elevated liver enzymes'],
    contraindications: ['Atovaquone hypersensitivity', 'Severe renal impairment (proguanil)'],
  },
  Pyrimethamine: {
    name: 'Pyrimethamine',
    drugClass: 'Antiprotozoal (folate antagonist)',
    indications: ['Toxoplasmosis (combination)', 'Malaria (combination)', 'PCP (combination)'],
    sideEffects: ['Megaloblastic anemia (folate deficiency)', 'Pan Cytopenia', 'GI upset', 'Rash'],
    contraindications: ['Pyrimethamine hypersensitivity', 'Megaloblastic anemia', 'Pregnancy (relative)'],
  },
  Ivermectin: {
    name: 'Ivermectin',
    drugClass: 'Anthelminthic (macrocyclic lactone)',
    indications: ['Strongyloidiasis', 'Onchocerciasis', 'Scabies', 'Filariasis', 'Lice'],
    sideEffects: ['Dizziness', 'Pruritus', 'Fever', 'Mazzotti reaction (with filariasis)', 'GI upset'],
    contraindications: ['Ivermectin hypersensitivity', 'Pregnancy'],
  },
  Albendazole: {
    name: 'Albendazole',
    drugClass: 'Anthelminthic (benzimidazole)',
    indications: ['Neurocysticercosis', 'Hydatid disease', 'Pinworm', 'Hookworm', 'Ascariasis'],
    sideEffects: ['Hepatotoxicity', 'Headache', 'Nausea', 'Hair loss (with prolonged use)', 'Bone marrow suppression'],
    contraindications: ['Albendazole hypersensitivity', 'Pregnancy', 'Cirrhosis'],
  },
  Mebendazole: {
    name: 'Mebendazole',
    drugClass: 'Anthelminthic (benzimidazole)',
    indications: ['Pinworm', 'Roundworm', 'Hookworm', 'Whipworm'],
    sideEffects: ['Abdominal pain', 'Diarrhea', 'Headache', 'Hepatotoxicity (rare)'],
    contraindications: ['Mebendazole hypersensitivity', 'Pregnancy'],
  },
  Praziquantel: {
    name: 'Praziquantel',
    drugClass: 'Anthelminthic (anti-fluke)',
    indications: ['Schistosomiasis', 'Tapeworm infections', 'Liver flukes', 'Neurocysticercosis (adjunct)'],
    sideEffects: ['Dizziness', 'Headache', 'Abdominal discomfort', 'Nausea', 'Raised ICP (cysticercosis)'],
    contraindications: ['Praziquantel hypersensitivity', 'Ocular cysticercosis'],
  },
  Pyrantel: {
    name: 'Pyrantel Pamoate',
    drugClass: 'Anthelminthic (nicotinic agonist)',
    indications: ['Pinworm', 'Roundworm', 'Hookworm'],
    sideEffects: ['GI upset', 'Headache', 'Dizziness', 'Rash'],
    contraindications: ['Pyrantel hypersensitivity', 'Concurrent piperazine'],
  },
  Nitazoxanide: {
    name: 'Nitazoxanide',
    drugClass: 'Antiprotozoal / Anti-infective',
    indications: ['Cryptosporidiosis', 'Giardiasis', 'Amebiasis', 'Helminth infections'],
    sideEffects: ['Abdominal pain', 'Nausea', 'Headache', 'Discolored urine'],
    contraindications: ['Nitazoxanide hypersensitivity'],
  },
  Paromomycin: {
    name: 'Paromomycin',
    drugClass: 'Aminoglycoside Antiprotozoal',
    indications: ['Intestinal amebiasis', 'Giardiasis', 'Cryptosporidiosis'],
    sideEffects: ['GI upset', 'Nephrotoxicity (systemic)', 'Ototoxicity', 'Local irritation'],
    contraindications: ['Paromomycin hypersensitivity', 'Intestinal obstruction'],
  },
  Pentamidine: {
    name: 'Pentamidine',
    drugClass: 'Antiprotozoal',
    indications: ['Pneumocystis jirovecii pneumonia (inhalation/IV)', 'Trypanosomiasis', 'Leishmaniasis'],
    sideEffects: ['Hypotension', 'Nephrotoxicity', 'QT prolongation', 'Hypoglycemia/hyperglycemia', 'Pancreatitis'],
    contraindications: ['Pentamidine hypersensitivity', 'Prolonged QT', 'Severe renal impairment'],
  },
  Miltefosine: {
    name: 'Miltefosine',
    drugClass: 'Antiprotozoal',
    indications: ['Leishmaniasis (visceral, cutaneous)', 'Free-living ameba (naegleria, adjunct)'],
    sideEffects: ['GI upset (nausea, vomiting)', 'Nephrotoxicity', 'Hepatotoxicity', 'Teratogenicity', 'Stevens-Johnson'],
    contraindications: ['Miltefosine hypersensitivity', 'Pregnancy', 'Sjogren syndrome'],
  },
  Suramin: {
    name: 'Suramin',
    drugClass: 'Antiprotozoal',
    indications: ['African trypanosomiasis (first stage)', 'Onchocerciasis (historical)'],
    sideEffects: ['Nausea/vomiting', 'Nephrotoxicity', 'Peripheral neuropathy', 'Rash', 'Anaphylaxis (rare)'],
    contraindications: ['Suramin hypersensitivity', 'Severe renal impairment'],
  },
  Nifurtimox: {
    name: 'Nifurtimox',
    drugClass: 'Antiprotozoal',
    indications: ['Chagas disease (Trypanosoma cruzi)', 'African trypanosomiasis (combination)'],
    sideEffects: ['GI upset', 'Anorexia', 'Peripheral neuropathy', 'Psychiatric effects', 'Rash'],
    contraindications: ['Nifurtimox hypersensitivity', 'Pregnancy'],
  },
  Benznidazole: {
    name: 'Benznidazole',
    drugClass: 'Antiprotozoal',
    indications: ['Chagas disease (Trypanosoma cruzi)'],
    sideEffects: ['Skin rash', 'Peripheral neuropathy', 'Bone marrow suppression', 'GI upset', 'Fever'],
    contraindications: ['Benznidazole hypersensitivity', 'Severe renal/hepatic impairment', 'Pregnancy'],
  },
  SodiumStibogluconate: {
    name: 'Sodium Stibogluconate',
    drugClass: 'Antiprotozoal (pentavalent antimonial)',
    indications: ['Visceral/cutaneous leishmaniasis'],
    sideEffects: ['Pancreatitis', 'Cardiotoxicity (QT prolongation)', 'Nephrotoxicity', 'Myalgia', 'Hepatotoxicity'],
    contraindications: ['Sodium stibogluconate hypersensitivity', 'Severe cardiac/hepatic/renal disease'],
  },
  Lisinopril: {
    name: 'Lisinopril',
    drugClass: 'ACE Inhibitor',
    indications: ['Hypertension', 'Heart failure', 'Post-MI', 'Diabetic nephropathy', 'Proteinuria reduction'],
    sideEffects: ['Dry cough', 'Hyperkalemia', 'Angioedema', 'Hypotension', 'Dizziness', 'Renal impairment'],
    contraindications: ['History of angioedema', 'Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia', 'Concurrent aliskiren use'],
  },
  Enalapril: {
    name: 'Enalapril',
    drugClass: 'ACE Inhibitor',
    indications: ['Hypertension', 'Heart failure', 'Post-MI', 'Diabetic nephropathy'],
    sideEffects: ['Dry cough', 'Hyperkalemia', 'Angioedema', 'Hypotension', 'Dizziness'],
    contraindications: ['History of angioedema', 'Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia'],
  },
  Ramipril: {
    name: 'Ramipril',
    drugClass: 'ACE Inhibitor',
    indications: ['Hypertension', 'Heart failure', 'Post-MI', 'Cardiovascular risk reduction', 'Diabetic nephropathy'],
    sideEffects: ['Dry cough', 'Hyperkalemia', 'Angioedema', 'Hypotension', 'Dizziness'],
    contraindications: ['History of angioedema', 'Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia'],
  },
  Captopril: {
    name: 'Captopril',
    drugClass: 'ACE Inhibitor',
    indications: ['Hypertension', 'Heart failure', 'Post-MI', 'Diabetic nephropathy'],
    sideEffects: ['Dry cough', 'Hyperkalemia', 'Angioedema', 'Dysgeusia (taste disturbance)', 'Rash', 'Neutropenia (rare)'],
    contraindications: ['History of angioedema', 'Pregnancy', 'Bilateral renal artery stenosis'],
  },
  Perindopril: {
    name: 'Perindopril',
    drugClass: 'ACE Inhibitor',
    indications: ['Hypertension', 'Heart failure', 'Cardiovascular risk reduction'],
    sideEffects: ['Dry cough', 'Hyperkalemia', 'Angioedema', 'Dizziness', 'Headache'],
    contraindications: ['History of angioedema', 'Pregnancy', 'Bilateral renal artery stenosis'],
  },
  Losartan: {
    name: 'Losartan',
    drugClass: 'Angiotensin II Receptor Blocker (ARB)',
    indications: ['Hypertension', 'Diabetic nephropathy', 'Heart failure', 'Post-stroke prevention'],
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Renal impairment', 'Less cough than ACEi', 'Angioedema (rare)'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia', 'Concurrent aliskiren (diabetics)'],
  },
  Valsartan: {
    name: 'Valsartan',
    drugClass: 'Angiotensin II Receptor Blocker (ARB)',
    indications: ['Hypertension', 'Heart failure', 'Post-MI'],
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Renal impairment', 'Headache'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia'],
  },
  Candesartan: {
    name: 'Candesartan',
    drugClass: 'Angiotensin II Receptor Blocker (ARB)',
    indications: ['Hypertension', 'Heart failure'],
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Renal impairment', 'Headache'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia'],
  },
  Irbesartan: {
    name: 'Irbesartan',
    drugClass: 'Angiotensin II Receptor Blocker (ARB)',
    indications: ['Hypertension', 'Diabetic nephropathy'],
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Renal impairment', 'GI upset'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia'],
  },
  Olmesartan: {
    name: 'Olmesartan',
    drugClass: 'Angiotensin II Receptor Blocker (ARB)',
    indications: ['Hypertension'],
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Sprue-like enteropathy (chronic)', 'Renal impairment'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis'],
  },
  Telmisartan: {
    name: 'Telmisartan',
    drugClass: 'Angiotensin II Receptor Blocker (ARB)',
    indications: ['Hypertension', 'Cardiovascular risk reduction'],
    sideEffects: ['Dizziness', 'Hyperkalemia', 'Diarrhea', 'Renal impairment'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Biliary obstruction'],
  },
  Amlodipine: {
    name: 'Amlodipine',
    drugClass: 'Calcium Channel Blocker',
    indications: ['Hypertension', 'Angina pectoris', 'Coronary artery disease', 'Vasospastic angina'],
    sideEffects: ['Peripheral edema', 'Flushing', 'Headache', 'Dizziness', 'Fatigue', 'Palpitations'],
    contraindications: ['Severe hypotension', 'Cardiogenic shock', 'Severe aortic stenosis', 'Hepatic impairment'],
  },
  Nifedipine: {
    name: 'Nifedipine',
    drugClass: 'Calcium Channel Blocker (dihydropyridine)',
    indications: ['Hypertension', 'Angina', 'Raynaud phenomenon', 'Preterm labor (tocolytic)'],
    sideEffects: ['Peripheral edema', 'Flushing', 'Headache', 'Reflex tachycardia', 'Dizziness'],
    contraindications: ['Cardiogenic shock', 'Severe aortic stenosis', 'Concurrent rifampin'],
  },
  Felodipine: {
    name: 'Felodipine',
    drugClass: 'Calcium Channel Blocker (dihydropyridine)',
    indications: ['Hypertension', 'Angina'],
    sideEffects: ['Peripheral edema', 'Flushing', 'Headache', 'Dizziness'],
    contraindications: ['Cardiogenic shock', 'Severe aortic stenosis'],
  },
  Diltiazem: {
    name: 'Diltiazem',
    drugClass: 'Non-dihydropyridine Calcium Channel Blocker',
    indications: ['Atrial fibrillation (rate control)', 'Angina', 'Hypertension'],
    sideEffects: ['Bradycardia', 'Heart block', 'Edema', 'Dizziness', 'Constipation', 'Heart failure exacerbation'],
    contraindications: ['Severe bradycardia', '2nd/3rd degree AV block', 'Sick sinus syndrome', 'Cardiogenic shock', 'Heart failure with reduced EF'],
  },
  Verapamil: {
    name: 'Verapamil',
    drugClass: 'Non-dihydropyridine Calcium Channel Blocker',
    indications: ['Atrial fibrillation/flutter (rate control)', 'SVT termination', 'Angina', 'Hypertension', 'Migraine prophylaxis'],
    sideEffects: ['Constipation (prominent)', 'Bradycardia', 'Heart block', 'Edema', 'Heart failure exacerbation', 'Gingival hyperplasia'],
    contraindications: ['Severe bradycardia', '2nd/3rd degree AV block', 'Heart failure with reduced EF', 'Cardiogenic shock', 'Concurrent beta-blockers IV'],
  },
};
