import type { DrugInfo } from '../medicalTypes';

export const DRUGS_PART2: Record<string, DrugInfo> = {
  Amoxicillin: {
    name: 'Amoxicillin',
    drugClass: 'Penicillin Antibiotic',
    indications: ['Upper respiratory infections', 'Otitis media', 'UTI', 'H. pylori eradication', 'Dental infections', 'Community-acquired pneumonia'],
    sideEffects: ['GI upset', 'Diarrhea', 'Skin rash', 'Allergic reactions (anaphylaxis rare)', 'C. difficile colitis'],
    contraindications: ['Penicillin hypersensitivity', 'History of amoxicillin-associated cholestatic jaundice', 'Infectious mononucleosis (rash risk)'],
  },
  Ampicillin: {
    name: 'Ampicillin',
    drugClass: 'Penicillin Antibiotic (aminopenicillin)',
    indications: ['Listeria meningitis', 'Enterococcal infections', 'UTI', 'Endocarditis prophylaxis', 'Respiratory infections'],
    sideEffects: ['GI upset', 'Diarrhea', 'Rash', 'C. difficile colitis', 'Allergic reactions'],
    contraindications: ['Penicillin hypersensitivity', 'Infectious mononucleosis (rash risk)'],
  },
  PenicillinV: {
    name: 'Penicillin V',
    drugClass: 'Penicillin Antibiotic',
    indications: ['Streptococcal pharyngitis', 'Prophylaxis of rheumatic fever', 'Dental infections', 'Erysipelas'],
    sideEffects: ['GI upset', 'Diarrhea', 'Rash', 'Allergic reactions'],
    contraindications: ['Penicillin hypersensitivity'],
  },
  PiperacillinTazobactam: {
    name: 'Piperacillin-Tazobactam',
    drugClass: 'Beta-lactam/Beta-lactamase inhibitor',
    indications: ['Hospital-acquired pneumonia', 'Intra-abdominal infections', 'Complicated UTIs', 'Febrile neutropenia', 'Pseudomonas infections'],
    sideEffects: ['Diarrhea', 'Rash', 'Nausea', 'Clostridioides difficile colitis', 'Renal impairment'],
    contraindications: ['Penicillin hypersensitivity', 'Severe beta-lactam allergy'],
  },
  Nafcillin: {
    name: 'Nafcillin',
    drugClass: 'Penicillinase-resistant Penicillin',
    indications: ['MSSA infections', 'Severe staphylococcal infections', 'MSSA endocarditis'],
    sideEffects: ['Phlebitis', 'Neutropenia', 'Hypokalemia', 'Nausea', 'Rash'],
    contraindications: ['Penicillin hypersensitivity'],
  },
  Dicloxacillin: {
    name: 'Dicloxacillin',
    drugClass: 'Penicillinase-resistant Penicillin',
    indications: ['MSSA skin infections', 'Cellulitis', 'Impetigo', 'Abscesses'],
    sideEffects: ['GI upset', 'Rash', 'Hepatotoxicity', 'Nausea'],
    contraindications: ['Penicillin hypersensitivity'],
  },
  AmoxicillinClavulanate: {
    name: 'Amoxicillin-Clavulanate',
    drugClass: 'Beta-lactam/Beta-lactamase inhibitor',
    indications: ['Otitis media', 'Sinusitis', 'Animal bites', 'Diabetic foot infections', 'Community-acquired pneumonia', 'Wound infections'],
    sideEffects: ['Diarrhea', 'Nausea/vomiting', 'Cholestatic jaundice', 'Rash', 'C. difficile colitis'],
    contraindications: ['Penicillin hypersensitivity', 'History of amoxicillin-clavulanate jaundice', 'Severe hepatic impairment'],
  },
  Cephalexin: {
    name: 'Cephalexin',
    drugClass: 'First-generation Cephalosporin',
    indications: ['Skin and soft tissue infections', 'Streptococcal pharyngitis', 'UTI', 'Bone infections', 'Surgical prophylaxis'],
    sideEffects: ['GI upset', 'Diarrhea', 'Rash', 'Hypersensitivity reactions', 'C. difficile colitis'],
    contraindications: ['Cephalosporin hypersensitivity', 'Severe penicillin allergy (cross-reactivity caution)'],
  },
  Cefazolin: {
    name: 'Cefazolin',
    drugClass: 'First-generation Cephalosporin',
    indications: ['Surgical prophylaxis', 'MSSA infections', 'Skin/soft tissue infections', 'UTI'],
    sideEffects: ['GI upset', 'Rash', 'Hypersensitivity', 'Renal impairment', 'C. difficile colitis'],
    contraindications: ['Cephalosporin hypersensitivity', 'Severe penicillin allergy caution'],
  },
  Cefuroxime: {
    name: 'Cefuroxime',
    drugClass: 'Second-generation Cephalosporin',
    indications: ['Respiratory infections', 'Otitis media', 'Sinusitis', 'UTI', 'Surgical prophylaxis'],
    sideEffects: ['Diarrhea', 'Nausea', 'Hypersensitivity', 'C. difficile colitis', 'Headache'],
    contraindications: ['Cephalosporin hypersensitivity'],
  },
  Cefoxitin: {
    name: 'Cefoxitin',
    drugClass: 'Second-generation Cephalosporin (cephamycin)',
    indications: ['Anaerobic infections', 'Pelvic inflammatory disease', 'Intra-abdominal infections', 'Prophylaxis (colorectal surgery)'],
    sideEffects: ['Diarrhea', 'Rash', 'Hypersensitivity', 'C. difficile colitis'],
    contraindications: ['Cephalosporin hypersensitivity'],
  },
  Ceftriaxone: {
    name: 'Ceftriaxone',
    drugClass: 'Third-generation Cephalosporin',
    indications: ['Bacterial meningitis', 'Community-acquired pneumonia', 'Gonorrhea', 'Sepsis', 'Lyme disease', 'Spontaneous bacterial peritonitis'],
    sideEffects: ['Diarrhea', 'Biliary sludging', 'Hypersensitivity', 'Neutropenia', 'C. difficile colitis'],
    contraindications: ['Cephalosporin hypersensitivity', 'Neonates with hyperbilirubinemia', 'Concurrent calcium-containing IV fluids in neonates'],
  },
  Ceftazidime: {
    name: 'Ceftazidime',
    drugClass: 'Third-generation Cephalosporin (anti-Pseudomonas)',
    indications: ['Pseudomonas infections', 'Hospital-acquired pneumonia', 'Febrile neutropenia', 'Gram-negative infections'],
    sideEffects: ['Diarrhea', 'Rash', 'Hypersensitivity', 'Renal impairment'],
    contraindications: ['Cephalosporin hypersensitivity'],
  },
  Cefepime: {
    name: 'Cefepime',
    drugClass: 'Fourth-generation Cephalosporin',
    indications: ['Febrile neutropenia', 'Severe Gram-negative infections', 'Pseudomonas infections', 'Hospital-acquired pneumonia'],
    sideEffects: ['Diarrhea', 'Rash', 'Neurotoxicity (high doses/renal failure)', 'Hypersensitivity'],
    contraindications: ['Cephalosporin hypersensitivity', 'Severe penicillin allergy caution'],
  },
  Ceftaroline: {
    name: 'Ceftaroline',
    drugClass: 'Fifth-generation Cephalosporin',
    indications: ['MRSA skin infections', 'Community-acquired pneumonia (including MRSA)', 'Complicated skin infections'],
    sideEffects: ['Diarrhea', 'Rash', 'Hypersensitivity', 'Eosinophilic pneumonia (rare)'],
    contraindications: ['Cephalosporin hypersensitivity'],
  },
  Cefdinir: {
    name: 'Cefdinir',
    drugClass: 'Third-generation Cephalosporin (oral)',
    indications: ['Ottitis media', 'Sinusitis', 'Pharyngitis', 'Skin infections', 'Community-acquired pneumonia'],
    sideEffects: ['Diarrhea', 'Nausea', 'Rash', 'Red stools (with iron)', 'C. difficile colitis'],
    contraindications: ['Cephalosporin hypersensitivity'],
  },
  Cefixime: {
    name: 'Cefixime',
    drugClass: 'Third-generation Cephalosporin (oral)',
    indications: ['Gonorrhea', 'Otitis media', 'UTI', 'Pharyngitis'],
    sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain', 'Hypersensitivity'],
    contraindications: ['Cephalosporin hypersensitivity'],
  },
  Azithromycin: {
    name: 'Azithromycin',
    drugClass: 'Macrolide Antibiotic',
    indications: ['Community-acquired pneumonia', 'Bronchitis', 'Pharyngitis', 'Chlamydia', "Traveler's diarrhea", 'Sinusitis'],
    sideEffects: ['GI upset', 'Diarrhea', 'QT prolongation', 'Hepatotoxicity', 'Ototoxicity (rare)', 'Cardiac arrhythmias'],
    contraindications: ['Macrolide hypersensitivity', 'Severe hepatic impairment', 'Concurrent QT-prolonging drugs', 'History of cholestatic jaundice with macrolides'],
  },
  Clarithromycin: {
    name: 'Clarithromycin',
    drugClass: 'Macrolide Antibiotic',
    indications: ['Community-acquired pneumonia', 'H. pylori eradication', 'Bronchitis', 'Mycobacterium avium complex', 'Sinusitis'],
    sideEffects: ['GI upset', 'Metallic taste', 'QT prolongation', 'CYP3A4 inhibition (drug interactions)', 'Hepatotoxicity'],
    contraindications: ['Macrolide hypersensitivity', 'Concurrent QT-prolonging drugs', 'Cisapride/pimozide use', 'Severe hepatic impairment'],
  },
  Erythromycin: {
    name: 'Erythromycin',
    drugClass: 'Macrolide Antibiotic',
    indications: ['Pertussis', 'Legionella', 'Streptococcal infections', 'Chlamydia', 'Gastroparesis (motilin agonist)'],
    sideEffects: ['GI upset (prominent)', 'QT prolongation', 'Ototoxicity (high doses)', 'Cholestatic hepatitis'],
    contraindications: ['Macrolide hypersensitivity', 'Concurrent QT-prolonging drugs', 'Pimozide use'],
  },
  Fidaxomicin: {
    name: 'Fidaxomicin',
    drugClass: 'Macrolide Antibiotic (enteric)',
    indications: ['Clostridioides difficile infection'],
    sideEffects: ['Nausea', 'Abdominal pain', 'Vomiting', 'Anemia'],
    contraindications: ['Fidaxomicin hypersensitivity'],
  },
  Metronidazole: {
    name: 'Metronidazole',
    drugClass: 'Nitroimidazole Antibiotic/Antiprotozoal',
    indications: ['Anaerobic infections', 'Diverticulitis', 'Bacterial vaginosis', 'Trichomoniasis', 'Giardiasis', 'C. difficile (selected)'],
    sideEffects: ['Metallic taste', 'Nausea', 'GI upset', 'Disulfiram-like reaction with alcohol', 'Peripheral neuropathy (long-term)'],
    contraindications: ['Metronidazole hypersensitivity', 'First trimester pregnancy (relative)', 'Concurrent disulfiram or alcohol'],
  },
  Tinidazole: {
    name: 'Tinidazole',
    drugClass: 'Nitroimidazole Antibiotic/Antiprotozoal',
    indications: ['Trichomoniasis', 'Giardiasis', 'Amebiasis', 'Anaerobic infections'],
    sideEffects: ['Metallic taste', 'Nausea', 'GI upset', 'Headache', 'Alcohol disulfiram-like reaction'],
    contraindications: ['Tinidazole hypersensitivity', 'First trimester pregnancy', 'Concurrent alcohol'],
  },
  Clindamycin: {
    name: 'Clindamycin',
    drugClass: 'Lincosamide Antibiotic',
    indications: ['Anaerobic infections', 'Skin/soft tissue infections', 'Bone/joint infections', 'Aspiration pneumonia', 'Group A strep (adjunct)', 'Malaria (adjunct)'],
    sideEffects: ['C. difficile colitis (prominent)', 'Diarrhea', 'Nausea', 'Rash', 'Esophageal irritation'],
    contraindications: ['Clindamycin hypersensitivity', 'History of antibiotic-associated colitis'],
  },
  Linezolid: {
    name: 'Linezolid',
    drugClass: 'Oxazolidinone Antibiotic',
    indications: ['MRSA infections', 'VRE infections', 'Vancomycin-resistant enterococci', 'Pneumonia (resistant strains)'],
    sideEffects: ['Myelosuppression (thrombocytopenia, anemia)', 'Peripheral neuropathy', 'Serotonin syndrome (MAO inhibition)', 'Lactic acidosis', 'Optic neuropathy'],
    contraindications: ['Concurrent serotonergic drugs (SSRIs/MAOIs)', 'Uncontrolled hypertension (relative)', 'Concurrent tyramine-rich foods'],
  },
  Tedizolid: {
    name: 'Tedizolid',
    drugClass: 'Oxazolidinone Antibiotic',
    indications: ['MRSA skin/soft tissue infections', 'VRE infections'],
    sideEffects: ['Nausea', 'Headache', 'Neuropathy (less than linezolid)', 'Anemia (less)'],
    contraindications: ['Tedizolid hypersensitivity', 'Concurrent MAOIs'],
  },
  Vancomycin: {
    name: 'Vancomycin',
    drugClass: 'Glycopeptide Antibiotic',
    indications: ['MRSA infections', 'Serious Gram-positive infections', 'Endocarditis', 'Meningitis (Gram-positive)', 'C. difficile (oral)'],
    sideEffects: ['Red man syndrome (infusion)', 'Nephrotoxicity', 'Ototoxicity', 'Neutropenia', 'Thrombophlebitis'],
    contraindications: ['Vancomycin hypersensitivity', 'Severe renal impairment (dose adjustment)'],
  },
  Teicoplanin: {
    name: 'Teicoplanin',
    drugClass: 'Glycopeptide Antibiotic',
    indications: ['MRSA infections', 'Gram-positive infections', 'Endocarditis', 'Surgical prophylaxis'],
    sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Rash', 'Thrombocytopenia'],
    contraindications: ['Teicoplanin hypersensitivity'],
  },
  Telavancin: {
    name: 'Telavancin',
    drugClass: 'Lipoglycopeptide Antibiotic',
    indications: ['MRSA pneumonia (HAP/VAP)', 'Complicated skin infections (MRSA)'],
    sideEffects: ['Nephrotoxicity', 'QT prolongation', 'Taste disturbance', 'Fetal harm'],
    contraindications: ['Telavancin hypersensitivity', 'Pregnancy', 'Concurrent QT-prolonging drugs'],
  },
  Dalbavancin: {
    name: 'Dalbavancin',
    drugClass: 'Lipoglycopeptide Antibiotic',
    indications: ['MRSA skin/soft tissue infections', 'Bacteremia (off-label)'],
    sideEffects: ['Nausea', 'Headache', 'Diarrhea', 'Rash', 'Elevated liver enzymes'],
    contraindications: ['Dalbavancin hypersensitivity'],
  },
  Daptomycin: {
    name: 'Daptomycin',
    drugClass: 'Lipopeptide Antibiotic',
    indications: ['MRSA bacteremia', 'Right-sided endocarditis', 'Skin/soft tissue infections', 'VRE infections'],
    sideEffects: ['Myopathy (elevated CK)', 'Rhabdomyolysis', 'Eosinophilic pneumonia', 'Peripheral neuropathy'],
    contraindications: ['Daptomycin hypersensitivity', 'Pneumonia (inactivated by surfactant)'],
  },
  Gentamicin: {
    name: 'Gentamicin',
    drugClass: 'Aminoglycoside Antibiotic',
    indications: ['Severe Gram-negative infections', 'Endocarditis (synergy)', 'Febrile neutropenia (combination)', 'UTI (complicated)'],
    sideEffects: ['Nephrotoxicity', 'Ototoxicity (vestibular/cochlear)', 'Neuromuscular blockade', 'Hypomagnesemia'],
    contraindications: ['Aminoglycoside hypersensitivity', 'Myasthenia gravis (relative)', 'Severe renal impairment (dose adjustment)'],
  },
  Tobramycin: {
    name: 'Tobramycin',
    drugClass: 'Aminoglycoside Antibiotic',
    indications: ['Pseudomonas infections', 'Cystic fibrosis (inhaled)', 'Severe Gram-negative infections'],
    sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Neuromuscular blockade', 'Bronchospasm (inhaled)'],
    contraindications: ['Aminoglycoside hypersensitivity', 'Severe renal impairment'],
  },
  Amikacin: {
    name: 'Amikacin',
    drugClass: 'Aminoglycoside Antibiotic',
    indications: ['Resistant Gram-negative infections', 'Multidrug-resistant TB', 'Severe hospital infections'],
    sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Neuromuscular blockade'],
    contraindications: ['Aminoglycoside hypersensitivity', 'Severe renal impairment'],
  },
  Ciprofloxacin: {
    name: 'Ciprofloxacin',
    drugClass: 'Fluoroquinolone Antibiotic',
    indications: ['UTI', 'Complicated infections', 'Bone/joint infections', 'Anthrax prophylaxis', 'Infectious diarrhea'],
    sideEffects: ['Tendon rupture/tendinitis', 'QT prolongation', 'Peripheral neuropathy', 'CNS effects', 'GI upset', 'Phototoxicity'],
    contraindications: ['Fluoroquinolone hypersensitivity', 'Concurrent tizanidine', 'Myasthenia gravis', 'Aortic aneurysm risk', 'QT prolongation'],
  },
  Levofloxacin: {
    name: 'Levofloxacin',
    drugClass: 'Fluoroquinolone Antibiotic',
    indications: ['Community-acquired pneumonia', 'Sinusitis', 'UTI', 'Prostatitis', 'Skin infections'],
    sideEffects: ['Tendon rupture', 'QT prolongation', 'Peripheral neuropathy', 'Blood glucose disturbances', 'CNS effects'],
    contraindications: ['Fluoroquinolone hypersensitivity', 'Myasthenia gravis', 'Concurrent QT-prolonging drugs'],
  },
  Moxifloxacin: {
    name: 'Moxifloxacin',
    drugClass: 'Fluoroquinolone Antibiotic',
    indications: ['Community-acquired pneumonia', 'Intra-abdominal infections', 'Skin infections', 'Sinusitis'],
    sideEffects: ['QT prolongation (prominent)', 'Tendon rupture', 'GI upset', 'Hepatotoxicity', 'Peripheral neuropathy'],
    contraindications: ['Fluoroquinolone hypersensitivity', 'Prolonged QT', 'Uncorrected hypokalemia', 'Myasthenia gravis'],
  },
  Doxycycline: {
    name: 'Doxycycline',
    drugClass: 'Tetracycline Antibiotic',
    indications: ['Community-acquired pneumonia', 'Lyme disease', 'Malaria prophylaxis', 'Acne vulgaris', 'Chlamydia', 'MRSA skin infections'],
    sideEffects: ['Photosensitivity', 'Esophageal irritation', 'GI upset', 'Tooth discoloration in children', 'Vaginal candidiasis'],
    contraindications: ['Pregnancy', 'Children under 8', 'Hepatic impairment', 'Concurrent warfarin (increased INR)'],
  },
  Minocycline: {
    name: 'Minocycline',
    drugClass: 'Tetracycline Antibiotic',
    indications: ['Acne vulgaris', 'MRSA colonization', 'Rheumatoid arthritis (adjunct)', 'Chlamydia'],
    sideEffects: ['Dizziness/vestibular effects', 'Photosensitivity', 'Hyperpigmentation', 'Tooth discoloration', 'Drug-induced lupus'],
    contraindications: ['Pregnancy', 'Children under 8', 'Concurrent isotretinoin'],
  },
  Tetracycline: {
    name: 'Tetracycline',
    drugClass: 'Tetracycline Antibiotic',
    indications: ['Acne', 'Chlamydia', 'Rickettsial infections', 'Brucellosis', 'Helicobacter pylori'],
    sideEffects: ['GI upset', 'Photosensitivity', 'Tooth discoloration', 'Esophageal ulceration', 'Hepatotoxicity'],
    contraindications: ['Pregnancy', 'Children under 8', 'Renal impairment'],
  },
  TrimethoprimSulfamethoxazole: {
    name: 'Trimethoprim-Sulfamethoxazole',
    drugClass: 'Sulfonamide Combination Antibiotic',
    indications: ['UTI', 'Pneumocystis jirovecii pneumonia (PCP)', 'MRSA skin infections', "Traveler's diarrhea", 'Shigellosis', 'Acinetobacter'],
    sideEffects: ['Hyperkalemia', 'Skin rash', 'Stevens-Johnson syndrome', 'Bone marrow suppression', 'Crystalluria', 'Photosensitivity'],
    contraindications: ['Sulfonamide allergy', 'Pregnancy (third trimester)', 'Severe renal impairment', 'G6PD deficiency', 'Megaloblastic anemia'],
  },
};
