import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART1: Record<string, DiseaseInfo> = {
  'Diabetes Mellitus Type 1': {
    category: 'endocrine',
    name: 'Diabetes Mellitus Type 1',
    symptoms: ['Polyuria', 'Polydipsia', 'Polyphagia', 'Weight loss', 'Fatigue', 'Ketoacidosis risk', 'Blurred vision'],
    causes: ['Autoimmune beta-cell destruction', 'Genetic predisposition', 'Viral triggers', 'Environmental factors'],
    treatment: ['Insulin therapy (basal + bolus)', 'Carbohydrate counting', 'Continuous glucose monitoring', 'Insulin pumps', 'Education and self-management'],
    description: 'An autoimmune disorder in which the immune system destroys insulin-producing beta cells, leading to absolute insulin deficiency and lifelong dependence on exogenous insulin.',
  },
  'Diabetes Mellitus Type 2': {
    category: 'endocrine',
    name: 'Diabetes Mellitus Type 2',
    symptoms: ['Polyuria', 'Polydipsia', 'Polyphagia', 'Fatigue', 'Blurred vision', 'Slow wound healing', 'Tingling in hands/feet'],
    causes: ['Insulin resistance', 'Genetic predisposition', 'Obesity', 'Sedentary lifestyle', 'Age over 45', 'PCOS'],
    treatment: ['Metformin', 'Lifestyle modifications', 'Diet control', 'Regular exercise', 'Sulfonylureas', 'GLP-1 agonists', 'SGLT2 inhibitors', 'Insulin therapy if needed'],
    description: 'A chronic metabolic disorder characterized by high blood glucose levels due to insulin resistance and relative insulin deficiency.',
  },
  'Gestational Diabetes': {
    category: 'endocrine',
    name: 'Gestational Diabetes Mellitus',
    symptoms: ['Often asymptomatic', 'Excessive thirst', 'Frequent urination', 'Fatigue', 'Recurrent infections'],
    causes: ['Placental hormones causing insulin resistance', 'Obesity', 'Family history of diabetes', 'Advanced maternal age', 'PCOS'],
    treatment: ['Diet and lifestyle modification', 'Blood glucose monitoring', 'Insulin therapy', 'Metformin (off-label)', 'Postpartum glucose re-screening'],
    description: 'Carbohydrate intolerance with onset during pregnancy, typically resolving after delivery but increasing future risk of type 2 diabetes.',
  },
  'Hypothyroidism': {
    category: 'endocrine',
    name: 'Hypothyroidism',
    symptoms: ['Fatigue', 'Weight gain', 'Cold intolerance', 'Constipation', 'Dry skin', 'Hair loss', 'Bradycardia', 'Depression'],
    causes: ['Hashimoto thyroiditis', 'Iodine deficiency', 'Post-thyroidectomy', 'Radioactive iodine therapy', 'Pituitary disease'],
    treatment: ['Levothyroxine replacement', 'Monitor TSH levels', 'Dose adjustment in pregnancy', 'Underlying cause management'],
    description: 'A condition in which the thyroid gland produces insufficient thyroid hormone, slowing the body metabolic rate.',
  },
  'Hyperthyroidism': {
    category: 'endocrine',
    name: 'Hyperthyroidism',
    symptoms: ['Weight loss', 'Tachycardia', 'Heat intolerance', 'Tremor', 'Anxiety', 'Diarrhea', 'Sweating', 'Exophthalmos (if Graves)'],
    causes: ['Graves disease', 'Toxic multinodular goiter', 'Toxic adenoma', 'Subacute thyroiditis', 'Excess levothyroxine'],
    treatment: ['Antithyroid drugs (Methimazole)', 'Beta-blockers for symptoms', 'Radioactive iodine', 'Thyroidectomy', 'Glucocorticoids in thyroid storm'],
    description: 'A condition caused by excessive circulating thyroid hormone, resulting in a hypermetabolic state.',
  },
  'Graves Disease': {
    category: 'endocrine',
    name: 'Graves Disease',
    symptoms: ['Exophthalmos', 'Goiter', 'Palpitations', 'Weight loss', 'Heat intolerance', 'Tremor', 'Pretibial myxedema'],
    causes: ['Autoimmune stimulation of TSH receptor', 'Genetic predisposition', 'Female sex', 'Smoking'],
    treatment: ['Antithyroid drugs (Methimazole)', 'Radioactive iodine ablation', 'Thyroidectomy', 'Beta-blockers', 'Ophthalmology referral for eye disease'],
    description: 'An autoimmune condition in which thyroid-stimulating antibodies mimic TSH, causing overproduction of thyroid hormone and characteristic eye findings.',
  },
  'Hashimoto Thyroiditis': {
    category: 'endocrine',
    name: 'Hashimoto Thyroiditis',
    symptoms: ['Fatigue', 'Weight gain', 'Cold intolerance', 'Dry skin', 'Constipation', 'Goiter', 'Hair thinning'],
    causes: ['Autoimmune inflammation of thyroid', 'Genetic predisposition', 'Female sex', 'Iodine excess'],
    treatment: ['Levothyroxine if hypothyroid', 'Periodic TSH monitoring', 'Selenium supplementation (adjunct)'],
    description: 'A chronic autoimmune inflammation of the thyroid gland, the most common cause of hypothyroidism in iodine-sufficient regions.',
  },
  'Subacute Thyroiditis': {
    category: 'endocrine',
    name: 'Subacute (De Quervain) Thyroiditis',
    symptoms: ['Tender painful thyroid', 'Fever', 'Malaise', 'Transient hyperthyroidism', 'Viral prodrome'],
    causes: ['Viral infection', 'Post-viral inflammatory phase', 'Female sex'],
    treatment: ['NSAIDs', 'Beta-blockers for symptoms', 'Glucocorticoids if severe', 'Levothyroxine if transient hypothyroidism'],
    description: 'A self-limited painful inflammation of the thyroid, usually following a viral infection, with a triphasic pattern of hyper-, eu-, and hypothyroidism.',
  },
  'Thyroid Nodule': {
    category: 'endocrine',
    name: 'Thyroid Nodule',
    symptoms: ['Often asymptomatic', 'Palpable neck lump', 'Dysphagia', 'Hoarseness', 'Pain (rare)'],
    causes: ['Benign colloid nodules', 'Follicular adenoma', 'Thyroid cyst', 'Thyroid cancer (small %)', 'Iodine deficiency'],
    treatment: ['Thyroid ultrasound', 'FNA biopsy if suspicious', 'Thyroid function tests', 'Surgery for malignant/large nodules', 'Serial monitoring'],
    description: 'A discrete lesion within the thyroid gland; most are benign, but ultrasound features and cytology guide further management.',
  },
  'Goiter': {
    category: 'endocrine',
    name: 'Goiter',
    symptoms: ['Enlarged thyroid gland', 'Neck swelling', 'Pressure symptoms', 'Dysphagia', 'Dyspnea (severe)'],
    causes: ['Iodine deficiency', 'Hashimoto disease', 'Graves disease', 'Multinodular disease', 'Goitrogens'],
    treatment: ['Treat underlying cause', 'Levothyroxine for deficiency', 'Iodine supplementation', 'Radioactive iodine or surgery for compressive symptoms'],
    description: 'Non-neoplastic enlargement of the thyroid gland, which can be diffuse or nodular and may be associated with altered thyroid function.',
  },
  'Addison Disease': {
    category: 'endocrine',
    name: 'Adrenal Insufficiency (Addison Disease)',
    symptoms: ['Fatigue', 'Weight loss', 'Hyperpigmentation', 'Hypotension', 'Salt craving', 'Nausea', 'Abdominal pain', 'Adrenal crisis'],
    causes: ['Autoimmune adrenal destruction', 'Tuberculosis', 'Metastatic cancer', 'HIV', 'Hemorrhage'],
    treatment: ['Glucocorticoid replacement (Hydrocortisone)', 'Mineralocorticoid replacement (Fludrocortisone)', 'Stress-dose steroids', 'Sick-day rules'],
    description: 'Primary failure of the adrenal glands producing insufficient cortisol and aldosterone, with potentially life-threatening adrenal crisis.',
  },
  'Cushing Syndrome': {
    category: 'endocrine',
    name: 'Cushing Syndrome',
    symptoms: ['Central obesity', 'Moon facies', 'Buffalo hump', 'Purple striae', 'Easy bruising', 'Hypertension', 'Hyperglycemia', 'Proximal muscle weakness'],
    causes: ['Exogenous glucocorticoids (most common)', 'Pituitary adenoma (Cushing disease)', 'Adrenal adenoma', 'Ectopic ACTH'],
    treatment: ['Taper exogenous steroids', 'Surgical resection of adenoma', 'Radiation therapy', 'Adrenal enzyme inhibitors', 'Glucocorticoid blockade'],
    description: 'A syndrome of sustained glucocorticoid excess with characteristic metabolic and physical features.',
  },
  'Hyperaldosteronism': {
    category: 'endocrine',
    name: 'Primary Hyperaldosteronism (Conn Syndrome)',
    symptoms: ['Hypertension (often resistant)', 'Hypokalemia', 'Muscle weakness', 'Palpitations', 'Polyuria', 'Headache'],
    causes: ['Adrenal adenoma', 'Bilateral adrenal hyperplasia', 'Adrenal carcinoma (rare)', 'Familial hyperaldosteronism'],
    treatment: ['Surgical adrenalectomy for adenoma', 'Spironolactone', 'Eplerenone', 'Aldosterone antagonists', 'Blood pressure monitoring'],
    description: 'Excess aldosterone secretion from the adrenal glands causing hypertension, hypokalemia, and suppressed renin.',
  },
  'Pheochromocytoma': {
    category: 'endocrine',
    name: 'Pheochromocytoma',
    symptoms: ['Paroxysmal hypertension', 'Palpitations', 'Severe headache', 'Sweating', 'Tremor', 'Anxiety', 'Pallor'],
    causes: ['Adrenal medulla tumor', 'Genetic syndromes (MEN2, VHL, NF1)', 'Extra-adrenal paraganglioma'],
    treatment: ['Alpha-blockade first (Phenoxybenzamine)', 'Beta-blockade after alpha', 'Surgical resection', 'Blood pressure control'],
    description: 'A catecholamine-secreting tumor of the adrenal medulla causing episodic hypertension and classic headache-palpitations-sweating triad.',
  },
  'Congenital Adrenal Hyperplasia': {
    category: 'endocrine',
    name: 'Congenital Adrenal Hyperplasia',
    symptoms: ['Ambiguous genitalia (females)', 'Virilization', 'Salt wasting', 'Failure to thrive', 'Adrenal crisis', 'Premature puberty'],
    causes: ['21-hydroxylase deficiency', '11-beta-hydroxylase deficiency', 'Autosomal recessive mutations'],
    treatment: ['Glucocorticoid replacement', 'Mineralocorticoid replacement', 'Salt supplementation', 'Reconstructive surgery (selected cases)'],
    description: 'An inherited disorder of adrenal steroid biosynthesis causing cortisol deficiency with androgen excess and variable mineralocorticoid deficiency.',
  },
  'Acromegaly': {
    category: 'endocrine',
    name: 'Acromegaly',
    symptoms: ['Enlarged hands and feet', 'Coarse facial features', 'Prognathism', 'Headache', 'Hyperhidrosis', 'Deep voice', 'Joint pain', 'Visual field defects'],
    causes: ['Growth hormone-secreting pituitary adenoma', 'GH excess before epiphyseal closure (gigantism)'],
    treatment: ['Transsphenoidal surgery', 'Somatostatin analogues (Octreotide)', 'GH receptor antagonist (Pegvisomant)', 'Radiotherapy', 'Dopamine agonists'],
    description: 'Chronic excess of growth hormone, usually from a pituitary adenoma, causing progressive enlargement of acral and soft tissues.',
  },
  'Growth Hormone Deficiency': {
    category: 'endocrine',
    name: 'Growth Hormone Deficiency',
    symptoms: ['Short stature', 'Delayed puberty', 'Decreased muscle mass', 'Increased fat mass', 'Low energy'],
    causes: ['Pituitary tumors', 'Cranial irradiation', 'Congenital hypopituitarism', 'Traumatic brain injury', 'Idiopathic'],
    treatment: ['Recombinant growth hormone therapy', 'Monitor growth velocity', 'Treat underlying cause'],
    description: 'Insufficient growth hormone secretion during childhood leading to growth failure and short stature.',
  },
  'Prolactinoma': {
    category: 'endocrine',
    name: 'Prolactinoma',
    symptoms: ['Galactorrhea', 'Amenorrhea', 'Decreased libido', 'Impotence', 'Headache', 'Visual field defects', 'Infertility'],
    causes: ['Lactotroph pituitary adenoma', 'Genetic syndromes (MEN1)'],
    treatment: ['Dopamine agonists (Cabergoline, Bromocriptine)', 'Transsphenoidal surgery if refractory', 'Radiotherapy (rare)', 'Monitoring tumor size'],
    description: 'A benign prolactin-secreting tumor of the pituitary gland, the most common hormone-secreting pituitary adenoma.',
  },
  'Diabetes Insipidus': {
    category: 'endocrine',
    name: 'Diabetes Insipidus',
    symptoms: ['Polyuria (large volume)', 'Nocturia', 'Polydipsia', 'Risk of dehydration', 'Normal or high plasma osmolarity'],
    causes: ['Central: pituitary/hypothalamic lesions', 'Nephrogenic: lithium, hypercalcemia, kidney disease', 'Head trauma', 'Neurosurgery'],
    treatment: ['Central: Desmopressin', 'Nephrogenic: water intake, thiazides, treat cause', 'Correct underlying electrolyte disorders'],
    description: 'A disorder of water balance due to ADH deficiency (central) or renal resistance to ADH (nephrogenic), characterized by dilute polyuria.',
  },
  'SIADH': {
    category: 'endocrine',
    name: 'Syndrome of Inappropriate ADH (SIADH)',
    symptoms: ['Hyponatremia', 'Nausea', 'Headache', 'Confusion', 'Lethargy', 'Seizures (severe)'],
    causes: ['Small cell lung cancer', 'CNS disorders', 'Pulmonary disease', 'Drugs (SSRIs, carbamazepine)', 'Postoperative state'],
    treatment: ['Fluid restriction', 'Demeclocycline', 'Vaptans (Tolvaptan)', 'Treat underlying cause', 'Careful sodium correction'],
    description: 'Euvolemic hyponatremia caused by inappropriate release of antidiuretic hormone despite low plasma osmolality.',
  },
  'Hypopituitarism': {
    category: 'endocrine',
    name: 'Hypopituitarism',
    symptoms: ['Fatigue', 'Hypogonadism', 'Growth failure', 'Hypothyroidism', 'Adrenal insufficiency', 'Low blood pressure'],
    causes: ['Pituitary adenoma (mass effect)', 'Sheehan syndrome', 'Pituitary surgery/radiation', 'Hypophysitis', 'Trauma'],
    treatment: ['Hormone replacement (thyroid, cortisol, sex steroids, GH)', 'Monitor hormone levels', 'Treat underlying cause'],
    description: 'Partial or complete loss of pituitary hormone secretion leading to failure of target endocrine glands.',
  },
  'Hyperparathyroidism': {
    category: 'endocrine',
    name: 'Primary Hyperparathyroidism',
    symptoms: ['Often asymptomatic', 'Nephrolithiasis', 'Bone pain', 'Fractures', 'Depression', 'Constipation', 'Fatigue'],
    causes: ['Parathyroid adenoma', 'Parathyroid hyperplasia', 'Parathyroid carcinoma (rare)', 'MEN syndromes'],
    treatment: ['Parathyroidectomy', 'Calcimimetics (Cinacalcet)', 'Hydration', 'Bisphosphonates (bone protection)', 'Monitoring asymptomatic cases'],
    description: 'Excess parathyroid hormone secretion causing hypercalcemia, hypophosphatemia, and complications of bone and renal disease.',
  },
  'Hypoparathyroidism': {
    category: 'endocrine',
    name: 'Hypoparathyroidism',
    symptoms: ['Perioral numbness', 'Carpopedal spasm', 'Tetany', 'Seizures', 'Laryngospasm', 'Chvostek sign', 'Trousseau sign'],
    causes: ['Post-thyroidectomy', 'Autoimmune polyendocrine syndrome', 'DiGeorge syndrome', 'Magnesium deficiency', 'Idiopathic'],
    treatment: ['Calcium supplementation', 'Vitamin D analogs (Calcitriol)', 'PTH replacement (parathyroid hormone)', 'Magnesium correction'],
    description: 'Insufficient parathyroid hormone causing hypocalcemia and hyperphosphatemia with neuromuscular excitability.',
  },
  'Obesity': {
    category: 'metabolic',
    name: 'Obesity',
    symptoms: ['Elevated BMI', 'Increased body fat', 'Breathlessness on exertion', 'Joint pain', 'Sleep apnea', 'Low energy'],
    causes: ['Excess caloric intake', 'Physical inactivity', 'Genetic factors', 'Endocrine disorders', 'Medications', 'Psychosocial factors'],
    treatment: ['Dietary modification', 'Regular exercise', 'Behavioral therapy', 'Pharmacotherapy (GLP-1, Orlistat)', 'Bariatric surgery (severe cases)'],
    description: 'A chronic disease of excess body fat leading to increased risk of metabolic, cardiovascular, and mechanical complications.',
  },
  'Metabolic Syndrome': {
    category: 'metabolic',
    name: 'Metabolic Syndrome',
    symptoms: ['Central obesity', 'Elevated triglycerides', 'Low HDL', 'Hypertension', 'Fasting hyperglycemia', 'Increased waist circumference'],
    causes: ['Insulin resistance', 'Visceral adiposity', 'Genetic predisposition', 'Sedentary lifestyle', 'High-carbohydrate diet'],
    treatment: ['Weight loss', 'Exercise', 'Treat each component (BP, lipids, glucose)', 'Mediterranean diet', 'Metformin if pre-diabetic'],
    description: 'A cluster of interconnected metabolic risk factors that increase the risk of type 2 diabetes and cardiovascular disease.',
  },
  'Hemochromatosis': {
    category: 'metabolic',
    name: 'Hereditary Hemochromatosis',
    symptoms: ['Fatigue', 'Arthralgia', 'Bronze skin pigmentation', 'Hepatomegaly', 'Cirrhosis', 'Diabetes', 'Cardiomyopathy', 'Impotence'],
    causes: ['HFE gene mutations (C282Y)', 'Excess dietary iron absorption', 'Autosomal recessive inheritance'],
    treatment: ['Therapeutic phlebotomy', 'Avoid iron/vitamin C supplements', 'Monitor ferritin and transferrin saturation', 'Treat organ complications'],
    description: 'An inherited disorder of excessive intestinal iron absorption leading to iron accumulation and organ damage (liver, pancreas, heart).',
  },
  'Wilson Disease': {
    category: 'metabolic',
    name: 'Wilson Disease',
    symptoms: ['Jaundice', 'Flapping tremor', 'Kayser-Fleischer rings', 'Dysarthria', 'Personality changes', 'Acute liver failure', 'Hemolysis'],
    causes: ['ATP7B gene mutations', 'Impaired biliary copper excretion', 'Autosomal recessive inheritance'],
    treatment: ['Penicillamine', 'Trientine', 'Zinc acetate', 'Low-copper diet', 'Liver transplantation (fulminant)'],
    description: 'An autosomal recessive disorder of copper metabolism causing accumulation of copper in the liver, brain, and other organs.',
  },
  'Porphyria': {
    category: 'metabolic',
    name: 'Acute Porphyria',
    symptoms: ['Abdominal pain', 'Neuropathy', 'Dark/red urine', 'Photosensitivity', 'Psychiatric symptoms', 'Tachycardia', 'Hypertension'],
    causes: ['Heme synthesis enzyme deficiencies', 'Triggers: drugs, fasting, alcohol, infections', 'Genetic mutations'],
    treatment: ['Avoid precipitating factors', 'Hemin infusion', 'Glucose loading', 'Pain management', 'Avoid porphyrinogenic drugs'],
    description: 'A group of metabolic disorders caused by enzyme defects in heme synthesis, with episodic neurovisceral attacks.',
  },
  'Phenylketonuria': {
    category: 'metabolic',
    name: 'Phenylketonuria (PKU)',
    symptoms: ['Intellectual disability (if untreated)', 'Musty odor', 'Light skin/hair', 'Eczema', 'Behavioral problems'],
    causes: ['PAH gene mutations', 'Phenylalanine hydroxylase deficiency', 'Autosomal recessive inheritance'],
    treatment: ['Low-phenylalanine diet', 'Amino acid formula', 'Sapropterin (in responsive forms)', 'Newborn screening and lifelong monitoring'],
    description: 'An inborn error of metabolism preventing conversion of phenylalanine to tyrosine, causing neurotoxicity if untreated.',
  },
  'Galactosemia': {
    category: 'metabolic',
    name: 'Galactosemia',
    symptoms: ['Vomiting', 'Poor feeding', 'Jaundice', 'Hepatomegaly', 'Cataracts', 'E. coli sepsis (neonates)', 'Intellectual disability (if untreated)'],
    causes: ['GALT gene deficiency', 'Impaired galactose metabolism', 'Autosomal recessive inheritance'],
    treatment: ['Galactose-free diet (lifelong)', 'Avoid milk/lactose', 'Manage cataracts', 'Developmental support'],
    description: 'An inherited inability to metabolize galactose, causing neonatal liver disease, cataracts, and sepsis risk if untreated.',
  },
  'Maple Syrup Urine Disease': {
    category: 'metabolic',
    name: 'Maple Syrup Urine Disease',
    symptoms: ['Maple syrup odor of urine', 'Poor feeding', 'Vomiting', 'Lethargy', 'Seizures', 'Hypoglycemia', 'Encephalopathy'],
    causes: ['BCKD complex enzyme deficiency', 'Branched-chain amino acid accumulation', 'Autosomal recessive inheritance'],
    treatment: ['Dietary restriction of branched-chain amino acids', 'Thiamine supplementation', 'Metabolic emergency protocols', 'Liver transplantation (severe)'],
    description: 'An inborn error of branched-chain amino acid metabolism causing toxic accumulation and life-threatening metabolic crisis in infancy.',
  },
  'Hyperlipidemia': {
    category: 'metabolic',
    name: 'Hyperlipidemia',
    symptoms: ['Usually asymptomatic', 'Xanthelasma', 'Tendon xanthomas', 'Premature cardiovascular disease', 'Pancreatitis (very high TG)'],
    causes: ['Genetic predisposition', 'High-fat diet', 'Obesity', 'Hypothyroidism', 'Diabetes', 'Alcohol'],
    treatment: ['Statins', 'Lifestyle modification', 'Fibrates for hypertriglyceridemia', 'Ezetimibe', 'PCSK9 inhibitors'],
    description: 'Elevated levels of lipids in the blood, a major modifiable risk factor for atherosclerotic cardiovascular disease.',
  },
  'Hyperuricemia': {
    category: 'metabolic',
    name: 'Hyperuricemia',
    symptoms: ['Often asymptomatic', 'Gout flares', 'Uric acid kidney stones', 'Arthritis flares'],
    causes: ['Purine-rich diet', 'Alcohol', 'Renal impairment', 'Diuretic use', 'Genetic factors', 'Tumor lysis'],
    treatment: ['Allopurinol', 'Febuxostat', 'Dietary modification', 'Hydration', 'Treat underlying cause'],
    description: 'Elevated serum uric acid, a precursor to gout and uric acid nephrolithiasis.',
  },
  'Lactose Intolerance': {
    category: 'metabolic',
    name: 'Lactose Intolerance',
    symptoms: ['Diarrhea', 'Abdominal bloating', 'Flatulence', 'Abdominal cramps', 'Nausea after dairy'],
    causes: ['Lactase enzyme deficiency', 'Intestinal injury', 'Congenital lactase deficiency'],
    treatment: ['Avoid or limit dairy', 'Lactase enzyme supplements', 'Lactose-free products', 'Calcium supplementation'],
    description: 'Inability to digest lactose due to lactase deficiency, causing osmotic diarrhea and gastrointestinal symptoms after dairy intake.',
  },
  'Vitamin D Deficiency': {
    category: 'metabolic',
    name: 'Vitamin D Deficiency',
    symptoms: ['Bone pain', 'Muscle weakness', 'Fatigue', 'Rickets in children', 'Osteomalacia in adults', 'Fractures'],
    causes: ['Inadequate sunlight', 'Poor dietary intake', 'Malabsorption', 'Renal/hepatic disease', 'Obesity', 'Medications (anticonvulsants)'],
    treatment: ['Vitamin D supplementation', 'Sun exposure', 'Treat underlying malabsorption', 'Calcium supplementation if needed'],
    description: 'Insufficient vitamin D leading to impaired calcium metabolism and bone mineralization.',
  },
  'Osteomalacia': {
    category: 'metabolic',
    name: 'Osteomalacia',
    symptoms: ['Bone pain', 'Muscle weakness', 'Fractures', 'Difficulty walking', 'Bone tenderness'],
    causes: ['Vitamin D deficiency', 'Phosphate deficiency', 'Renal tubular acidosis', 'Malabsorption'],
    treatment: ['Vitamin D and calcium replacement', 'Phosphate supplementation', 'Treat underlying cause', 'Monitoring bone markers'],
    description: 'Softening of bones due to defective mineralization, most commonly from vitamin D deficiency.',
  },
};