import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART5: Record<string, DiseaseInfo> = {
  'Major Depressive Disorder': {
    category: 'psychiatry',
    name: 'Major Depressive Disorder',
    symptoms: ['Persistent low mood', 'Loss of interest (anhedonia)', 'Fatigue', 'Sleep disturbance', 'Appetite changes', 'Poor concentration', 'Worthlessness', 'Suicidal ideation'],
    causes: ['Genetic predisposition', 'Serotonin/norepinephrine dysfunction', 'Stressful life events', 'Chronic illness', 'Hormonal factors'],
    treatment: ['SSRIs/SNRIs', 'Cognitive behavioral therapy', 'Psychotherapy', 'Exercise', 'Interpersonal therapy', 'Electroconvulsive therapy (severe)'],
    description: 'A common mood disorder of persistent sadness, low energy, and loss of interest lasting at least two weeks.',
  },
  'Bipolar Disorder': {
    category: 'psychiatry',
    name: 'Bipolar Disorder',
    symptoms: ['Mania: elevated mood, grandiosity, decreased sleep, impulsivity', 'Depressive episodes', 'Rapid speech', 'Risky behavior', 'Cyclic mood changes'],
    causes: ['Genetic predisposition', 'Neurotransmitter imbalance', 'Stressful life events', 'Substance use'],
    treatment: ['Mood stabilizers (Lithium)', 'Anticonvulsants (Valproate, Lamotrigine)', 'Atypical antipsychotics', 'Psychotherapy', 'Sleep hygiene', 'Avoid triggers'],
    description: 'A mood disorder characterized by alternating episodes of mania and depression.',
  },
  'Generalized Anxiety Disorder': {
    category: 'psychiatry',
    name: 'Generalized Anxiety Disorder',
    symptoms: ['Excessive worry', 'Restlessness', 'Fatigue', 'Muscle tension', 'Poor concentration', 'Irritability', 'Sleep disturbance'],
    causes: ['Genetic vulnerability', 'Neurotransmitter imbalance', 'Stressful life experiences', 'Personality traits', 'Chronic stressors'],
    treatment: ['SSRIs/SNRIs', 'Cognitive behavioral therapy', 'Relaxation techniques', 'Exercise', 'Mindfulness therapy', 'Sleep hygiene'],
    description: 'A chronic anxiety disorder of excessive, uncontrollable worry about various aspects of daily life.',
  },
  'Panic Disorder': {
    category: 'psychiatry',
    name: 'Panic Disorder',
    symptoms: ['Recurrent panic attacks', 'Palpitations', 'Chest pain', 'Difficulty breathing', 'Fear of dying', 'Derealization', 'Avoidance behaviors'],
    causes: ['Genetic factors', 'Norepinephrine dysfunction', 'Stressful triggers', 'Major life transitions', 'Catastrophic thinking'],
    treatment: ['SSRIs/SNRIs (first line)', 'Cognitive behavioral therapy', 'Benzodiazepines (short-term)', 'Exposure therapy', 'Breathing techniques'],
    description: 'A disorder of recurrent unexpected panic attacks with persistent worry about future attacks.',
  },
  'Obsessive-Compulsive Disorder': {
    category: 'psychiatry',
    name: 'Obsessive-Compulsive Disorder (OCD)',
    symptoms: ['Recurrent intrusive thoughts (obsessions)', 'Repetitive behaviors (compulsions)', 'Checking rituals', 'Cleaning behaviors', 'Symmetry/counting needs', 'Distress if rituals prevented'],
    causes: ['Genetic factors', 'Cortico-striatal circuit dysfunction', 'Serotonin dysregulation', 'Streptococcal infection association'],
    treatment: ['SSRIs (high dose)', 'Exposure and response prevention (ERP)', 'Cognitive behavioral therapy', 'Clomipramine', 'Deep brain stimulation (severe)'],
    description: 'A chronic disorder of intrusive obsessions and repetitive compulsions performed to reduce anxiety.',
  },
  'Post-Traumatic Stress Disorder': {
    category: 'psychiatry',
    name: 'Post-Traumatic Stress Disorder (PTSD)',
    symptoms: ['Re-experiencing (flashbacks, nightmares)', 'Avoidance of reminders', 'Hyperarousal (hypervigilance, startle)', 'Irritability', 'Sleep disturbance', 'Emotional numbness', 'Negative thoughts'],
    causes: ['Traumatic events', 'Combat exposure', 'Sexual/physical assault', 'Accidents/disasters', 'Lack of social support'],
    treatment: ['Trauma-focused cognitive behavioral therapy', 'EMDR', 'SSRIs (Sertraline, Paroxetine)', 'Prazosin (nightmares)', 'Prolonged exposure therapy'],
    description: 'A disorder of persistent re-experiencing, avoidance, and hyperarousal following exposure to trauma.',
  },
  Schizophrenia: {
    category: 'psychiatry',
    name: 'Schizophrenia',
    symptoms: ['Hallucinations (auditory)', 'Delusions', 'Disorganized speech', 'Disorganized behavior', 'Negative symptoms (social withdrawal, flat affect)', 'Cognitive impairment'],
    causes: ['Genetic predisposition', 'Dopamine dysregulation', 'Prenatal complications', 'Stressful events', 'Cannabis use (risk factor)'],
    treatment: ['Antipsychotics (first/second generation)', 'Psychosocial rehabilitation', 'Cognitive behavioral therapy', 'Family education', 'Social skills training'],
    description: 'A chronic psychotic disorder characterized by hallucinations, delusions, disorganized thinking, and negative symptoms.',
  },
  'Attention Deficit Hyperactivity Disorder': {
    category: 'psychiatry',
    name: 'Attention Deficit Hyperactivity Disorder (ADHD)',
    symptoms: ['Inattention', 'Hyperactivity', 'Impulsivity', 'Difficulty organizing tasks', 'Losing items', 'Interrupting', 'Fidgeting'],
    causes: ['Genetic predisposition', 'Dopamine/norepinephrine dysfunction', 'Prenatal exposures', 'Preterm birth', 'Environmental factors'],
    treatment: ['Stimulants (Methylphenidate, Amphetamines)', 'Non-stimulants (Atomoxetine)', 'Behavioral therapy', 'Parent training', 'Educational support'],
    description: 'A neurodevelopmental disorder of inattention, hyperactivity, and impulsivity affecting function across settings.',
  },
  'Autism Spectrum Disorder': {
    category: 'psychiatry',
    name: 'Autism Spectrum Disorder',
    symptoms: ['Social communication difficulties', 'Restricted interests', 'Repetitive behaviors', 'Sensory sensitivities', 'Difficulty with changes', 'Delayed speech'],
    causes: ['Genetic factors', 'Combination of genes and environment', 'Advanced parental age'],
    treatment: ['Applied behavior analysis (ABA)', 'Speech therapy', 'Occupational therapy', 'Social skills training', 'Educational support', 'Co-occurring condition management'],
    description: 'A neurodevelopmental disorder of social communication differences and restricted, repetitive patterns of behavior.',
  },
  'Anorexia Nervosa': {
    category: 'psychiatry',
    name: 'Anorexia Nervosa',
    symptoms: ['Restrictive eating', 'Intense fear of weight gain', 'Distorted body image', 'Severe weight loss', 'Amenorrhea', 'Lanugo hair', 'Bradycardia', 'Hypotension'],
    causes: ['Genetic predisposition', 'Perfectionism', 'Societal pressure', 'Psychological factors', 'Family dynamics'],
    treatment: ['Family-based therapy (adolescents)', 'Nutritional rehabilitation', 'Psychological therapy', 'Medical monitoring', 'Weight restoration'],
    description: 'A serious eating disorder of restrictive eating and fear of weight gain with high medical and psychiatric comorbidity.',
  },
  'Bulimia Nervosa': {
    category: 'psychiatry',
    name: 'Bulimia Nervosa',
    symptoms: ['Binge eating episodes', 'Purging (vomiting, laxatives)', 'Secretive eating', 'Dental erosion', 'Electrolyte imbalance', 'Gastrointestinal symptoms'],
    causes: ['Genetic factors', 'Body dissatisfaction', 'Impulsivity', 'Societal pressures', 'Co-occurring mood disorder'],
    treatment: ['Cognitive behavioral therapy (CBT)', 'Nutritional counseling', 'SSRIs', 'Monitoring electrolytes', 'Binge-eating management'],
    description: 'An eating disorder of recurrent binge eating followed by inappropriate compensatory behaviors to prevent weight gain.',
  },
  'Substance Use Disorder': {
    category: 'psychiatry',
    name: 'Substance Use Disorder',
    symptoms: ['Craving', 'Loss of control over use', 'Tolerance', 'Withdrawal symptoms', 'Neglect of responsibilities', 'Continued use despite harm'],
    causes: ['Genetic predisposition', 'Dopamine reward pathway', 'Stress/trauma', 'Peer pressure', 'Mental illness comorbidity'],
    treatment: ['Detoxification protocols', 'Medications (buprenorphine, naltrexone)', 'Psychotherapy', '12-step programs', 'Relapse prevention'],
    description: 'A chronic brain disorder of compulsive substance use despite harmful consequences, with tolerance and withdrawal.',
  },
  'Alcohol Use Disorder': {
    category: 'psychiatry',
    name: 'Alcohol Use Disorder',
    symptoms: ['Craving alcohol', 'Loss of control', 'Tolerance', 'Withdrawal (tremor, sweating, seizures)', 'Neglect of roles', 'Continued drinking despite harm'],
    causes: ['Genetic predisposition', 'Dopamine and GABA system effects', 'Stress', 'Mental health comorbidity', 'Social environment'],
    treatment: ['Medications (Naltrexone, Acamprosate, Disulfiram)', 'Behavioral therapy', 'Medical detoxification', 'Support groups', 'Treat comorbid conditions'],
    description: 'A pattern of alcohol use causing clinically significant impairment or distress, including dependence and withdrawal.',
  },
  'Insomnia Disorder': {
    category: 'psychiatry',
    name: 'Insomnia Disorder',
    symptoms: ['Difficulty falling asleep', 'Difficulty staying asleep', 'Early awakening', 'Daytime fatigue', 'Impaired concentration', 'Irritability'],
    causes: ['Stress', 'Anxiety/depression', 'Poor sleep hygiene', 'Chronic pain', 'Medications', 'Substance use', 'Shift work'],
    treatment: ['Cognitive behavioral therapy for insomnia (CBT-I)', 'Sleep hygiene', 'Stimulus control', 'Short-term sleep aids', 'Treat underlying conditions'],
    description: 'A sleep disorder of persistent difficulty initiating or maintaining sleep despite opportunity, with daytime consequences.',
  },
  'Panic Attacks (Recurrent)': {
    category: 'psychiatry',
    name: 'Recurrent Panic Attacks',
    symptoms: ['Sudden intense fear', 'Palpitations', 'Shortness of breath', 'Dizziness', 'Trembling', 'Chest tightness', 'Fear of collapsing', 'Sense of doom'],
    causes: ['Stressful triggers', 'Hyperventilation', 'Caffeine', 'Anxiety sensitivity', 'Life transitions'],
    treatment: ['Cognitive behavioral therapy', 'SSRIs', 'Breathing retraining', 'Exposure therapy', 'Lifestyle modification'],
    description: 'Recurrent episodes of intense fear with somatic symptoms, causing functional impairment and anticipatory anxiety.',
  },
  'Borderline Personality Disorder': {
    category: 'psychiatry',
    name: 'Borderline Personality Disorder',
    symptoms: ['Emotional instability', 'Fear of abandonment', 'Unstable relationships', 'Impulsive behavior', 'Self-harm', 'Identity disturbance', 'Chronic emptiness'],
    causes: ['Genetic factors', 'Childhood trauma', 'Invalidating environment', 'Neurobiological factors'],
    treatment: ['Dialectical behavior therapy (DBT)', 'Mentalization-based therapy', 'Cognitive behavioral therapy', 'Mood stabilization (selected)', 'Crisis management'],
    description: 'A personality disorder of pervasive instability in mood, relationships, self-image, and behavior.',
  },
  'Antisocial Personality Disorder': {
    category: 'psychiatry',
    name: 'Antisocial Personality Disorder',
    symptoms: ['Disregard for others rights', 'Impulsivity', 'Lack of remorse', 'Irresponsibility', 'Violation of rules/law', 'Deceitfulness', 'Aggression'],
    causes: ['Genetic predisposition', 'Childhood conduct disorder', 'Adverse childhood experiences', 'Environmental factors'],
    treatment: ['Cognitive behavioral therapy', 'Contingency management', 'Treat comorbid substance use', 'Social skills training', 'Behavioral interventions'],
    description: 'A personality disorder of pervasive disregard for and violation of the rights of others beginning in childhood or adolescence.',
  },
  'Seasonal Affective Disorder': {
    category: 'psychiatry',
    name: 'Seasonal Affective Disorder',
    symptoms: ['Depression in autumn/winter', 'Hypersomnia', 'Increased appetite', 'Carbohydrate cravings', 'Weight gain', 'Low energy', 'Social withdrawal'],
    causes: ['Reduced sunlight exposure', 'Melatonin dysregulation', 'Serotonin changes', 'Circadian rhythm disruption', 'Geographic location'],
    treatment: ['Light therapy', 'SSRIs', 'Cognitive behavioral therapy', 'Vitamin D supplementation', 'Exercise', 'Regular sleep schedule'],
    description: 'A type of depression occurring in a seasonal pattern, typically with onset in autumn or winter.',
  },
  'Delirium': {
    category: 'psychiatry',
    name: 'Delirium',
    symptoms: ['Acute confusion', 'Fluctuating consciousness', 'Inattention', 'Hallucinations', 'Agitation/lethargy', 'Disorganized thinking', 'Sleep-wake disruption'],
    causes: ['Infection', 'Metabolic derangements', 'Medications', 'Alcohol/drug withdrawal', 'Surgery', 'Hospitalization', 'Hypoxia'],
    treatment: ['Treat underlying cause', 'Reorientation (clock, family)', 'Minimize sedatives', 'Antipsychotics (low dose if agitated)', 'Non-pharmacologic measures'],
    description: 'An acute, fluctuating disturbance in attention and consciousness, usually due to an underlying medical condition.',
  },
  'Adaptation Disorder': {
    category: 'psychiatry',
    name: 'Adjustment Disorder',
    symptoms: ['Emotional distress after stressor', 'Mood disturbance', 'Anxiety', 'Behavioral changes', 'Sleep problems', 'Impaired function'],
    causes: ['Major life stressors', 'Relationship problems', 'Financial difficulties', 'Work stressors', 'Loss and grief'],
    treatment: ['Psychotherapy', 'Supportive counseling', 'Stress management', 'Short-term medication (selected)', 'Coping strategies'],
    description: 'Emotional or behavioral symptoms developing in response to an identifiable stressor, within 3 months of onset.',
  },
  'Bipolar II Disorder': {
    category: 'psychiatry',
    name: 'Bipolar II Disorder',
    symptoms: ['Hypomanic episodes', 'Major depressive episodes', 'Increased energy (hypomania)', 'Impulsivity (less severe)', 'Mood instability', 'Anxiety'],
    causes: ['Genetic predisposition', 'Neurotransmitter imbalance', 'Stressful events', 'Substance use'],
    treatment: ['Mood stabilizers (Lamotrigine, Lithium)', 'Careful antidepressant use', 'Psychotherapy', 'Sleep stabilization', 'Mood tracking'],
    description: 'A mood disorder with episodes of hypomania and major depression, without full manic episodes.',
  },
};