import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART14: Record<string, DiseaseInfo> = {
  'Normal Pregnancy': {
    category: 'obgyn',
    name: 'Normal Pregnancy',
    symptoms: ['Amenorrhea', 'Nausea/vomiting (early)', 'Breast tenderness', 'Fatigue', 'Urinary frequency', 'Fetal movements', 'Weight gain'],
    causes: ['Conception and implantation', 'Fetal development', 'Physiologic adaptation'],
    treatment: ['Prenatal care', 'Folic acid supplementation', 'Prenatal vitamins', 'Gestational age dating', 'Antenatal screening', 'Delivery planning'],
    description: 'A physiologic gestation of approximately 40 weeks characterized by maternal adaptation and fetal development.',
  },
  Preeclampsia: {
    category: 'obgyn',
    name: 'Preeclampsia',
    symptoms: ['New-onset hypertension', 'Proteinuria', 'Edema (face/hands)', 'Headache', 'Visual disturbances', 'Epigastric pain', 'Rapid weight gain'],
    causes: ['Placental dysfunction', 'Angiogenic imbalance', 'Immune maladaptation', 'First pregnancy', 'Prior preeclampsia', 'Renal disease', 'Obesity'],
    treatment: ['Delivery (definitive)', 'Blood pressure control (labetalol, nifedipine)', 'Magnesium sulfate (seizure prophylaxis)', 'Antenatal corticosteroids (preterm)', 'Antenatal surveillance', 'Severe: urgent delivery'],
    description: 'A hypertensive disorder of pregnancy with proteinuria and end-organ effects, a leading cause of maternal morbidity.',
  },
  Eclampsia: {
    category: 'obgyn',
    name: 'Eclampsia',
    symptoms: ['Generalized seizures', 'Hypertension', 'Headache', 'Visual disturbance', 'Preceding preeclampsia', 'Posterior reversible encephalopathy'],
    causes: ['Severe preeclampsia progression', 'Cerebral vasospasm/edema', 'Delivery usually resolves'],
    treatment: ['Magnesium sulfate (urgent)', 'Blood pressure control', 'Delivery planning', 'Anti-seizure protocol', 'ICU monitoring', 'Recurrence risk counseling'],
    description: 'New-onset grand-mal seizures in preeclampsia, a life-threatening obstetric emergency.',
  },
  'Gestational Hypertension': {
    category: 'obgyn',
    name: 'Gestational Hypertension',
    symptoms: ['New-onset hypertension', 'Often asymptomatic', 'Mild edema', 'Not meeting preeclampsia criteria'],
    causes: ['Placental vascular changes', 'Maternal predisposition', 'First pregnancy', 'Multiple gestation'],
    treatment: ['Blood pressure monitoring', 'Antenatal surveillance', 'Antihypertensives (severe)', 'Delivery at term', 'Monitor for preeclampsia progression'],
    description: 'Hypertension arising after 20 weeks gestation without proteinuria or end-organ dysfunction.',
  },
  'Ectopic Pregnancy': {
    category: 'obgyn',
    name: 'Ectopic Pregnancy',
    symptoms: ['Pelvic pain', 'Vaginal bleeding (spotting)', 'Amenorrhea (missed period)', 'Shoulder tip pain (rupture)', 'Dizziness/syncope', 'Cervical motion tenderness'],
    causes: ['Fallopian tube damage', 'Prior ectopic', 'Pelvic infection', 'IUD in situ', 'Assisted reproduction', 'Tubal surgery'],
    treatment: ['Methotrexate (early, stable)', 'Salpingectomy/salpingostomy (surgery)', 'Expectant management (selected)', 'Serial hCG monitoring', 'Emergency surgery (rupture)', 'Rh immunoglobulin (if Rh negative)'],
    description: 'Implantation of the embryo outside the uterine cavity, most often the fallopian tube, a surgical emergency when ruptured.',
  },
  'Placenta Previa': {
    category: 'obgyn',
    name: 'Placenta Previa',
    symptoms: ['Painless vaginal bleeding (3rd trimester)', 'Bright red bleeding', 'Often asymptomatic until bleeding', 'Abnormal fetal position'],
    causes: ['Low placental implantation', 'Prior cesarean', 'Prior uterine surgery', 'Multiple pregnancy', 'Advanced maternal age', 'Smoking'],
    treatment: ['Pelvic rest', 'Antenatal corticosteroids', 'Serial ultrasound', 'Cesarean delivery (planned)', 'Blood products availability', 'Avoid vaginal examination'],
    description: 'Implantation of the placenta over or near the cervical os causing painless third-trimester bleeding.',
  },
  'Placental Abruption': {
    category: 'obgyn',
    name: 'Placental Abruption',
    symptoms: ['Painful vaginal bleeding', 'Abdominal/back pain', 'Uterine tenderness', 'Hypertonic uterus', 'Fetal distress', 'Shock (severe)'],
    causes: ['Hypertension', 'Trauma', 'Cocaine use', 'Short umbilical cord', 'Uterine overdistension', 'Prior abruption'],
    treatment: ['Immediate delivery', 'Fetal monitoring', 'Resuscitation', 'Blood products', 'Manage coagulopathy (DIC)', 'Emergency cesarean often'],
    description: 'Premature separation of the placenta from the uterine wall, an obstetric emergency with fetal and maternal risk.',
  },
  'Miscarriage': {
    category: 'obgyn',
    name: 'Spontaneous Abortion (Miscarriage)',
    symptoms: ['Vaginal bleeding', 'Abdominal cramping (lower)', 'Passage of tissue', 'Loss of pregnancy symptoms', 'Cervical os findings'],
    causes: ['Chromosomal abnormalities (most)', 'Maternal age', 'Uterine anomalies', 'Endocrine disorders', 'Infections', 'Thrombophilia'],
    treatment: ['Expectant management', 'Misoprostol (medical)', 'Curettage/D&C (surgical)', 'Rh immunoglobulin (Rh negative)', 'Grief support', 'Recurrent loss workup'],
    description: 'Spontaneous loss of pregnancy before viability, most commonly from chromosomal abnormalities.',
  },
  'Polycystic Ovary Syndrome': {
    category: 'obgyn',
    name: 'Polycystic Ovary Syndrome (PCOS)',
    symptoms: ['Irregular menses (oligomenorrhea)', 'Hirsutism', 'Acne', 'Obesity', 'Infertility', 'Insulin resistance', 'Polycystic ovaries on ultrasound'],
    causes: ['Hyperandrogenism', 'Insulin resistance', 'Luteinizing hormone excess', 'Genetic predisposition'],
    treatment: ['Lifestyle modification and weight loss', 'Combined oral contraceptives (cycle regulation)', 'Metformin (insulin resistance)', 'Anti-androgens (hirsutism)', 'Ovulation induction (letrozole/clomiphene)', 'Long-term metabolic monitoring'],
    description: 'A common endocrine-metabolic disorder of women characterized by androgen excess, ovulatory dysfunction, and polycystic ovaries.',
  },
  Endometriosis: {
    category: 'obgyn',
    name: 'Endometriosis',
    symptoms: ['Chronic pelvic pain', 'Painful periods (dysmenorrhea)', 'Pain with intercourse (dyspareunia)', 'Infertility', 'Heavy bleeding', 'Pain with defecation/urination'],
    causes: ['Retrograde menstruation', 'Estrogen-dependent implants', 'Genetic predisposition', 'Hormonal factors'],
    treatment: ['NSAIDs (pain)', 'Hormonal therapy (OCPs, progestins, GnRH agonists)', 'Surgical excision/ablation', 'Infertility treatment', 'Hysterectomy (selected)', 'Pain management (multidisciplinary)'],
    description: 'Growth of endometrial-like tissue outside the uterus causing chronic pain and infertility.',
  },
  'Uterine Fibroids': {
    category: 'obgyn',
    name: 'Uterine Fibroids (Leiomyomas)',
    symptoms: ['Heavy/prolonged menstrual bleeding', 'Pelvic pressure/pain', 'Bloating', 'Urinary frequency', 'Constipation', 'Fertility effects', 'Often asymptomatic'],
    causes: ['Estrogen-sensitive smooth muscle growth', 'Genetic factors (HIF/receptor mutations)', 'Obesity', 'Age (childbearing)'],
    treatment: ['Observation (asymptomatic)', 'Tranexamic acid (bleeding)', 'Hormonal therapy (GnRH agonists)', 'Uterine artery embolization', 'Myomectomy', 'Hysterectomy (definitive)'],
    description: 'Benign smooth muscle tumors of the uterus, common in reproductive-age women.',
  },
  'Pelvic Inflammatory Disease': {
    category: 'obgyn',
    name: 'Pelvic Inflammatory Disease (PID)',
    symptoms: ['Lower abdominal pain', 'Abnormal vaginal discharge', 'Fever', 'Cervical motion tenderness', 'Adnexal tenderness', 'Dyspareunia', 'Irregular bleeding'],
    causes: ['Chlamydia trachomatis', 'Neisseria gonorrhoeae', 'Ascending infection', 'Multiple partners', 'IUD insertion (few weeks)', 'Prior PID'],
    treatment: ['Antibiotics (ceftriaxone + doxycycline)', 'Outpatient vs inpatient regimens', 'Pain management', 'Partner treatment', 'STI screening', 'Fertility follow-up'],
    description: 'Infection of the upper female genital tract with serious reproductive consequences (infertility, ectopic risk).',
  },
  'Postpartum Hemorrhage': {
    category: 'obgyn',
    name: 'Postpartum Hemorrhage',
    symptoms: ['Excessive vaginal bleeding (>500 ml vaginal / >1000 ml cesarean)', 'Hypotension', 'Tachycardia', 'Pallor', 'Shock', 'Oozing/uterine atony'],
    causes: ['Uterine atony (most common)', 'Retained placenta', 'Genital tract trauma/laceration', 'Coagulopathy', 'Placenta accreta'],
    treatment: ['Uterine massage', 'Oxytocin', 'Methylergonovine/carboprost (refractory)', 'Tranexamic acid', 'Balloon tamponade', 'B-lynch suture/hysterectomy', 'Blood transfusion'],
    description: 'Bleeding >500-1000 mL after delivery, a leading cause of maternal death, usually from uterine atony.',
  },
  'Preterm Labor': {
    category: 'obgyn',
    name: 'Preterm Labor',
    symptoms: ['Regular uterine contractions', 'Cervical change <37 weeks', 'Pelvic pressure', 'Low back pain', 'Change in discharge', 'Watery leakage (rupture of membranes)'],
    causes: ['Infection (chorioamnionitis)', 'Multiple pregnancy', 'Uterine overdistension', 'Cervical insufficiency', 'Placental abruption', 'Stress'],
    treatment: ['Antenatal corticosteroids (lung maturity)', 'Nifedipine/atosiban (tocolytic)', 'Magnesium sulfate (neuroprotection)', 'Antibiotics (PPROM)', 'Transfer to tertiary center', 'Tocolytic contraindications'],
    description: 'Labor occurring before 37 weeks gestation, managed to delay delivery and reduce prematurity complications.',
  },
  'Gestational Trophoblastic Disease': {
    category: 'obgyn',
    name: 'Gestational Trophoblastic Disease',
    symptoms: ['Vaginal bleeding in pregnancy', 'Severe nausea/vomiting', 'Uterus larger than dates', 'Preeclampsia (early)', 'Absent fetal heart', 'Elevated hCG'],
    causes: ['Abnormal trophoblast proliferation', 'Complete mole (androgenetic)', 'Partial mole', 'Choriocarcinoma (malignant)'],
    treatment: ['Suction curettage', 'Serial hCG monitoring', 'Chemotherapy (malignant variants)', 'Contraception during surveillance', 'Staging for persistent disease'],
    description: 'A spectrum of trophoblastic neoplasms, most often hydatidiform mole with risk of malignant transformation.',
  },
  'Mastitis': {
    category: 'obgyn',
    name: 'Breast Mastitis (Lactational)',
    symptoms: ['Fever', 'Breast pain/tenderness', 'Erythema (wedge-shaped)', 'Swelling', 'Malaise', 'Nipple fissure'],
    causes: ['Staphylococcus aureus (milk stasis + infection)', 'Lactation', 'Cracked nipples', 'Blocked duct', 'Poor breastfeeding technique'],
    treatment: ['Antibiotics (dicloxacillin/cephalexin)', 'Continue/pump milk', 'Warm compresses and massage', 'Analgesia', 'Frequent feeding/emptying', 'Abscess (if): drainage'],
    description: 'Inflammation/infection of the breast, usually during lactation, with milk stasis and bacterial infection.',
  },
  'Ovarian Cyst': {
    category: 'obgyn',
    name: 'Ovarian Cyst (Functional)',
    symptoms: ['Often asymptomatic', 'Pelvic pain (midcycle)', 'Bloating', 'Pressure', 'Menstrual irregularity', 'Torsion: acute severe pain'],
    causes: ['Physiologic follicle cysts (follicular/luteal)', 'Hormonal cycle', 'Ovulation'],
    treatment: ['Observation (resolve spontaneously)', 'Analgesia', 'OCPs (suppression, selected)', 'Serial ultrasound', 'Surgery (large, complex, torsion)'],
    description: 'Fluid-filled sacs on the ovary, usually functional and benign, often resolving spontaneously.',
  },
  'Menopause': {
    category: 'obgyn',
    name: 'Menopause',
    symptoms: ['Amenorrhea (12 months)', 'Hot flashes', 'Night sweats', 'Vaginal dryness', 'Sleep disturbance', 'Mood changes', 'Urinary symptoms'],
    causes: ['Ovarian follicle depletion', 'Age (usually 45-55)', 'Surgical menopause', 'Premature ovarian failure'],
    treatment: ['Hormone replacement therapy (selected)', 'Non-hormonal treatments (SSNRI)', 'Lubricants/moisturizers', 'Lifestyle modifications', 'Bone health monitoring', 'Vasomotor symptom management'],
    description: 'The permanent cessation of menstruation due to ovarian follicular loss, with vasomotor and genitourinary symptoms.',
  },
  'Cervical Incompetence': {
    category: 'obgyn',
    name: 'Cervical Insufficiency',
    symptoms: ['Painless cervical dilation mid-trimester', 'History of mid-trimester loss', 'Vaginal pressure', 'Mucous discharge change'],
    causes: ['Congenital cervical weakness', 'Prior cervical surgery (LLETZ, cone)', 'Cervical trauma', 'Uterine anomalies'],
    treatment: ['Cervical cerclage (pregnancy)', 'Progesterone supplementation', 'Serial cervical length ultrasound', 'Activity restrictions (selected)', 'Prevention of recurrent preterm birth'],
    description: 'Painless, non-labor cervical shortening/dilation in the second trimester leading to pregnancy loss.',
  },
  'Amniotic Fluid Embolism': {
    category: 'obgyn',
    name: 'Amniotic Fluid Embolism',
    symptoms: ['Sudden dyspnea', 'Cyanosis', 'Cardiovascular collapse', 'Hypotension', 'Seizures', 'Consumptive coagulopathy (DIC)', 'Cardiac arrest during labor/postpartum'],
    causes: ['Amniotic fluid/fetal material enters maternal circulation', 'Intrapartum', 'Rare but catastrophic'],
    treatment: ['Immediate resuscitation', 'Cardiopulmonary support', 'Blood products/coagulation support', 'ICU care', 'Emergency delivery (in utero arrest)', 'Survival with early support'],
    description: 'A rare, catastrophic obstetric emergency of sudden cardiovascular collapse from amniotic fluid embolism.',
  },
};