import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART12: Record<string, DiseaseInfo> = {
  'Atopic Dermatitis (Eczema)': {
    category: 'dermatology',
    name: 'Atopic Dermatitis (Eczema)',
    symptoms: ['Intense itching', 'Erythematous plaques', 'Flexural involvement (creases)', 'Dry skin', 'Weeping/oozing (acute)', 'Lichenification (chronic)'],
    causes: ['Skin barrier dysfunction (filaggrin)', 'Immune dysregulation', 'Genetic predisposition', 'Environmental allergens', 'Family history of atopy'],
    treatment: ['Emollients (regular moisturizing)', 'Topical corticosteroids', 'Topical calcineurin inhibitors', 'Antihistamines (itch)', 'Trigger avoidance', 'Biologics (Dupilumab, severe)'],
    description: 'A chronic inflammatory skin condition of intense pruritus and eczematous lesions, common in childhood.',
  },
  Psoriasis: {
    category: 'dermatology',
    name: 'Psoriasis',
    symptoms: ['Well-demarcated erythematous plaques', 'Silver scale', 'Extensor surfaces (elbows, knees)', 'Scalp involvement', 'Nail pitting', 'Koebner phenomenon', 'Itching'],
    causes: ['Autoimmune keratinocyte hyperproliferation', 'Genetic predisposition', 'Stress', 'Infections (streptococcal)', 'Medications (lithium, beta-blockers)'],
    treatment: ['Topical corticosteroids', 'Vitamin D analogs (Calcipotriene)', 'Phototherapy (UVB)', 'Systemic therapy (Methotrexate)', 'Biologics (TNF, IL-17, IL-23)', 'Medicated shampoos (scalp)'],
    description: 'A chronic autoimmune skin disease of rapid keratinocyte turnover with characteristic scaly plaques.',
  },
  AcneVulgaris: {
    category: 'dermatology',
    name: 'Acne Vulgaris',
    symptoms: ['Comedones (blackheads, whiteheads)', 'Papules', 'Pustules', 'Nodules/cysts (severe)', 'Scarring', 'Face/back/chest involvement'],
    causes: ['Hormonal stimulation of sebaceous glands', 'Follicular hyperkeratinization', 'Propionibacterium (C. acnes)', 'Inflammation', 'Genetics'],
    treatment: ['Benzoyl peroxide', 'Topical retinoids', 'Topical antibiotics (clindamycin)', 'Oral antibiotics (doxycycline)', 'Hormonal therapy (women)', 'Isotretinoin (severe)'],
    description: 'A common skin condition of pilosebaceous unit inflammation causing comedones, papules, and pustules.',
  },
  Rosacea: {
    category: 'dermatology',
    name: 'Rosacea',
    symptoms: ['Facial flushing', 'Erythema (central face)', 'Telangiectasias', 'Papules/pustules', 'Burning sensation', 'Ocular involvement (dry, gritty eyes)'],
    causes: ['Vascular dysregulation', 'Hair follicle mites (Demodex)', 'Trigger factors (alcohol, spicy food, heat)', 'Genetic predisposition'],
    treatment: ['Avoid triggers', 'Topical metronidazole/azelaic acid', 'Oral antibiotics (doxycycline, low dose)', 'Brimonidine gel (erythema)', 'Laser therapy (telangiectasias)', 'Ocular care'],
    description: 'A chronic facial skin condition of flushing, erythema, and inflammatory papules, typically in adults.',
  },
  'Contact Dermatitis': {
    category: 'dermatology',
    name: 'Contact Dermatitis',
    symptoms: ['Localized erythema', 'Itching', 'Vesicles/bullae (acute)', 'Burning', 'Crusting (eczematous)', 'Site corresponds to exposure'],
    causes: ['Irritants (soaps, chemicals)', 'Allergens (nickel, poison ivy, latex)', 'Occupational exposures', 'Cosmetics'],
    treatment: ['Avoid causative agent', 'Topical corticosteroids', 'Antihistamines', 'Cool compresses', 'Barrier creams', 'Severe: systemic steroids'],
    description: 'Skin inflammation from direct contact with an irritant or allergen causing localized dermatitis.',
  },
  'Seborrheic Dermatitis': {
    category: 'dermatology',
    name: 'Seborrheic Dermatitis',
    symptoms: ['Greasy yellow scaling', 'Erythema', 'Scalp, face (eyebrows, nasolabial)', 'Itching', 'Dandruff', 'Recurs'],
    causes: ['Malassezia yeast', 'Sebaceous gland activity', 'Stress', 'Immunosuppression (HIV)', 'Parkinson disease (association)'],
    treatment: ['Ketoconazole shampoo', 'Selenium sulfide', 'Topical steroids (face)', 'Antifungal creams', 'Salicylic acid', 'Regular maintenance'],
    description: 'A chronic inflammatory scaling dermatosis affecting seborrheic areas (scalp, face, trunk).',
  },
  Urticaria: {
    category: 'dermatology',
    name: 'Urticaria (Hives)',
    symptoms: ['Wheals (elevated erythematous)', 'Intense itching', 'Individual lesions <24 hours', 'Angioedema (lips/eyes) in severe', 'Migratory lesions'],
    causes: ['Mast cell histamine release', 'Allergies (food, drugs)', 'Infection', 'Physical (cold, pressure, heat)', 'Stress', 'Idiopathic'],
    treatment: ['Antihistamines (H1)', 'Avoid triggers', 'H2 blockers (adjunct)', 'Oral corticosteroids (severe/short)', 'Epinephrine (anaphylaxis)', 'Leukotriene modifiers'],
    description: 'A condition of itchy transient wheals from mast cell degranulation, acute or chronic.',
  },
  'Cutaneous Fungal Infection': {
    category: 'dermatology',
    name: 'Dermatophytosis (Ringworm)',
    symptoms: ['Annular scaly plaque with central clearing', 'Itching', 'Ring-like border', 'Tinea corporis/cruris/pedis', 'Skin scaling'],
    causes: ['Dermatophytes (Trichophyton, Microsporum)', 'Direct skin contact', 'Warm moist environments', 'Shared towels/footwear'],
    treatment: ['Topical antifungals (azole, terbinafine)', 'Oral terbinafine (extensive)', 'Keep skin dry', 'Avoid sharing towels', 'Treat infected contacts/pets'],
    description: 'Superficial fungal infections of skin, hair, and nails (tinea infections).',
  },
  'Basal Cell Carcinoma': {
    category: 'dermatology',
    name: 'Basal Cell Carcinoma',
    symptoms: ['Pearl-like (waxy) nodule', 'Telangiectasias on surface', 'Rolled borders', 'Central ulceration (rodent ulcer)', 'Slow growth', 'Sun-exposed areas'],
    causes: ['UV radiation', 'Light skin type', 'Chronic sun exposure', 'Age'],
    treatment: ['Surgical excision', 'Mohs micrographic surgery (cosmetic areas)', 'Curettage/electrocautery', 'Cryotherapy', 'Radiation (elderly, selected)', 'Surveillance'],
    description: 'The most common skin cancer, locally invasive but virtually never metastasizing.',
  },
  'Squamous Cell Carcinoma': {
    category: 'dermatology',
    name: 'Squamous Cell Carcinoma (Skin)',
    symptoms: ['Scaly erythematous keratotic plaque', 'Non-healing ulcer', 'Hard nodule', 'Crusting', 'Metastatic potential (higher than BCC)'],
    causes: ['Chronic UV exposure', 'Actinic keratosis progression', 'Immunosuppression', 'HPV (selected sites)', 'Chronic scars/ulcers'],
    treatment: ['Surgical excision', 'Mohs surgery', 'Radiation therapy', 'Cryotherapy (premalignant)', 'Local/systemic therapy (advanced)'],
    description: 'A keratinocyte skin cancer with risk of local invasion and lymph node metastasis.',
  },
  'Psoriasis (Guttate)': {
    category: 'dermatology',
    name: 'Guttate Psoriasis',
    symptoms: ['Sudden small drop-shaped lesions', 'Trunk/extremities', 'Fine scale', 'Erythematous papules', 'Often after strep throat'],
    causes: ['Streptococcal pharyngitis trigger', 'Autoimmune reaction', 'Genetic predisposition'],
    treatment: ['Treat strep infection', 'Topical corticosteroids', 'Phototherapy', 'Emollients', 'Watchful waiting (self-limiting)'],
    description: 'An acute eruptive form of psoriasis, frequently triggered by streptococcal infection in young patients.',
  },
  'Herpes Simplex (Skin)': {
    category: 'dermatology',
    name: 'Herpetic Skin Infection',
    symptoms: ['Clustered vesicles', 'Erythematous base', 'Burning/tingling prodrome', 'Painful lesions', 'Crusting after rupture'],
    causes: ['HSV-1/HSV-2', 'Direct contact', 'Immunosuppression', 'Sun exposure (triggers)'],
    treatment: ['Acyclovir/Valacyclovir (oral)', 'Topical antiviral', 'Pain management', 'Suppressive therapy (recurrent)', 'Avoid spread'],
    description: 'Cutaneous infection with herpes simplex virus causing characteristic grouped vesicles.',
  },
  'Scabies': {
    category: 'dermatology',
    name: 'Scabies',
    symptoms: ['Intense pruritus (worse at night)', 'Burrows (curvilinear tracks)', 'Web spaces, wrists, genitalia', 'Papules/vesicles', 'Contact history'],
    causes: ['Sarcoptes scabiei mite', 'Prolonged skin contact', 'Bedding/close contact spread'],
    treatment: ['Permethrin cream (5%)', 'Ivermectin (oral)', 'Treat all contacts simultaneously', 'Wash bedding/clothes', 'Antihistamines (itch)'],
    description: 'A highly contagious skin infestation by mites creating burrows and intense itching.',
  },
  'Lice Infestation': {
    category: 'dermatology',
    name: 'Pediculosis (Lice)',
    symptoms: ['Scalp/body itching', 'Visible nits (eggs) on hair shafts', 'Small erythematous bites', 'Fever (body lice)', 'Secondary skin infection'],
    causes: ['Head/body/pubis lice', 'Direct contact', 'Shared hats/combs/bedding'],
    treatment: ['Permethrin lotion', 'Wet combing', 'Wash linens (hot)', 'Family/contact treatment', 'Prophylaxis of close contacts'],
    description: 'Infestation with lice causing pruritus and visible nits predominantly on hair-bearing areas.',
  },
  'Vitiligo': {
    category: 'dermatology',
    name: 'Vitiligo',
    symptoms: ['Depigmented white macules/patches', 'Symmetrical distribution', 'Periorificial involvement', 'Hair depigmentation (poliosis)', 'Areas of trauma (Koebner)'],
    causes: ['Autoimmune melanocyte destruction', 'Genetic predisposition', 'Autoimmune disease association (thyroid)'],
    treatment: ['Topical corticosteroids', 'Topical calcineurin inhibitors', 'Phototherapy (NB-UVB)', 'Excimer laser', 'Camouflage cosmetics', 'Depigmentation (extensive)'],
    description: 'An autoimmune skin disorder of melanocyte loss causing well-demarcated depigmented patches.',
  },
  'Alopecia Areata': {
    category: 'dermatology',
    name: 'Alopecia Areata',
    symptoms: ['Sudden patchy hair loss', 'Smooth bald patches', 'Exclamation mark hairs', 'Nail pitting', 'May progress to totalis'],
    causes: ['Autoimmune attack on hair follicle', 'Genetic predisposition', 'Stress triggers', 'Associated autoimmunity'],
    treatment: ['Intralesional corticosteroids', 'Topical minoxidil', 'Contact immunotherapy', 'JAK inhibitors (emerging)', 'Psychological support'],
    description: 'A non-scarring autoimmune hair loss disorder with sudden round patches of alopecia.',
  },
  'Hidradenitis Suppurativa': {
    category: 'dermatology',
    name: 'Hidradenitis Suppurativa',
    symptoms: ['Painful inflamed nodules', 'Abscesses (axillae, groin, breasts)', 'Sinus tracts', 'Scarring', 'Purulent drainage', 'Chronic recurrent'],
    causes: ['Follicular occlusion', 'Chronic inflammation', 'Smoking', 'Obesity', 'Hormonal factors'],
    treatment: ['Antibiotics (long-term, clindamycin)', 'Retinoids (acitretin)', 'Biologics (Adalimumab)', 'Surgical deroofing/excision', 'Weight loss', 'Smoking cessation'],
    description: 'A chronic inflammatory skin disease of nodules and abscesses in apocrine gland-rich areas.',
  },
};