import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART2: Record<string, DiseaseInfo> = {
  Hypertension: {
    category: 'cardiovascular',
    name: 'Hypertension',
    symptoms: ['Often asymptomatic', 'Headache', 'Dizziness', 'Blurred vision', 'Nosebleeds', 'Shortness of breath'],
    causes: ['High sodium intake', 'Obesity', 'Stress', 'Genetics', 'Lack of exercise', 'Excessive alcohol', 'Kidney disease'],
    treatment: ['ACE inhibitors', 'ARBs', 'Calcium channel blockers', 'Thiazide diuretics', 'Dietary changes', 'Regular exercise'],
    description: 'A chronic medical condition where blood pressure in the arteries is persistently elevated, increasing cardiovascular risk.',
  },
  'Stable Angina': {
    category: 'cardiovascular',
    name: 'Stable Angina',
    symptoms: ['Retrosternal chest pain on exertion', 'Pressure/tightness', 'Radiation to arm/jaw', 'Relief with rest or nitroglycerin', 'Dyspnea'],
    causes: ['Coronary atherosclerosis', 'Fixed coronary stenosis', 'Myocardial oxygen demand-supply mismatch', 'Risk factors (smoking, diabetes, lipids)'],
    treatment: ['Nitroglycerin (sublingual)', 'Beta-blockers', 'Aspirin', 'Statins', 'Calcium channel blockers', 'PCI or CABG'],
    description: 'Predictable chest discomfort caused by transient myocardial ischemia on exertion, relieved by rest or nitroglycerin.',
  },
  'Unstable Angina': {
    category: 'cardiovascular',
    name: 'Unstable Angina',
    symptoms: ['Chest pain at rest', 'Change in angina pattern', 'Increasing frequency/severity', 'Duration longer', 'New onset (severe)'],
    causes: ['Plaque rupture', 'Intracoronary thrombosis (partial)', 'Endothelial dysfunction', 'Vasospasm'],
    treatment: ['Aspirin', 'Heparin anticoagulation', 'Nitroglycerin', 'Beta-blockers', 'High-intensity statins', 'Coronary angiography'],
    description: 'Angina that is new, worsening, or occurring at rest, representing an acute coronary syndrome requiring urgent evaluation.',
  },
  MI: {
    category: 'cardiovascular',
    name: 'Myocardial Infarction',
    symptoms: ['Crushing chest pain', 'Pain radiating to left arm/jaw', 'Diaphoresis', 'Nausea/vomiting', 'Shortness of breath', 'Palpitations'],
    causes: ['Coronary artery occlusion (atherosclerosis)', 'Thrombus formation', 'Coronary vasospasm', 'Embolism'],
    treatment: ['Aspirin', 'PCI (angioplasty/stenting)', 'Thrombolytics', 'Beta-blockers', 'ACE inhibitors', 'Statins', 'Oxygen'],
    description: 'Death of myocardial tissue due to prolonged ischemia of the heart muscle, usually from blockage of a coronary artery.',
  },
  Stroke: {
    category: 'neurology',
    name: 'Stroke',
    symptoms: ['Sudden facial drooping', 'Arm weakness', 'Speech difficulty (FAST)', 'Visual disturbances', 'Severe headache', 'Loss of coordination'],
    causes: ['Ischemic: thrombosis or embolism', 'Hemorrhagic: ruptured blood vessel', 'Hypertension', 'Atrial fibrillation', 'Atherosclerosis'],
    treatment: ['Ischemic: tPA (within 4.5 hrs)', 'Mechanical thrombectomy', 'Antiplatelet therapy', 'Hemorrhagic: blood pressure control', 'Surgical intervention', 'Rehabilitation'],
    description: 'A medical emergency where blood supply to part of the brain is interrupted or reduced, causing brain cell death.',
  },
  'Heart Failure': {
    category: 'cardiovascular',
    name: 'Heart Failure',
    symptoms: ['Dyspnea', 'Orthopnea', 'Peripheral edema', 'Fatigue', 'Exercise intolerance', 'Weight gain', 'JVD'],
    causes: ['Coronary artery disease', 'Hypertension', 'Cardiomyopathy', 'Valvular heart disease', 'Myocarditis', 'Alcohol'],
    treatment: ['ACE inhibitors/ARBs', 'Beta-blockers', 'Diuretics', 'Aldosterone antagonists', 'SGLT2 inhibitors', 'Digoxin', 'Sodium restriction', 'Device therapy'],
    description: 'A chronic condition where the heart cannot pump blood efficiently enough to meet the body needs.',
  },
  AFib: {
    category: 'cardiovascular',
    name: 'Atrial Fibrillation',
    symptoms: ['Palpitations', 'Irregular pulse', 'Dyspnea', 'Fatigue', 'Dizziness', 'Chest discomfort'],
    causes: ['Hypertension', 'Valvular disease', 'Hyperthyroidism', 'Alcohol excess', 'Obstructive sleep apnea', 'Age'],
    treatment: ['Rate control (Beta-blockers, CCBs)', 'Rhythm control (Amiodarone)', 'Anticoagulation (Warfarin, DOACs)', 'Cardioversion', 'Catheter ablation'],
    description: 'The most common cardiac arrhythmia characterized by rapid and irregular atrial activation with stroke risk.',
  },
  'Atrial Flutter': {
    category: 'cardiovascular',
    name: 'Atrial Flutter',
    symptoms: ['Palpitations', 'Dyspnea', 'Fatigue', 'Dizziness', 'Chest discomfort'],
    causes: ['Re-entrant circuit in right atrium', 'Prior cardiac surgery', 'COPD', 'Valvular disease', 'Hyperthyroidism'],
    treatment: ['Rate control', 'Catheter ablation (curative)', 'Anticoagulation', 'Synchronized cardioversion', 'Antiarrhythmics'],
    description: 'A macro-reentrant atrial tachycardia producing rapid, regular sawtooth flutter waves, commonly around the tricuspid annulus.',
  },
  'Supraventricular Tachycardia': {
    category: 'cardiovascular',
    name: 'Supraventricular Tachycardia (SVT)',
    symptoms: ['Sudden rapid palpitations', 'Lightheadedness', 'Chest discomfort', 'Dyspnea', 'Anxiety', 'Polyuria'],
    causes: ['AV nodal re-entry', 'AV re-entry (accessory pathway)', 'Atrial ectopic focus', 'Stress/caffeine (precipitants)'],
    treatment: ['Vagal maneuvers', 'Adenosine', 'Calcium channel blockers', 'Beta-blockers', 'Catheter ablation'],
    description: 'A group of tachyarrhythmias arising above the ventricles, often episodic and paroxysmal.',
  },
  'Ventricular Tachycardia': {
    category: 'cardiovascular',
    name: 'Ventricular Tachycardia',
    symptoms: ['Palpitations', 'Syncope', 'Chest pain', 'Dyspnea', 'Cardiac arrest (if sustained)'],
    causes: ['Myocardial scar (MI)', 'Cardiomyopathy', 'Electrolyte abnormalities', 'Long QT syndrome', 'Drug toxicity'],
    treatment: ['Synchronized cardioversion (unstable)', 'Antiarrhythmics (Amiodarone, Lidocaine)', 'Defibrillator implant (ICD)', 'Catheter ablation', 'Correct electrolytes'],
    description: 'A rapid, regular heart rhythm originating in the ventricles that can be life-threatening and degenerate into ventricular fibrillation.',
  },
  'Ventricular Fibrillation': {
    category: 'cardiovascular',
    name: 'Ventricular Fibrillation',
    symptoms: ['Sudden collapse', 'Loss of consciousness', 'Pulseless', 'Apnea', 'Cardiac arrest'],
    causes: ['Ischemic heart disease', 'MI', 'Cardiomyopathy', 'Electrolyte abnormalities', 'Drug-induced arrhythmia', 'Channelopathies'],
    treatment: ['Immediate defibrillation', 'CPR', 'Epinephrine', 'Antiarrhythmics', 'Treat reversible causes'],
    description: 'Chaotic, disorganized electrical activity of the ventricles causing cardiac arrest; without defibrillation it is rapidly fatal.',
  },
  DVT: {
    category: 'cardiovascular',
    name: 'Deep Vein Thrombosis',
    symptoms: ['Unilateral leg swelling', 'Pain/tenderness', 'Warmth', 'Redness', 'Dilated veins'],
    causes: ['Venous stasis', 'Hypercoagulability', 'Endothelial injury', 'Immobility', 'Surgery', 'Cancer'],
    treatment: ['Anticoagulation (Heparin then Warfarin)', 'DOACs', 'Compression stockings', 'Thrombolysis in severe cases', 'IVC filter if contraindication'],
    description: 'Formation of a blood clot in a deep vein, usually in the legs, which can be life-threatening if the clot embolizes to the lungs.',
  },
  PE: {
    category: 'cardiovascular',
    name: 'Pulmonary Embolism',
    symptoms: ['Sudden dyspnea', 'Pleuritic chest pain', 'Tachycardia', 'Hemoptysis', 'Hypoxia', 'Anxiety'],
    causes: ['DVT embolization', 'Immobility', 'Hypercoagulable states', 'Surgery', 'Cancer', 'Oral contraceptives'],
    treatment: ['Anticoagulation', 'Thrombolysis for massive PE', 'Embolectomy', 'IVC filter', 'Oxygen support', 'Hemodynamic support'],
    description: 'A blockage in one of the pulmonary arteries in the lungs, usually from blood clots that travel from the legs.',
  },
  'Aortic Aneurysm': {
    category: 'cardiovascular',
    name: 'Abdominal Aortic Aneurysm',
    symptoms: ['Often asymptomatic', 'Pulsatile abdominal mass', 'Abdominal/back pain', 'Rupture: sudden severe pain, shock'],
    causes: ['Atherosclerosis', 'Hypertension', 'Smoking', 'Family history', 'Connective tissue disorders'],
    treatment: ['Surveillance (small aneurysms)', 'Endovascular repair (EVAR)', 'Open surgical repair', 'Blood pressure control', 'Smoking cessation'],
    description: 'A focal dilation of the abdominal aorta, at risk for rupture as it enlarges.',
  },
  'Aortic Dissection': {
    category: 'cardiovascular',
    name: 'Aortic Dissection',
    symptoms: ['Sudden tearing chest/back pain', 'Migrating pain', 'Symmetric BP difference', 'Syncope', 'Neurologic deficits', 'Cardiac tamponade'],
    causes: ['Hypertension (main)', 'Connective tissue disorders (Marfan)', 'Bicuspid aortic valve', 'Trauma', 'Pregnancy'],
    treatment: ['Emergency blood pressure control (beta-blockers)', 'Analgesia', 'Surgical repair (type A)', 'Endovascular stent (type B)', 'ICU monitoring'],
    description: 'A tear in the aortic intima allowing blood to track within the wall, a life-threatening vascular emergency.',
  },
  'Peripheral Arterial Disease': {
    category: 'cardiovascular',
    name: 'Peripheral Arterial Disease (PAD)',
    symptoms: ['Claudication', 'Leg pain with walking', 'Cold extremity', 'Weak pulses', 'Non-healing ulcers', 'Gangrene'],
    causes: ['Atherosclerosis', 'Smoking', 'Diabetes', 'Hypertension', 'Hyperlipidemia'],
    treatment: ['Exercise therapy', 'Smoking cessation', 'Antiplatelet therapy', 'Statins', 'Angioplasty/stenting', 'Bypass surgery'],
    description: 'Obstructive atherosclerotic disease of peripheral arteries, most commonly affecting the lower limbs.',
  },
  'Raynaud Phenomenon': {
    category: 'cardiovascular',
    name: 'Raynaud Phenomenon',
    symptoms: ['Cold, white then blue then red fingers', 'Numbness', 'Tingling', 'Pain on rewarming', 'Triggers: cold, stress'],
    causes: ['Primary: idiopathic vasospasm', 'Secondary: scleroderma, SLE, RA', 'Cold exposure', 'Smoking'],
    treatment: ['Avoid cold', 'Keep warm', 'Smoking cessation', 'Calcium channel blockers', 'Vasodilators (severe)'],
    description: 'Exaggerated vasospastic response of digital arteries causing triphasic color changes in response to cold or stress.',
  },
  'Rheumatic Heart Disease': {
    category: 'cardiovascular',
    name: 'Rheumatic Heart Disease',
    symptoms: ['Mitral stenosis symptoms', 'Dyspnea', 'Palpitations', 'Fatigue', 'Valvular murmurs', 'Heart failure'],
    causes: ['Group A streptococcal infection', 'Rheumatic fever sequelae', 'Autoimmune valvular damage', 'Recurrent infections'],
    treatment: ['Antibiotic prophylaxis', 'Valve surgery/replacement', 'Anticoagulation (AF)', 'Symptomatic management', 'Treat heart failure'],
    description: 'Chronic valvular damage, most commonly mitral stenosis, resulting from prior acute rheumatic fever.',
  },
  'Infective Endocarditis': {
    category: 'cardiovascular',
    name: 'Infective Endocarditis',
    symptoms: ['Fever', 'New or changed murmur', 'Osler nodes', 'Janeway lesions', 'Petechiae', 'Splinter hemorrhages', 'Embolic events', 'Fatigue'],
    causes: ['Bacterial infection (Strep viridans, Staph aureus)', 'Valvular abnormalities', 'Prosthetic valves', 'IV drug use', 'Dental procedures'],
    treatment: ['Prolonged IV antibiotics', 'Blood cultures-guided therapy', 'Surgical valve intervention', 'Complication management'],
    description: 'Infection of the endocardial surface of the heart, usually involving heart valves, with systemic embolic complications.',
  },
  Myocarditis: {
    category: 'cardiovascular',
    name: 'Myocarditis',
    symptoms: ['Chest pain', 'Dyspnea', 'Fatigue', 'Arrhythmias', 'Palpitations', 'Flu-like prodrome', 'Heart failure signs'],
    causes: ['Viral infections (Coxsackie, influenza)', 'COVID-19', 'Autoimmune diseases', 'Drugs/toxins', 'Sarcoidosis'],
    treatment: ['Supportive care', 'Heart failure therapy', 'Antiarrhythmics', 'Avoid exertion', 'Immunosuppression (selected cases)'],
    description: 'Inflammation of the myocardium, most often viral, which can impair cardiac function and cause arrhythmias.',
  },
  Pericarditis: {
    category: 'cardiovascular',
    name: 'Pericarditis',
    symptoms: ['Sharp pleuritic chest pain', 'Pain worsens supine', 'Relief when leaning forward', 'Fever', 'Pericardial friction rub'],
    causes: ['Viral infection', 'Post-MI (Dressler)', 'Uremia', 'Autoimmune disease', 'Tuberculosis', 'Malignancy'],
    treatment: ['NSAIDs', 'Colchicine', 'Glucocorticoids (refractory)', 'Treat underlying cause', 'Pericardiocentesis if effusion'],
    description: 'Inflammation of the pericardial sac causing characteristic positional chest pain.',
  },
  'Cardiac Tamponade': {
    category: 'cardiovascular',
    name: 'Cardiac Tamponade',
    symptoms: ['Beck triad (hypotension, JVD, muffled heart sounds)', 'Dyspnea', 'Tachycardia', 'Pulsus paradoxus', 'Shock'],
    causes: ['Pericardial effusion (malignant, uremic)', 'Trauma', 'Post-cardiac surgery', 'Tuberculosis', 'Hypothyroidism'],
    treatment: ['Emergency pericardiocentesis', 'Pericardial window', 'Intravenous fluids (supportive)', 'Treat underlying cause'],
    description: 'Compression of the heart by accumulating pericardial fluid, causing impaired diastolic filling and hemodynamic collapse.',
  },
  'Mitral Stenosis': {
    category: 'cardiovascular',
    name: 'Mitral Stenosis',
    symptoms: ['Dyspnea', 'Fatigue', 'Palpitations', 'Hemoptysis', 'Rheumatic history', 'Diastolic rumble murmur'],
    causes: ['Rheumatic heart disease', 'Congenital', 'Severe mitral annular calcification'],
    treatment: ['Diuretics', 'Anticoagulation (AF)', 'Beta-blockers', 'Mitral balloon valvuloplasty', 'Mitral valve replacement'],
    description: 'Narrowing of the mitral valve orifice, most commonly rheumatic, impeding left atrial emptying.',
  },
  'Aortic Stenosis': {
    category: 'cardiovascular',
    name: 'Aortic Stenosis',
    symptoms: ['Exertional dyspnea', 'Angina', 'Syncope', 'Systolic ejection murmur', 'Heart failure'],
    causes: ['Calcific degeneration of trileaflet valve', 'Bicuspid aortic valve', 'Rheumatic disease'],
    treatment: ['Transcatheter aortic valve replacement (TAVR)', 'Surgical valve replacement (SAVR)', 'Avoid vasodilators', 'Symptom management'],
    description: 'Narrowing of the aortic valve orifice causing left ventricular outflow obstruction with classic exertional triad of dyspnea, angina, and syncope.',
  },
  'Aortic Regurgitation': {
    category: 'cardiovascular',
    name: 'Aortic Regurgitation',
    symptoms: ['Palpitations', 'Dyspnea', 'Water-hammer pulse', 'Diastolic decrescendo murmur', 'Wide pulse pressure'],
    causes: ['Infective endocarditis', 'Aortic dissection', 'Bicuspid aortic valve', 'Rheumatic disease', 'Marfan syndrome'],
    treatment: ['Vasodilators', 'Afterload reduction', 'Surgical valve replacement', 'Treat endocarditis', 'Blood pressure control'],
    description: 'Backflow of blood from the aorta into the left ventricle during diastole due to an incompetent aortic valve.',
  },
  'Mitral Regurgitation': {
    category: 'cardiovascular',
    name: 'Mitral Regurgitation',
    symptoms: ['Dyspnea', 'Fatigue', 'Palpitations', 'Holosystolic murmur', 'Atrial fibrillation', 'Heart failure'],
    causes: ['Mitral valve prolapse', 'Ischemic heart disease', 'Rheumatic disease', 'Infective endocarditis', 'Dilated cardiomyopathy'],
    treatment: ['Afterload reduction', 'Diuretics', 'Surgical repair/replacement', 'Mitral clip (selected)', 'Valve repair preferred'],
    description: 'Incomplete closure of the mitral valve causing blood to reflux into the left atrium during ventricular systole.',
  },
  'Hypertrophic Cardiomyopathy': {
    category: 'cardiovascular',
    name: 'Hypertrophic Cardiomyopathy (HCM)',
    symptoms: ['Exertional dyspnea', 'Angina', 'Syncope', 'Palpitations', 'Sudden cardiac death risk', 'Systolic murmur (Valsalva increases)'],
    causes: ['Sarcomeric gene mutations', 'Autosomal dominant inheritance', 'Left ventricular hypertrophy'],
    treatment: ['Beta-blockers', 'Calcium channel blockers (non-dihydropyridine)', 'Avoid dehydration', 'Implantable defibrillator (high-risk)', 'Septal reduction therapy'],
    description: 'A genetic cardiomyopathy with inappropriate left ventricular hypertrophy, dynamic outflow obstruction, and arrhythmia risk.',
  },
  'Dilated Cardiomyopathy': {
    category: 'cardiovascular',
    name: 'Dilated Cardiomyopathy',
    symptoms: ['Dyspnea', 'Fatigue', 'Peripheral edema', 'Palpitations', 'Heart failure signs'],
    causes: ['Ischemic heart disease', 'Genetic mutations', 'Viral myocarditis', 'Alcohol', 'Peripartum', 'Anthracyclines'],
    treatment: ['Heart failure therapy (ACEi, BB, diuretics, SGLT2i)', 'Device therapy (CRT/ICD)', 'Avoid alcohol', 'Anticoagulation if AF', 'Transplant (selected)'],
    description: 'Enlargement and impaired contraction of the left ventricle leading to systolic heart failure.',
  },
  'Cardiac Arrest': {
    category: 'emergency',
    name: 'Cardiac Arrest',
    symptoms: ['Sudden loss of consciousness', 'No pulse', 'No breathing', 'Pupil dilation', 'Death if untreated'],
    causes: ['Ventricular fibrillation', 'Ventricular tachycardia', 'Severe hypoxia', 'Electrolyte abnormalities', 'Trauma', 'Drug overdose'],
    treatment: ['Immediate CPR', 'Automated/external defibrillation', 'Epinephrine', 'Advanced airway management', 'Treat reversible causes'],
    description: 'Abrupt cessation of effective cardiac pumping causing loss of circulation and consciousness, requiring immediate resuscitation.',
  },
  'Restrictive Cardiomyopathy': {
    category: 'cardiovascular',
    name: 'Restrictive Cardiomyopathy',
    symptoms: ['Dyspnea', 'Edema', 'Ascites', 'JVD', 'Fatigue', 'Heart failure with normal systolic function'],
    causes: ['Amyloidosis', 'Sarcoidosis', 'Hemochromatosis', 'Endomyocardial fibrosis', 'Radiation'],
    treatment: ['Treat underlying infiltrative disease', 'Diuretics', 'Heart failure medications', 'Disease-modifying therapy (amyloid)'],
    description: 'A cardiomyopathy with rigid ventricular walls that impair diastolic filling despite preserved contractility.',
  },
};