import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART8: Record<string, DiseaseInfo> = {
  'Anemia (Iron Deficiency)': {
    category: 'hematology',
    name: 'Iron Deficiency Anemia',
    symptoms: ['Fatigue', 'Pallor', 'Dyspnea on exertion', 'Headache', 'Dizziness', 'Cold intolerance', 'Pica', 'Koilonychia'],
    causes: ['Chronic blood loss (menstrual, GI)', 'Poor dietary iron', 'Malabsorption', 'Pregnancy', 'GI malignancy'],
    treatment: ['Oral iron supplementation', 'IV iron (selected)', 'Identify bleeding source', 'Dietary iron increase', 'Treat underlying cause'],
    description: 'The most common anemia, from insufficient iron stores for hemoglobin synthesis.',
  },
  'Anemia (B12 Deficiency)': {
    category: 'hematology',
    name: 'Vitamin B12 Deficiency Anemia',
    symptoms: ['Fatigue', 'Pallor', 'Glossitis', 'Peripheral neuropathy', 'Paresthesias', 'Balance problems', 'Memory impairment'],
    causes: ['Pernicious anemia (autoimmune)', 'Malabsorption (gastric/ileal disease)', 'Strict vegetarian diet', 'Medications (Metformin, PPIs)'],
    treatment: ['Cyanocobalamin injections', 'Oral B12 (selected)', 'Treat pernicious anemia', 'Dietary supplementation', 'Monitor levels'],
    description: 'Megaloblastic anemia with neurological manifestations from vitamin B12 deficiency.',
  },
  'Anemia (Folate Deficiency)': {
    category: 'hematology',
    name: 'Folate Deficiency Anemia',
    symptoms: ['Fatigue', 'Pallor', 'Glossitis', 'Dyspnea', 'Megaloblastic changes'],
    causes: ['Poor dietary intake', 'Alcoholism', 'Pregnancy', 'Malabsorption', 'Anticonvulsants', 'Hemolysis'],
    treatment: ['Folic acid supplementation', 'Dietary improvement', 'Alcohol cessation', 'Treat underlying cause', 'Preventive in pregnancy'],
    description: 'Megaloblastic anemia due to folate deficiency, important in pregnancy for neural tube defects.',
  },
  'Aplastic Anemia': {
    category: 'hematology',
    name: 'Aplastic Anemia',
    symptoms: ['Fatigue', 'Bleeding/bruising', 'Recurrent infections', 'Pallor', 'Petechiae', 'Fever'],
    causes: ['Autoimmune marrow destruction', 'Radiation/chemotherapy', 'Drugs (chloramphenicol)', 'Viral (hepatitis, EBV)', 'Idiopathic'],
    treatment: ['Immunosuppression (ATG + cyclosporine)', 'Stem cell transplant', 'Blood product support', 'Growth factors', 'Antibiotic prophylaxis'],
    description: 'Failure of the bone marrow to produce blood cells, causing pancytopenia.',
  },
  'Hemolytic Anemia': {
    category: 'hematology',
    name: 'Hemolytic Anemia',
    symptoms: ['Fatigue', 'Jaundice', 'Dark urine', 'Pallor', 'Splenomegaly', 'Gallstones', 'Anemia'],
    causes: ['Autoimmune hemolysis', 'G6PD deficiency', 'Sickle cell disease', 'Hereditary spherocytosis', 'Drug-induced', 'Microangiopathy'],
    treatment: ['Treat underlying cause', 'Corticosteroids (autoimmune)', 'Folate supplementation', 'Transfusion support', 'Splenectomy (selected)'],
    description: 'Premature destruction of red blood cells causing anemia, hyperbilirubinemia, and reticulocytosis.',
  },
  'Sickle Cell Disease': {
    category: 'hematology',
    name: 'Sickle Cell Disease',
    symptoms: ['Painful crises', 'Chronic anemia', 'Jaundice', 'Infections (splenic dysfunction)', 'Hand-foot syndrome', 'Priapism', 'Stroke risk', 'Avascular necrosis'],
    causes: ['Hemoglobin S gene mutations', 'Autosomal recessive inheritance', 'HbS polymerization'],
    treatment: ['Hydroxyurea', 'Hydration and analgesia (crises)', 'Folate supplementation', 'Antibiotic prophylaxis (penicillin)', 'Vaccinations', 'Stem cell transplant (curative)', 'Crizanlizumab (crises)'],
    description: 'A genetic hemoglobinopathy causing rigid sickled red cells, vaso-occlusion, hemolytic anemia, and multiorgan damage.',
  },
  'Thalassemia': {
    category: 'hematology',
    name: 'Thalassemia',
    symptoms: ['Anemia (variable severity)', 'Fatigue', 'Bone deformities (facial)', 'Growth retardation', 'Splenomegaly', 'Jaundice', 'Iron overload (transfusions)'],
    causes: ['Globin chain gene mutations', 'Impaired hemoglobin synthesis', 'Autosomal recessive inheritance'],
    treatment: ['Transfusions (major)', 'Iron chelation', 'Folate supplementation', 'Splenectomy (selected)', 'Stem cell transplant', 'Luspatercept (transfusion reduction)'],
    description: 'A group of hemoglobin disorders with reduced globin chain synthesis, causing microcytic anemia and iron overload with transfusions.',
  },
  'G6PD Deficiency': {
    category: 'hematology',
    name: 'G6PD Deficiency',
    symptoms: ['Hemolytic episodes', 'Jaundice', 'Dark urine', 'Fatigue', 'Shortness of breath', 'Triggered by drugs/infection/fava'],
    causes: ['X-linked enzyme deficiency', 'Oxidative stress on red cells', 'Drugs (sulfa, antimalarials)', 'Fava beans'],
    treatment: ['Avoid precipitating factors', 'Supportive care', 'Transfusion (severe hemolysis)', 'Hydration', 'Folate supplementation'],
    description: 'An X-linked enzyme deficiency causing hemolysis upon oxidative stress from drugs, foods, or infection.',
  },
  'Hereditary Spherocytosis': {
    category: 'hematology',
    name: 'Hereditary Spherocytosis',
    symptoms: ['Anemia', 'Jaundice (neonatal)', 'Splenomegaly', 'Gallstones', 'Fatigue', 'Pallor'],
    causes: ['Spectrin/ankyrin mutations', 'Autosomal dominant inheritance', 'Decreased red cell deformability'],
    treatment: ['Folate supplementation', 'Transfusion support', 'Splenectomy (moderate-severe)', 'Gallbladder surgery (stones)', 'Vaccinations before splenectomy'],
    description: 'A red cell membrane disorder causing spherical, fragile cells prone to splenic destruction.',
  },
  'Leukemia (Acute Lymphoblastic)': {
    category: 'oncology',
    name: 'Acute Lymphoblastic Leukemia (ALL)',
    symptoms: ['Fatigue', 'Bleeding/bruising', 'Fever/infections', 'Pallor', 'Bone pain', 'Lymphadenopathy', 'Petechiae'],
    causes: ['Chromosomal abnormalities', 'Genetic syndromes', 'Ionizing radiation (rare)', 'Precursor B/T cell malignancy'],
    treatment: ['Multi-agent chemotherapy', 'CNS prophylaxis (intrathecal)', 'Targeted therapy (tyrosine kinase)', 'Stem cell transplant', 'Blinatumomab (selected)'],
    description: 'A malignant proliferation of lymphoid precursor cells, the most common cancer in children.',
  },
  'Leukemia (Acute Myeloid)': {
    category: 'oncology',
    name: 'Acute Myeloid Leukemia (AML)',
    symptoms: ['Fatigue', 'Bleeding/bruising', 'Fever/infections', 'Pallor', 'Bone pain', 'Gum bleeding/swelling', 'Leukostasis (high counts)'],
    causes: ['Chromosomal translocations', 'Prior chemotherapy/radiation', 'Myelodysplasia progression', 'Age', 'Environmental exposures'],
    treatment: ['Induction chemotherapy (7+3)', 'Consolidation therapy', 'Targeted therapy (FLT3, IDH)', 'Stem cell transplant', 'APL: ATRA + arsenic'],
    description: 'A rapidly progressive malignancy of myeloid precursors with bone marrow failure and blast infiltration.',
  },
  'Leukemia (Chronic Myeloid)': {
    category: 'oncology',
    name: 'Chronic Myeloid Leukemia (CML)',
    symptoms: ['Fatigue', 'Weight loss', 'Splenomegaly', 'Night sweats', 'Early satiety', 'Fever', 'Often asymptomatic (incidental)'],
    causes: ['Philadelphia chromosome (BCR-ABL translocation)', 't(9;22) translocation', 'Ionizing radiation'],
    treatment: ['Tyrosine kinase inhibitors (Imatinib, nilotinib)', 'Blast crisis management', 'Monitoring BCR-ABL levels', 'Allogeneic transplant (refractory)', 'Targeted therapy'],
    description: 'A myeloproliferative neoplasm characterized by the Philadelphia chromosome and a chronic phase with progression risk.',
  },
  'Leukemia (Chronic Lymphocytic)': {
    category: 'oncology',
    name: 'Chronic Lymphocytic Leukemia (CLL)',
    symptoms: ['Often asymptomatic', 'Fatigue', 'Lymphadenopathy', 'Splenomegaly', 'Recurrent infections', 'B symptoms (fever, night sweats, weight loss)'],
    causes: ['Mature B-cell neoplasm', 'Chromosomal abnormalities (del17p, del13q)', 'Genetic predisposition'],
    treatment: ['Watch and wait (early)', 'BTK inhibitors (Ibrutinib)', 'BCL2 inhibitors (Venetoclax)', 'Anti-CD20 (Rituximab)', 'Chemoimmunotherapy', 'Targeted combinations'],
    description: 'A slowly progressive B-cell malignancy, common in older adults, with variable clinical course.',
  },
  'Lymphoma (Hodgkin)': {
    category: 'oncology',
    name: 'Hodgkin Lymphoma',
    symptoms: ['Painless lymphadenopathy (cervical)', 'B symptoms (fever, night sweats, weight loss)', 'Pruritus', 'Fatigue', 'Mediastinal mass', 'Alcohol-induced pain (rare)'],
    causes: ['Reed-Sternberg cells', 'Epstein-Barr virus (association)', 'Immunological dysfunction', 'Genetic factors'],
    treatment: ['ABVD chemotherapy', 'Radiation therapy (early-stage)', 'BEACOPP (advanced)', 'Stem cell transplant (relapsed)', 'Immunotherapy (checkpoint inhibitors)'],
    description: 'A lymphoma with distinctive Reed-Sternberg cells, highly curable even in advanced stages.',
  },
  'Lymphoma (Non-Hodgkin)': {
    category: 'oncology',
    name: 'Non-Hodgkin Lymphoma',
    symptoms: ['Painless lymphadenopathy', 'B symptoms', 'Extranodal disease', 'Abdominal mass', 'Fatigue', 'Pruritus'],
    causes: ['B-cell or T-cell origin', 'EBV (selected types)', 'Immunosuppression', 'Autoimmune disease', 'Age'],
    treatment: ['R-CHOP chemotherapy', 'Radiation (localized)', 'Targeted therapy (BTK inhibitors)', 'Stem cell transplant', 'CAR-T therapy (selected)'],
    description: 'A diverse group of lymphocytic malignancies, more common than Hodgkin lymphoma, with variable aggressiveness.',
  },
  'Multiple Myeloma': {
    category: 'oncology',
    name: 'Multiple Myeloma',
    symptoms: ['Bone pain (back, ribs)', 'Pathologic fractures', 'Fatigue (anemia)', 'Hypercalcemia (confusion, nausea)', 'Renal failure', 'Recurrent infections', 'Bone lesions lytic'],
    causes: ['Plasma cell malignancy', 'Monoclonal immunoglobulin production', 'Chromosomal abnormalities', 'MGUS progression'],
    treatment: ['Proteasome inhibitors (Bortezomib)', 'Immunomodulators (Lenalidomide)', 'Monoclonal antibodies (Daratumumab)', 'Corticosteroids', 'Stem cell transplant (eligible)', 'Bisphosphonates (bones)'],
    description: 'A malignancy of plasma cells producing lytic bone lesions, hypercalcemia, anemia, renal disease, and infections.',
  },
  'Immune Thrombocytopenia': {
    category: 'hematology',
    name: 'Immune Thrombocytopenia (ITP)',
    symptoms: ['Petechiae', 'Purpura', 'Bruising', 'Mucosal bleeding', 'Epistaxis', 'Heavy menses', 'Fatal intracranial hemorrhage (rare)'],
    causes: ['Autoimmune platelet destruction', 'Antiplatelet antibodies', 'Viral triggers', 'Drug induced - immune'],
    treatment: ['Corticosteroids', 'IVIG', 'Anti-D immunoglobulin', 'Thrombopoietin agonists', 'Rituximab', 'Splenectomy (refractory)'],
    description: 'An autoimmune disorder of low platelets with increased bleeding risk, usually without leukopenia or anemia.',
  },
  'Disseminated Intravascular Coagulation': {
    category: 'hematology',
    name: 'Disseminated Intravascular Coagulation (DIC)',
    symptoms: ['Bleeding (multiple sites)', 'Petechiae/purpura', 'Oozing from venipunctures', 'End-organ ischemia', 'Thrombosis symptoms', 'Shock'],
    causes: ['Sepsis', 'Obstetric complications (abruption, amniotic fluid embolism)', 'Malignancy', 'Major trauma', 'Pancreatitis', 'Snakebite'],
    treatment: ['Treat underlying cause', 'Blood product replacement', 'Cryoprecipitate (fibrinogen)', 'Platelets', 'Plasma transfusion', 'Heparin (selected, chronic DIC)'],
    description: 'An acquired consumptive coagulopathy with simultaneous widespread bleeding and microvascular thrombosis.',
  },
  'von Willebrand Disease': {
    category: 'hematology',
    name: 'von Willebrand Disease',
    symptoms: ['Easy bruising', 'Epistaxis', 'Heavy menstrual bleeding', 'Prolonged bleeding after surgery', 'Gum bleeding', 'Family history of bleeding'],
    causes: ['von Willebrand factor deficiency/dysfunction', 'Autosomal inheritance', 'Genetic mutations'],
    treatment: ['Desmopressin (DDAVP)', 'von Willebrand factor replacement', 'Tranexamic acid', 'Antifibrinolytics', 'Avoid antiplatelet agents'],
    description: 'The most common inherited bleeding disorder, from deficiency or dysfunction of von Willebrand factor.',
  },
  'Hemophilia': {
    category: 'hematology',
    name: 'Hemophilia',
    symptoms: ['Spontaneous joint bleeding (hemarthrosis)', 'Deep muscle bleeding', 'Easy bruising', 'Prolonged bleeding', 'Target joint damage'],
    causes: ['Factor VIII deficiency (A)', 'Factor IX deficiency (B)', 'X-linked recessive inheritance', 'Genetic mutations'],
    treatment: ['Factor replacement (VIII/IX)', 'Emicizumab (A, prophylaxis)', 'Tranexamic acid', 'Avoid NSAIDs', 'Desmopressin (mild A)', 'Gene therapy (selected)'],
    description: 'An X-linked bleeding disorder from factor VIII or IX deficiency causing spontaneous and trauma-related bleeding.',
  },
  'Deep Vein Thrombosis (Recurrent)': {
    category: 'hematology',
    name: 'Recurrent Venous Thromboembolism',
    symptoms: ['Recurrent leg swelling', 'Recurrent PE symptoms', 'Pain', 'Post-thrombotic syndrome'],
    causes: ['Thrombophilia (Factor V Leiden, antiphospholipid)', 'Malignancy', 'Immobility', 'Estrogen use', 'Idiopathic'],
    treatment: ['Long-term or indefinite anticoagulation', 'DOACs/Warfarin', 'Treat malignancy', 'Compression stockings', 'Consider IVC filter'],
    description: 'Repeated venous thromboembolic events, prompting evaluation for hypercoagulable states.',
  },
  'Polycythemia Vera': {
    category: 'oncology',
    name: 'Polycythemia Vera',
    symptoms: ['Headache', 'Pruritus (after shower)', 'Dizziness', 'Blurred vision', 'Hypertension', 'Facial plethora', 'Thrombosis risk', 'Splenomegaly'],
    causes: ['JAK2 V617F mutation', 'Myeloproliferative neoplasm', 'Unregulated red cell production'],
    treatment: ['Phlebotomy', 'Low-dose aspirin', 'Hydroxyurea (high risk)', 'Ruxolitinib (JAK2 inhibitor)', 'Control cardiovascular risk'],
    description: 'A myeloproliferative neoplasm of excess red cell production with thrombosis and bleeding risks.',
  },
  'Thrombotic Thrombocytopenic Purpura': {
    category: 'hematology',
    name: 'Thrombotic Thrombocytopenic Purpura (TTP)',
    symptoms: ['Fever', 'Thrombocytopenia (bleeding)', 'Hemolytic anemia', 'Neurologic changes', 'Renal dysfunction', 'Confusion'],
    causes: ['ADAMTS13 deficiency', 'Autoantibodies to ADAMTS13', 'Ultra-large vWF multimers', 'Acquired (idiopathic, drug)'],
    treatment: ['Therapeutic plasma exchange', 'Glucocorticoids', 'Rituximab (refractory)', 'Caplacizumab', 'Stop culprit drugs'],
    description: 'A thrombotic microangiopathy of platelet clumping causing microvascular occlusion, hemolytic anemia, and multiorgan dysfunction.',
  },
  'Myelodysplastic Syndrome': {
    category: 'oncology',
    name: 'Myelodysplastic Syndrome (MDS)',
    symptoms: ['Fatigue (anemia)', 'Bleeding (thrombocytopenia)', 'Infections (neutropenia)', 'Bruising', 'Pallor'],
    causes: ['Clonal marrow stem cell disorder', 'Prior chemotherapy/radiation', 'Age', 'Chromosomal abnormalities', 'Environmental exposures'],
    treatment: ['Growth factors', 'Hypomethylating agents (Azacitidine)', 'Lenalidomide (del5q)', 'Stem cell transplant (curative)', 'Transfusion support'],
    description: 'A clonal disorder of ineffective hematopoiesis with cytopenias and risk of transformation to acute leukemia.',
  },
  'Anemia of Chronic Disease': {
    category: 'hematology',
    name: 'Anemia of Chronic Disease',
    symptoms: ['Fatigue', 'Pallor', 'Reduced exercise tolerance', 'Underlying disease symptoms'],
    causes: ['Chronic inflammation', 'Cancer', 'Chronic infection', 'Autoimmune disease', 'Iron sequestration (hepcidin)'],
    treatment: ['Treat underlying disease', 'Erythropoiesis-stimulating agents (selected)', 'Iron supplementation (selected)', 'Address deficiency states'],
    description: 'A mild to moderate anemia associated with chronic inflammation, infection, or malignancy.',
  },
  'Neutropenia': {
    category: 'hematology',
    name: 'Neutropenia',
    symptoms: ['Fever (infection risk)', 'Recurrent infections', 'Mouth ulcers', 'Cellulitis', 'Sepsis (severe)'],
    causes: ['Chemotherapy', 'Drug-induced', 'Autoimmune', 'Bone marrow disorders', 'Viral infection', 'Sepsis'],
    treatment: ['G-CSF (growth factor)', 'Antibiotics for fever (empiric)', 'Treat underlying cause', 'Reverse offending drugs', 'Infection precautions'],
    description: 'Reduced neutrophil count increasing susceptibility to bacterial and fungal infections, especially febrile neutropenia.',
  },
};