import type { DiseaseInfo } from '../medicalTypes';

export const DISEASES_PART7: Record<string, DiseaseInfo> = {
  'Chronic Kidney Disease': {
    category: 'nephrology',
    name: 'Chronic Kidney Disease',
    symptoms: ['Fatigue', 'Edema', 'Poor appetite', 'Nausea', 'Itching', 'Sleep problems', 'Decreased urine output', 'Hypertension'],
    causes: ['Diabetes mellitus', 'Hypertension', 'Glomerulonephritis', 'Polycystic kidney disease', 'Autoimmune disease', 'Obstruction'],
    treatment: ['ACEi/ARBs', 'BP control', 'Glycemic control', 'Diuretics (edema)', 'Phosphate binders', 'Erythropoietin (anemia)', 'Renal replacement (dialysis/transplant)'],
    description: 'Progressive loss of kidney function over months/years, leading to accumulation of waste products and fluid imbalance.',
  },
  'Acute Kidney Injury': {
    category: 'nephrology',
    name: 'Acute Kidney Injury',
    symptoms: ['Decreased urine output', 'Fluid overload', 'Nausea', 'Fatigue', 'Confusion', 'Edema', 'Elevated creatinine'],
    causes: ['Pre-renal: hypovolemia, sepsis, heart failure', 'Renal: toxins, drugs, glomerulonephritis', 'Post-renal: obstruction (stones, prostate)'],
    treatment: ['Correct hypovolemia', 'Stop nephrotoxic drugs', 'Dialysis (severe)', 'Treat underlying cause', 'Fluid/electrolyte management', 'Monitor urine output'],
    description: 'A rapid decline in kidney function causing accumulation of toxins and fluid, with multiple causes.',
  },
  'Nephrotic Syndrome': {
    category: 'nephrology',
    name: 'Nephrotic Syndrome',
    symptoms: ['Heavy proteinuria', 'Peripheral edema', 'Foamy urine', 'Hypoalbuminemia', 'Hyperlipidemia', 'Weight gain'],
    causes: ['Minimal change disease (children)', 'Membranous nephropathy', 'Focal segmental glomerulosclerosis', 'Diabetes', 'Systemic lupus'],
    treatment: ['Glucocorticoids (minimal change)', 'Immunosuppression (selected)', 'ACEi/ARBs', 'Diuretics', 'Low-sodium diet', 'Anticoagulation (thrombosis risk)'],
    description: 'A glomerular disorder with massive proteinuria leading to edema, hypoalbuminemia, and hyperlipidemia.',
  },
  'Nephritic Syndrome': {
    category: 'nephrology',
    name: 'Acute Nephritic Syndrome',
    symptoms: ['Hematuria (coluria)', 'Hypertension', 'Decreased urine output', 'Periorbital/pedal edema', 'Proteinuria (moderate)', 'Fatigue'],
    causes: ['Post-streptococcal glomerulonephritis', 'IgA nephropathy', 'Lupus nephritis', 'Goodpasture syndrome', 'ANCA vasculitis'],
    treatment: ['Blood pressure control', 'Diuretics', 'Treat underlying cause', 'Immunosuppression (vasculitis/lupus)', 'Dialysis (severe)'],
    description: 'Acute glomerular inflammation with hematuria, proteinuria, hypertension, and reduced urine output.',
  },
  'Glomerulonephritis': {
    category: 'nephrology',
    name: 'Glomerulonephritis',
    symptoms: ['Hematuria', 'Foamy urine', 'Edema', 'Hypertension', 'Reduced kidney function', 'Oliguria'],
    causes: ['Post-infectious', 'IgA nephropathy', 'Membranoproliferative', 'Autoimmune (SLE, vasculitis)', 'Cryoglobulinemia'],
    treatment: ['Treat underlying cause', 'Blood pressure control', 'Immunosuppressants (selected)', 'Diuretics', 'Rituximab (selected)', 'Dialysis (advanced)'],
    description: 'Inflammation of the glomeruli causing hematuria, proteinuria, hypertension, and impaired filtration.',
  },
  'Nephrolithiasis (Stones)': {
    category: 'urology',
    name: 'Kidney Stones (Nephrolithiasis)',
    symptoms: ['Severe colicky flank pain', 'Hematuria', 'Nausea/vomiting', 'Dysuria', 'Fever (if infected)', 'Pain radiating to groin'],
    causes: ['Calcium oxalate stones', 'Uric acid stones', 'Hypercalciuria', 'Dehydration', 'Infection (struvite)', 'Metabolic disorders'],
    treatment: ['Hydration', 'Pain control', 'Alpha-blockers (expulsion)', 'Shockwave lithotripsy', 'Ureteroscopy', 'Dietary modification prevention'],
    description: 'Crystalline concretions in the urinary tract causing colic, hematuria, and obstruction.',
  },
  'Urinary Tract Infection': {
    category: 'urology',
    name: 'Urinary Tract Infection',
    symptoms: ['Dysuria', 'Frequency', 'Urgency', 'Suprapubic pain', 'Cloudy/foul urine', 'Hematuria', 'Fever (if pyelonephritis)'],
    causes: ['E. coli (most common)', 'Bacterial ascent', 'Female anatomy', 'Catheterization', 'Stasis', 'Sexual activity'],
    treatment: ['Antibiotics (Nitrofurantoin, Trimethoprim)', 'Hydration', 'Urinalysis/culture', 'Analgesia (Phenazopyridine)', 'Preventive measures'],
    description: 'Bacterial infection of the urinary tract, commonly cystitis, with risk of ascending pyelonephritis.',
  },
  'Pyelonephritis': {
    category: 'urology',
    name: 'Acute Pyelonephritis',
    symptoms: ['Fever and chills', 'Flank pain', 'Dysuria', 'Nausea/vomiting', 'Costovertebral angle tenderness', 'Frequency'],
    causes: ['Ascending urinary infection', 'E. coli', 'Urinary obstruction', 'Vesicoureteral reflux', 'Catheterization'],
    treatment: ['Oral/IV antibiotics (Fluoroquinolones)', 'Hydration', 'Urinalysis/culture', 'Analgesia', 'Hospitalization (severe/pregnancy)'],
    description: 'Bacterial infection of the renal parenchyma and pelvis, a severe form of urinary infection.',
  },
  'Polycystic Kidney Disease': {
    category: 'nephrology',
    name: 'Polycystic Kidney Disease',
    symptoms: ['Flank/abdominal pain', 'Hematuria', 'Frequent infections', 'Nephrolithiasis', 'Hypertension', 'Progressive renal failure', 'Abdominal masses'],
    causes: ['PKD1/PKD2 gene mutations', 'Autosomal dominant inheritance', 'Cyst formation in kidneys'],
    treatment: ['Blood pressure control', 'Pain management', 'Antibiotics (infections)', 'Tolvaptan (ADPKD progression)', 'Dialysis/transplant (end-stage)'],
    description: 'A genetic disorder of multiple kidney cysts causing gradual kidney enlargement and eventual renal failure.',
  },
  'Nephrotic Syndrome (Diabetic)': {
    category: 'nephrology',
    name: 'Diabetic Nephropathy',
    symptoms: ['Gradual proteinuria', 'Edema', 'Progressive renal decline', 'Hypertension', 'Asymptomatic early'],
    causes: ['Long-standing diabetes', 'Hyperglycemia', 'Hypertension', 'Glomerular hyperfiltration', 'Genetics'],
    treatment: ['ACEi/ARBs (renoprotection)', 'Glycemic control', 'Blood pressure control', 'SGLT2 inhibitors', 'Low-protein diet', 'Dialysis/transplant (advanced)'],
    description: 'Progressive kidney damage from diabetes, a leading cause of end-stage renal disease.',
  },
  'Prostatitis': {
    category: 'urology',
    name: 'Prostatitis',
    symptoms: ['Perineal/pelvic pain', 'Dysuria', 'Frequency/urgency', 'Fever (acute)', 'Ejaculatory pain', 'Lower back pain'],
    causes: ['Bacterial infection (acute/chronic)', 'Chronic pelvic pain syndrome', 'Obstruction', 'Catheterization', 'Young men prevalence'],
    treatment: ['Antibiotics (prolonged for chronic)', 'Alpha-blockers', 'NSAIDs', 'Sitz baths', 'Prostate massage (selected)'],
    description: 'Inflammation of the prostate, acute bacterial or chronic, with pelvic pain and urinary symptoms.',
  },
  'Benign Prostatic Hyperplasia': {
    category: 'urology',
    name: 'Benign Prostatic Hyperplasia (BPH)',
    symptoms: ['Hesitancy', 'Weak stream', 'Nocturia', 'Urgency/frequency', 'Incomplete emptying', 'Post-void dribbling'],
    causes: ['Age-related prostate enlargement', 'Androgen stimulation', 'Family history', 'Hormonal changes'],
    treatment: ['Alpha-blockers (Tamsulosin)', '5-alpha reductase inhibitors (Finasteride)', 'Combination therapy', 'Surgical resection (TURP)', 'Watchful waiting'],
    description: 'Noncancerous enlargement of the prostate gland causing lower urinary tract obstruction in older men.',
  },
  'Kidney Cancer': {
    category: 'oncology',
    name: 'Renal Cell Carcinoma',
    symptoms: ['Hematuria', 'Flank pain', 'Palpable flank mass', 'Weight loss', 'Fever', 'Paraneoplastic syndromes', 'Fatigue'],
    causes: ['Smoking', 'Obesity', 'Hypertension', 'Von Hippel-Lindau disease', 'Genetic factors', 'Occupational exposures'],
    treatment: ['Nephrectomy (partial/radical)', 'Targeted therapy (tyrosine kinase inhibitors)', 'Immunotherapy', 'Ablation (small tumors)', 'Surveillance (selected)'],
    description: 'The most common kidney cancer, arising from renal tubular epithelial cells.',
  },
  'Bladder Cancer': {
    category: 'oncology',
    name: 'Bladder Cancer',
    symptoms: ['Painless hematuria', 'Dysuria', 'Frequency/urgency', 'Pelvic pain', 'Recurrent UTI-like symptoms'],
    causes: ['Smoking', 'Occupational chemical exposure', 'Chronic cystitis', 'Schistosomiasis', 'Age'],
    treatment: ['Transurethral resection (TURBT)', 'Intravesical therapy (BCG)', 'Cystectomy (invasive)', 'Chemotherapy', 'Radiation therapy'],
    description: 'A malignancy of the bladder urothelium, usually transitional cell carcinoma, presenting with hematuria.',
  },
  'Urinary Incontinence': {
    category: 'urology',
    name: 'Urinary Incontinence',
    symptoms: ['Involuntary urine leakage', 'Stress leakage (cough/sneeze)', 'Urge leakage', 'Nocturia', 'Impact on quality of life'],
    causes: ['Pelvic floor weakness', 'Overactive bladder', 'Prostate disease', 'Neurologic disease', 'Obesity', 'Medications'],
    treatment: ['Pelvic floor exercises (Kegel)', 'Bladder training', 'Antimuscarinics/Beta-3 agonists', 'Topical estrogen (women)', 'Botox injections', 'Surgical slings'],
    description: 'Involuntary loss of urine, classified as stress, urge, mixed, or overflow incontinence.',
  },
  'Prostate Cancer': {
    category: 'oncology',
    name: 'Prostate Cancer',
    symptoms: ['Often asymptomatic early', 'Urinary obstruction', 'Bone pain (metastasis)', 'Hematuria', 'Erectile dysfunction (late)'],
    causes: ['Age', 'Family history/genetics', 'African descent', 'High-fat diet (association)', 'Hormonal factors'],
    treatment: ['Active surveillance (low risk)', 'Prostatectomy', 'Radiation therapy', 'Hormone therapy (androgen deprivation)', 'Chemotherapy (metastatic)'],
    description: 'A malignancy of the prostate gland, screening with PSA and often slow-growing, but aggressive variants exist.',
  },
  'Erectile Dysfunction': {
    category: 'urology',
    name: 'Erectile Dysfunction',
    symptoms: ['Inability to maintain erection', 'Reduced rigidity', 'Decreased libido', 'Ejaculatory problems'],
    causes: ['Vascular disease', 'Diabetes', 'Hypertension', 'Medications (beta-blockers)', 'Psychological causes', 'Hormonal (low testosterone)'],
    treatment: ['PDE5 inhibitors (Sildenafil, Tadalafil)', 'Testosterone replacement (deficient)', 'Lifestyle modification', 'Psychotherapy', 'Penile prostheses (refractory)'],
    description: 'Persistent inability to achieve or maintain an erection sufficient for intercourse, a marker of vascular disease.',
  },
  'Kidney Infection (Chronic)': {
    category: 'urology',
    name: 'Chronic Pyelonephritis',
    symptoms: ['Recurrent flank pain', 'Fever', 'Dysuria', 'Progressive renal scarring', 'Hypertension', 'Recurrent infections'],
    causes: ['Recurrent urinary infections', 'Vesicoureteral reflux', 'Obstruction', 'Renal calculi', 'Struvite staghorn stones'],
    treatment: ['Treat underlying obstruction/reflux', 'Long-term antibiotics (selected)', 'Surgical correction (reflux)', 'Blood pressure control', 'Preserve renal function'],
    description: 'Repeated or persistent renal infection leading to renal scarring and renal function loss.',
  },
  'Nephritis (Interstitial)': {
    category: 'nephrology',
    name: 'Acute Interstitial Nephritis',
    symptoms: ['Rising creatinine', 'Hematuria (mild)', 'Fever', 'Rash', 'Flank pain', 'Eosinophilia'],
    causes: ['Drugs (PPIs, NSAIDs, antibiotics)', 'Infection', 'Autoimmune (Sjögren, SLE)', 'Idiopathic'],
    treatment: ['Stop culprit drug', 'Corticosteroids (selected)', 'Supportive care', 'Avoid nephrotoxins', 'Fluid management'],
    description: 'Inflammation of the renal interstitium, most commonly drug-induced, causing acute kidney injury.',
  },
  'Renal Artery Stenosis': {
    category: 'nephrology',
    name: 'Renal Artery Stenosis',
    symptoms: ['Refractory hypertension', 'Flash pulmonary edema', 'Abdominal bruit', 'Progressive renal failure', 'Asymmetry of kidney size'],
    causes: ['Atherosclerosis (older)', 'Fibromuscular dysplasia (younger)', 'Large-vessel vasculitis'],
    treatment: ['Angioplasty/stenting (selected)', 'Surgical revascularization', 'Blood pressure control', 'Medical therapy', 'Monitor renal function'],
    description: 'Narrowing of the renal artery causing renovascular hypertension and ischemic nephropathy.',
  },
  'Cystitis (Interstitial)': {
    category: 'urology',
    name: 'Interstitial Cystitis',
    symptoms: ['Chronic pelvic pain', 'Urinary urgency/frequency', 'Pain with bladder filling', 'Pain with urination relieved by voiding', 'Dyspareunia'],
    causes: ['Bladder epithelial dysfunction', 'Mast cell activation', 'Autoimmune component', 'Pelvic floor disorder'],
    treatment: ['Bladder instillations (DMSO)', 'Pentosan polysulfate', 'Antihistamines', 'Pelvic floor therapy', 'Oral medications', 'Bladder hydrodistention'],
    description: 'A chronic bladder pain syndrome of pelvic pain and lower urinary symptoms without identifiable infection.',
  },
  'Rhabdomyolysis': {
    category: 'nephrology',
    name: 'Rhabdomyolysis',
    symptoms: ['Muscle pain/weakness', 'Dark red/brown urine', 'Malaise', 'Elevated CK', 'Acute kidney injury', 'Swelling'],
    causes: ['Crush injury', 'Extreme exertion', 'Drugs/toxins (statins, cocaine)', 'Sepsis', 'Hyperthermia', 'Seizures'],
    treatment: ['Aggressive IV fluids', 'Electrolyte correction', 'Urine alkalinization (selected)', 'Dialysis (severe AKI)', 'Treat underlying cause'],
    description: 'Breakdown of skeletal muscle releasing myoglobin, causing pigment nephropathy and acute kidney injury.',
  },
  'Vesicoureteral Reflux': {
    category: 'urology',
    name: 'Vesicoureteral Reflux',
    symptoms: ['Recurrent urinary infections', 'Failure to thrive', 'Fever', 'Flank pain', 'Pyelonephritis in children'],
    causes: ['Congenital reflux of urine to kidneys', 'Short submucosal ureter', 'Bladder dysfunction', 'Genetic predisposition'],
    treatment: ['Antibiotic prophylaxis', 'Spontaneous resolution (mild)', 'Endoscopic injection (Deflux)', 'Ureteral reimplantation surgery', 'Bladder management'],
    description: 'Retrograde flow of urine from the bladder into the ureters/kidneys, causing reflux nephropathy.',
  },
  'Haematuria (Hematuria)': {
    category: 'urology',
    name: 'Hematuria',
    symptoms: ['Blood in urine', 'Often asymptomatic', 'Pain (if stones)', 'Frequency/dysuria (if infection)'],
    causes: ['Urinary infection', 'Stones', 'Glomerular disease', 'Malignancy', 'Trauma', 'Exercise'],
    treatment: ['Diagnostic workup (UA, culture, imaging, cystoscopy)', 'Treat underlying cause', 'Investigate urothelial malignancy', 'Referral (nephrology/urology)'],
    description: 'Presence of blood in the urine, microscopic or gross, requiring investigation for renal or urologic disease.',
  },
};